// Code generated by oapi-codegen; DO NOT EDIT.

package output

import (
	"bytes"
	"compress/gzip"
	"context"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"strings"
	"sync"

	oapiCodegenHelpersPkg "github.com/oapi-codegen/oapi-codegen-exp/experimental/runtime/helpers"
	oapiCodegenParamsPkg "github.com/oapi-codegen/oapi-codegen-exp/experimental/runtime/params"
	oapiCodegenTypesPkg "github.com/oapi-codegen/oapi-codegen-exp/experimental/runtime/types"
)

// #/components/schemas/Bar
type Bar struct {
	Value *string `form:"value,omitempty" json:"value,omitempty"`
}

// ApplyDefaults sets default values for fields that are nil.
func (s *Bar) ApplyDefaults() {
}

// #/components/schemas/Bar2
type Bar2 struct {
	Value *float32 `form:"value,omitempty" json:"value,omitempty"`
}

// ApplyDefaults sets default values for fields that are nil.
func (s *Bar2) ApplyDefaults() {
}

// #/components/schemas/CreateItemResponse
type CreateItemResponse struct {
	ID   *string `form:"id,omitempty" json:"id,omitempty"`
	Name *string `form:"name,omitempty" json:"name,omitempty"`
}

// ApplyDefaults sets default values for fields that are nil.
func (s *CreateItemResponse) ApplyDefaults() {
}

// #/components/schemas/ListItemsResponse
type ListItemsResponse = string

// #/components/schemas/QueryResponse
type QueryResponse struct {
	Results []string `form:"results,omitempty" json:"results,omitempty"`
}

// ApplyDefaults sets default values for fields that are nil.
func (s *QueryResponse) ApplyDefaults() {
}

// #/components/schemas/GetStatusResponse
type GetStatusResponse struct {
	Status    *string `form:"status,omitempty" json:"status,omitempty"`
	Timestamp *string `form:"timestamp,omitempty" json:"timestamp,omitempty"`
}

// ApplyDefaults sets default values for fields that are nil.
func (s *GetStatusResponse) ApplyDefaults() {
}

// #/components/schemas/Order
type Order struct {
	ID      *string `form:"id,omitempty" json:"id,omitempty"`
	Product *string `form:"product,omitempty" json:"product,omitempty"`
}

// ApplyDefaults sets default values for fields that are nil.
func (s *Order) ApplyDefaults() {
}

// #/components/schemas/Pet
type Pet struct {
	ID   *int    `form:"id,omitempty" json:"id,omitempty"`
	Name *string `form:"name,omitempty" json:"name,omitempty"`
}

// ApplyDefaults sets default values for fields that are nil.
func (s *Pet) ApplyDefaults() {
}

type Widget = string

type Metadata = string

// #/components/schemas/Resource_MVO
type ResourceMVO struct {
	Name   *string `form:"name,omitempty" json:"name,omitempty"`
	Status *string `form:"status,omitempty" json:"status,omitempty"`
}

// ApplyDefaults sets default values for fields that are nil.
func (s *ResourceMVO) ApplyDefaults() {
}

// #/components/schemas/Resource
type Resource struct {
	ID     *string `form:"id,omitempty" json:"id,omitempty"`
	Name   *string `form:"name,omitempty" json:"name,omitempty"`
	Status *string `form:"status,omitempty" json:"status,omitempty"`
}

// ApplyDefaults sets default values for fields that are nil.
func (s *Resource) ApplyDefaults() {
}

// #/components/schemas/JsonPatch
type JSONPatch = []JSONPatchItem

// #/components/schemas/JsonPatch/items
type JSONPatchItem struct {
	Op   *string `form:"op,omitempty" json:"op,omitempty"`
	Path *string `form:"path,omitempty" json:"path,omitempty"`
}

// ApplyDefaults sets default values for fields that are nil.
func (s *JSONPatchItem) ApplyDefaults() {
}

// #/components/schemas/Qux
type CustomQux struct {
	Label *string `form:"label,omitempty" json:"label,omitempty"`
}

// ApplyDefaults sets default values for fields that are nil.
func (s *CustomQux) ApplyDefaults() {
}

type Zap = string

// #/paths//foo/post/requestBody/content/application/json/schema
type PostFooJSONRequest struct {
	Value *int `form:"value,omitempty" json:"value,omitempty"`
}

// ApplyDefaults sets default values for fields that are nil.
func (s *PostFooJSONRequest) ApplyDefaults() {
}

// #/paths//foo/post/responses/200/content/application/json/schema
type PostFooJSONResponse struct {
	Value1 *Bar  `form:"value1,omitempty" json:"value1,omitempty"`
	Value2 *Bar2 `form:"value2,omitempty" json:"value2,omitempty"`
}

// ApplyDefaults sets default values for fields that are nil.
func (s *PostFooJSONResponse) ApplyDefaults() {
	if s.Value1 != nil {
		s.Value1.ApplyDefaults()
	}
	if s.Value2 != nil {
		s.Value2.ApplyDefaults()
	}
}

// #/paths//items/post/requestBody/content/application/json/schema
type CreateItemJSONRequest struct {
	Name *string `form:"name,omitempty" json:"name,omitempty"`
}

// ApplyDefaults sets default values for fields that are nil.
func (s *CreateItemJSONRequest) ApplyDefaults() {
}

// #/paths//query/post/requestBody/content/application/json/schema
type QueryJSONRequest struct {
	Q *string `form:"q,omitempty" json:"q,omitempty"`
}

// ApplyDefaults sets default values for fields that are nil.
func (s *QueryJSONRequest) ApplyDefaults() {
}

// #/paths//qux/get/responses/200/content/application/json/schema
type GetQuxJSONResponse struct {
	Data *string `form:"data,omitempty" json:"data,omitempty"`
}

// ApplyDefaults sets default values for fields that are nil.
func (s *GetQuxJSONResponse) ApplyDefaults() {
}

// #/paths//zap/get/responses/200/content/application/json/schema
type GetZapJSONResponse struct {
	Result *string `form:"result,omitempty" json:"result,omitempty"`
}

// ApplyDefaults sets default values for fields that are nil.
func (s *GetZapJSONResponse) ApplyDefaults() {
}

// #/paths//orders/post/requestBody/content/application/json/schema
type CreateOrderJSONRequest1 struct {
	ID      *string `form:"id,omitempty" json:"id,omitempty"`
	Product *string `form:"product,omitempty" json:"product,omitempty"`
}

// ApplyDefaults sets default values for fields that are nil.
func (s *CreateOrderJSONRequest1) ApplyDefaults() {
}

// #/paths//orders/post/requestBody/content/application/merge-patch+json/schema
type CreateOrderJSONRequest2 struct {
	Product *string `form:"product,omitempty" json:"product,omitempty"`
}

// ApplyDefaults sets default values for fields that are nil.
func (s *CreateOrderJSONRequest2) ApplyDefaults() {
}

// #/paths//orders/post/requestBody/content/application/json-patch+json/schema
type CreateOrderJSONRequest3 = []PostOrdersRequest

// #/paths//orders/post/requestBody/content/application/json-patch+json/schema/items
type PostOrdersRequest struct {
	Op    *string `form:"op,omitempty" json:"op,omitempty"`
	Path  *string `form:"path,omitempty" json:"path,omitempty"`
	Value *string `form:"value,omitempty" json:"value,omitempty"`
}

// ApplyDefaults sets default values for fields that are nil.
func (s *PostOrdersRequest) ApplyDefaults() {
}

// #/paths//entities/get/responses/200/content/application/json/schema
type ListEntitiesJSONResponse struct {
	Data     []Widget `form:"data,omitempty" json:"data,omitempty"`
	Metadata string   `form:"metadata,omitempty" json:"metadata,omitempty"`
}

// ApplyDefaults sets default values for fields that are nil.
func (s *ListEntitiesJSONResponse) ApplyDefaults() {
}

// #/paths//entities/get/responses/200/content/application/json/schema/properties/data
type GetEntities200Response = []Widget

// #/paths//resources/{id}/patch/responses/200/content/application/json-patch+json/schema

type PatchResourceJSONResponse2001 struct {
	union json.RawMessage
}

// AsResource returns the union data inside the PatchResourceJSONResponse2001 as a Resource.
func (t PatchResourceJSONResponse2001) AsResource() (Resource, error) {
	var body Resource
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromResource overwrites any union data inside the PatchResourceJSONResponse2001 as the provided Resource.
func (t *PatchResourceJSONResponse2001) FromResource(v Resource) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeResource performs a merge with any union data inside the PatchResourceJSONResponse2001, using the provided Resource.
func (t *PatchResourceJSONResponse2001) MergeResource(v Resource) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}
	merged, err := oapiCodegenHelpersPkg.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsPatchResourcesID200ResponseJSONOneOf11 returns the union data inside the PatchResourceJSONResponse2001 as a PatchResourcesID200ResponseJSONOneOf11.
func (t PatchResourceJSONResponse2001) AsPatchResourcesID200ResponseJSONOneOf11() (PatchResourcesID200ResponseJSONOneOf11, error) {
	var body PatchResourcesID200ResponseJSONOneOf11
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromPatchResourcesID200ResponseJSONOneOf11 overwrites any union data inside the PatchResourceJSONResponse2001 as the provided PatchResourcesID200ResponseJSONOneOf11.
func (t *PatchResourceJSONResponse2001) FromPatchResourcesID200ResponseJSONOneOf11(v PatchResourcesID200ResponseJSONOneOf11) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergePatchResourcesID200ResponseJSONOneOf11 performs a merge with any union data inside the PatchResourceJSONResponse2001, using the provided PatchResourcesID200ResponseJSONOneOf11.
func (t *PatchResourceJSONResponse2001) MergePatchResourcesID200ResponseJSONOneOf11(v PatchResourcesID200ResponseJSONOneOf11) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}
	merged, err := oapiCodegenHelpersPkg.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsPatchResourcesID200ResponseJSONOneOf21 returns the union data inside the PatchResourceJSONResponse2001 as a PatchResourcesID200ResponseJSONOneOf21.
func (t PatchResourceJSONResponse2001) AsPatchResourcesID200ResponseJSONOneOf21() (PatchResourcesID200ResponseJSONOneOf21, error) {
	var body PatchResourcesID200ResponseJSONOneOf21
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromPatchResourcesID200ResponseJSONOneOf21 overwrites any union data inside the PatchResourceJSONResponse2001 as the provided PatchResourcesID200ResponseJSONOneOf21.
func (t *PatchResourceJSONResponse2001) FromPatchResourcesID200ResponseJSONOneOf21(v PatchResourcesID200ResponseJSONOneOf21) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergePatchResourcesID200ResponseJSONOneOf21 performs a merge with any union data inside the PatchResourceJSONResponse2001, using the provided PatchResourcesID200ResponseJSONOneOf21.
func (t *PatchResourceJSONResponse2001) MergePatchResourcesID200ResponseJSONOneOf21(v PatchResourcesID200ResponseJSONOneOf21) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}
	merged, err := oapiCodegenHelpersPkg.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t PatchResourceJSONResponse2001) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *PatchResourceJSONResponse2001) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}

// ApplyDefaults sets default values for fields that are nil.
func (t *PatchResourceJSONResponse2001) ApplyDefaults() {
}

// #/paths//resources/{id}/patch/responses/200/content/application/json-patch+json/schema/oneOf/1
type PatchResourcesID200ResponseJSONOneOf11 = []Resource

// #/paths//resources/{id}/patch/responses/200/content/application/json-patch+json/schema/oneOf/2
type PatchResourcesID200ResponseJSONOneOf21 = oapiCodegenTypesPkg.Nullable[string]

// #/paths//resources/{id}/patch/responses/200/content/application/json-patch-query+json/schema

type PatchResourceJSONResponse2002 struct {
	union json.RawMessage
}

// AsResource returns the union data inside the PatchResourceJSONResponse2002 as a Resource.
func (t PatchResourceJSONResponse2002) AsResource() (Resource, error) {
	var body Resource
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromResource overwrites any union data inside the PatchResourceJSONResponse2002 as the provided Resource.
func (t *PatchResourceJSONResponse2002) FromResource(v Resource) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeResource performs a merge with any union data inside the PatchResourceJSONResponse2002, using the provided Resource.
func (t *PatchResourceJSONResponse2002) MergeResource(v Resource) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}
	merged, err := oapiCodegenHelpersPkg.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsPatchResourcesID200ResponseJSONOneOf12 returns the union data inside the PatchResourceJSONResponse2002 as a PatchResourcesID200ResponseJSONOneOf12.
func (t PatchResourceJSONResponse2002) AsPatchResourcesID200ResponseJSONOneOf12() (PatchResourcesID200ResponseJSONOneOf12, error) {
	var body PatchResourcesID200ResponseJSONOneOf12
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromPatchResourcesID200ResponseJSONOneOf12 overwrites any union data inside the PatchResourceJSONResponse2002 as the provided PatchResourcesID200ResponseJSONOneOf12.
func (t *PatchResourceJSONResponse2002) FromPatchResourcesID200ResponseJSONOneOf12(v PatchResourcesID200ResponseJSONOneOf12) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergePatchResourcesID200ResponseJSONOneOf12 performs a merge with any union data inside the PatchResourceJSONResponse2002, using the provided PatchResourcesID200ResponseJSONOneOf12.
func (t *PatchResourceJSONResponse2002) MergePatchResourcesID200ResponseJSONOneOf12(v PatchResourcesID200ResponseJSONOneOf12) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}
	merged, err := oapiCodegenHelpersPkg.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsPatchResourcesID200ResponseJSONOneOf22 returns the union data inside the PatchResourceJSONResponse2002 as a PatchResourcesID200ResponseJSONOneOf22.
func (t PatchResourceJSONResponse2002) AsPatchResourcesID200ResponseJSONOneOf22() (PatchResourcesID200ResponseJSONOneOf22, error) {
	var body PatchResourcesID200ResponseJSONOneOf22
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromPatchResourcesID200ResponseJSONOneOf22 overwrites any union data inside the PatchResourceJSONResponse2002 as the provided PatchResourcesID200ResponseJSONOneOf22.
func (t *PatchResourceJSONResponse2002) FromPatchResourcesID200ResponseJSONOneOf22(v PatchResourcesID200ResponseJSONOneOf22) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergePatchResourcesID200ResponseJSONOneOf22 performs a merge with any union data inside the PatchResourceJSONResponse2002, using the provided PatchResourcesID200ResponseJSONOneOf22.
func (t *PatchResourceJSONResponse2002) MergePatchResourcesID200ResponseJSONOneOf22(v PatchResourcesID200ResponseJSONOneOf22) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}
	merged, err := oapiCodegenHelpersPkg.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t PatchResourceJSONResponse2002) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *PatchResourceJSONResponse2002) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}

// ApplyDefaults sets default values for fields that are nil.
func (t *PatchResourceJSONResponse2002) ApplyDefaults() {
}

// #/paths//resources/{id}/patch/responses/200/content/application/json-patch-query+json/schema/oneOf/1
type PatchResourcesID200ResponseJSONOneOf12 = []Resource

// #/paths//resources/{id}/patch/responses/200/content/application/json-patch-query+json/schema/oneOf/2
type PatchResourcesID200ResponseJSONOneOf22 = oapiCodegenTypesPkg.Nullable[string]

// #/paths//pets/post/requestBody/content/application/json/schema
type CreatePetJSONRequest struct {
	Name    *string `form:"name,omitempty" json:"name,omitempty"`
	Species *string `form:"species,omitempty" json:"species,omitempty"`
}

// ApplyDefaults sets default values for fields that are nil.
func (s *CreatePetJSONRequest) ApplyDefaults() {
}

// Base64-encoded, gzip-compressed OpenAPI spec.
var openAPISpecJSON = []string{
	"H4sIAAAAAAAC/+xaWXMbuRF+56/oolJFqZaUKMoq21OVB0vrXduJI/moJOWXFDTT5GB3BhgDGInK8d9T",
	"OObAXBxaWnudih4kEUej0efXDfIMGcloAGfHy+PTyYSyNQ8mAIqqBAOYXvI0Exgjk/QWgZEUIeRJQiXl",
	"DARKnuRK/6tQqukEIEIZCprpsQD+PQEAeLlFEVKJEkiSQMTDPEWmMGpSy4hSKJgEEgouJVApc72JRXD9",
	"XgaG1sFquZzDwer8ifl9rn8/X83h4Mny6RwOnj1/PoeD07Nz/eH0yfnS/HmqF58+PT3Tf549O9Wbls/1",
	"ktXq9MzQfZFIDiG/RSGBk4wuQh7hBtkCt9nB6RM4pCyhDPWNM84kAr/5BUMFd1TF8AeBa8gEz1AoivLo",
	"eAKgKRkZLI+Xx8vJJCMqNnc4gGt7T3gRwKW+6EJiaGRYieLQ3d27rr2ivcD1e3PxI0NwekHEFEiWIRES",
	"KAMZxpgSOYeMCJKiQiHnIPBzjlJd8Iii+WhvIudGwjGSCIXUrJ+sObfSzrhU9j8AfTui2XwdBWbiJ87d",
	"VHVKsRhgYaQSwOzgJORpxhkyJU+qlScXRMzc6oqz+4pA13bvCj4Fd5lq/2q5rD70kXO7LClPORcBfDBS",
	"hFsJYUKRKbgTWsai0k7DtJ6cL61C3M7ppUCi8LXC9L07amqVHKG0phOWKwrqRgNUYSp36KDaOiRGPUgF",
	"RgEokWM5HHKmkKm6hEiWJTQ05E9+kZzV58CZlD8GoO4zDJwvNKYqf2huAuP47dGCnFSCss1ozXoR5+pP",
	"tZmOS+66Zt9Fuw3I+dlJW8/Gmur2dFnaE0kokb1WZaPXkdtdGNKfqVSavKzs6NCKyZI7aphVUqyvWxXA",
	"BrtNqVz+PQm9JZOGB/8YwFVxSZtq/ujOqaK4GS4Evzo/9933XY7ivs9zP+tJz2nNyA6nNWu+O3/9/L/k",
	"rJ5WGzbzsvTSlKgwRgk8+6FYW8/Kzx3a8A3mZ1QfFFG57DOaTbHAMxxphoJBFy13fk+ibsmjIe6fAtgu",
	"NnyhTWlhfBG3SkNNzuAHCLvBUcNFt1OIiWzS0ZDGF33p82aPc9jtTqG/y7f9Ep+tlsvZeJTxLt/OduOq",
	"+olfPUAMO852tocsmvbnaf7nmub3VvonkjWUPqhvvdzo+58k26nvTyR7NH1/ItkIfddP/F3pu2T/EfT9",
	"KoC3eaJoliC8+XD1l4J/k0VMzVK7PBya8mZ1eubqmysRYWeFY/TuVQXH8DFGj5g2lLPiPEPPnqliokxF",
	"qqcIZTDVQpuWpkQyiaA4qBhB6pgy1YxPQcZcqBLCHnQIfu6NpCg2uMh0PvmhPatHapOG4seYSlCCbja6",
	"HCUMKFtTRhUClyFNEgtpblDdITJ7s60Cma/XdOvYr4RrKLo5qQRRuKEoIWcJSmkux/IUBQ1hTZLkhoS/",
	"QkgY3Agkv5rp8D5M0PgP12oYV5YYjT2svDMkZt9TunMce4b/OoDX41sH2t6qoOboGnqHHV2Jo8LYHeGY",
	"OGsx59WPqZ8QE+sF5ujyFqVHhUSIe11YlHwcw0sSljTuQe+TMc+TCHLtIrG1sSapmQQbmnWBMgfGlSYR",
	"5SFClFvho10RYZgQa0G2AYFM0QqJDlUtL93KB8Sp38hQBqD2MNgGiIgiXeMFUSIEue+cr/UN2j9Dpvs3",
	"Gm1QzTp2pqhIP0NDNN+6nQ2PeBPAj6X+C1tleLWGFNMbE/Fs/6+0ay9XGFov4PrFx8tXlT2AQJULJiHt",
	"zzLWj4aDdSMc900uTB1nlxiyQwHfuWm128ToJjG4JYISpiybMiYCjTNH2hlCkjgZuQrWeLUT3iHjbKEV",
	"cVRI0B7ogoWhl+ZSGRfElKoh/4M1F6BiLkvdFDQ1HSv8KKJ6LUmS+7lJEfV0aziXVda0cFwCaQUIq4/p",
	"e5Q8FyH+4+1fr6ZHcBejwBbVQpFFlDLBy2SngqgVm5m2HU3OfMsxezQfEV2vUVTUTMgRjgt58i8a/cfl",
	"OK2dbtymZwrGB7ugBicAjWreQ5khENeGekBed3TpLLy/KMXWRT97NNi7Wi5LwtdaUC4AeM3uwFPvrSwM",
	"u6qxi563w4DXqDwEeMNVPAADtU4zVOPQyjWqhwnyuoqd3wVSMfxOqgm9281ZQhdEFBQ7EllX+rolSe41",
	"dT0zLYiuHocqy3VMslTbzdc9z6BRL9t9Dev23VrdSJ+J+lKvAbUnrwJlnijZ5qWJCTqQQJuTVn9mT27q",
	"jasB6SmaolQkzYZF6FWLRa3vSr9mbV+FjmLFXUzDWENgR+usUWKW5V5KsqKsa1V0tk1uKD6+EVn0q4aF",
	"cF2B3QecTJnCTVmAjbFfr2IpwqoRdlWP5BIjKJMvERtUJhQ330YrLo8d7c7qxcxZ4Dlw5fL4hjz3VIIZ",
	"f9vAsg88TnFFkn7hN+T6ppAr+JBnyLa9hYUwGw2OmRyBjkpklCW51NDI0RoFkODwjeTMpPJmyWnRYkGt",
	"Ccp1QToAyOeg7jjwtfPdAvM6YiOQbw2aAtRltacLDbrHyGDn8fCVM9A+LJaq9Hms549G7uisZLsrWJ7t",
	"hKoOWMe7ctPDXwlGvBMEcJlLxdN3+XbUk4FO3tsx0aNJfUD5CbnBZGxw/oK++XDnvDhoVAcd4BPJHil4",
	"5kynk6F7NwuqGia10r0hRYbTJVX9abWJiZukPfTeot6C4UMQvL9C6+j99Pd9WkB3REZ5FXQjIa28Xvjj",
	"d7sdxZ09b9s/vqWkIPvxPsMPZvTwqAM1fQsR+lF0MAD1wLGBPUMNnt/gLl/OXKODNY63dkexs5P4hV8f",
	"aGaFnarpyhAjNvX40A6Y/S1MtfsLUAOXkxmGnbIdShZvggE0WTTqTEI1IaMTnRag83I8xMRtiJmq9zst",
	"vrPwssQf/ajtwRoZan109bwe5t4PO21Pfx06rBStabi5b3S2slt3brzhPEHCbHL0Oli1rV7n6oKIcqmb",
	"947UP39f1Hb3se921b/P+c0y8Ol+fbQayx6Z1d5kVrNJE1960n6hZ5ry/hZi6n4LaoehGlJsXOQTyX4P",
	"F7GttC+IqA4Vm5g5UN26l4zKv2tYq/fxZ9TDT1Egj3r+GXz6cZRGPwCZXrbf3O9UspkBmYchSvk1o/rX",
	"i+iPEs2NapsmuNjz/GLX0ONw78PwQ47qgWEsTxJyk2DjMWvnS+r/hYWT/wYAAP//uCNlHY8zAAA=",
}

// decodeOpenAPISpec decodes and decompresses the embedded spec.
func decodeOpenAPISpec() ([]byte, error) {
	joined := strings.Join(openAPISpecJSON, "")
	raw, err := base64.StdEncoding.DecodeString(joined)
	if err != nil {
		return nil, fmt.Errorf("decoding base64: %w", err)
	}
	r, err := gzip.NewReader(bytes.NewReader(raw))
	if err != nil {
		return nil, fmt.Errorf("creating gzip reader: %w", err)
	}
	defer r.Close()
	var out bytes.Buffer
	if _, err := out.ReadFrom(r); err != nil {
		return nil, fmt.Errorf("decompressing: %w", err)
	}
	return out.Bytes(), nil
}

// decodeOpenAPISpecCached returns a closure that caches the decoded spec.
func decodeOpenAPISpecCached() func() ([]byte, error) {
	var cached []byte
	var cachedErr error
	var once sync.Once
	return func() ([]byte, error) {
		once.Do(func() {
			cached, cachedErr = decodeOpenAPISpec()
		})
		return cached, cachedErr
	}
}

var openAPISpec = decodeOpenAPISpecCached()

// GetOpenAPISpecJSON returns the raw OpenAPI spec as JSON bytes.
func GetOpenAPISpecJSON() ([]byte, error) {
	return openAPISpec()
}

type postFooJSONRequestBody = any

type createItemJSONRequestBody = any

type createOrderJSONRequestBody = any

type createOrderApplicationJsonPatchJsonRequestBody = any

type createOrderApplicationMergePatchJsonRequestBody = any

type createPetJSONRequestBody = any

type queryJSONRequestBody = any

type postQuxJSONRequestBody = CustomQux

type patchResourceJSONRequestBody = ResourceMVO

type patchResourceApplicationJsonPatchJsonRequestBody = JSONPatch

type patchResourceApplicationMergePatchJsonRequestBody = ResourceMVO

type postZapJSONRequestBody = Zap

// RequestEditorFn is the function signature for the RequestEditor callback function.
type RequestEditorFn func(ctx context.Context, req *http.Request) error

// HttpRequestDoer performs HTTP requests.
// The standard http.Client implements this interface.
type HttpRequestDoer interface {
	Do(req *http.Request) (*http.Response, error)
}

// Client which conforms to the OpenAPI3 specification for this service.
type Client struct {
	// The endpoint of the server conforming to this interface, with scheme,
	// https://api.deepmap.com for example. This can contain a path relative
	// to the server, such as https://api.deepmap.com/dev-test, and all the
	// paths in the OpenAPI spec will be appended to the server.
	Server string

	// Doer for performing requests, typically a *http.Client with any
	// customized settings, such as certificate chains.
	Client HttpRequestDoer

	// A list of callbacks for modifying requests which are generated before sending over
	// the network.
	RequestEditors []RequestEditorFn
}

// ClientOption allows setting custom parameters during construction.
type ClientOption func(*Client) error

// NewClient creates a new Client with reasonable defaults.
func NewClient(server string, opts ...ClientOption) (*Client, error) {
	client := Client{
		Server: server,
	}
	for _, o := range opts {
		if err := o(&client); err != nil {
			return nil, err
		}
	}
	// Ensure the server URL always has a trailing slash
	if !strings.HasSuffix(client.Server, "/") {
		client.Server += "/"
	}
	// Create httpClient if not already present
	if client.Client == nil {
		client.Client = &http.Client{}
	}
	return &client, nil
}

// WithHTTPClient allows overriding the default Doer, which is
// automatically created using http.Client. This is useful for tests.
func WithHTTPClient(doer HttpRequestDoer) ClientOption {
	return func(c *Client) error {
		c.Client = doer
		return nil
	}
}

// WithRequestEditorFn allows setting up a callback function, which will be
// called right before sending the request. This can be used to mutate the request.
func WithRequestEditorFn(fn RequestEditorFn) ClientOption {
	return func(c *Client) error {
		c.RequestEditors = append(c.RequestEditors, fn)
		return nil
	}
}

// WithBaseURL overrides the baseURL.
func WithBaseURL(baseURL string) ClientOption {
	return func(c *Client) error {
		newBaseURL, err := url.Parse(baseURL)
		if err != nil {
			return err
		}
		c.Server = newBaseURL.String()
		return nil
	}
}

func (c *Client) applyEditors(ctx context.Context, req *http.Request, additionalEditors []RequestEditorFn) error {
	for _, r := range c.RequestEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	for _, r := range additionalEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	return nil
}

// ClientInterface is the interface specification for the client.
type ClientInterface interface {
	// ListEntities makes a GET request to /entities
	ListEntities(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error)
	// PostFooWithBody makes a POST request to /foo
	PostFooWithBody(ctx context.Context, params *PostFooParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)
	PostFoo(ctx context.Context, params *PostFooParams, body postFooJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)
	// ListItems makes a GET request to /items
	ListItems(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error)
	// CreateItemWithBody makes a POST request to /items
	CreateItemWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)
	CreateItem(ctx context.Context, body createItemJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)
	// CreateOrderWithBody makes a POST request to /orders
	CreateOrderWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)
	CreateOrder(ctx context.Context, body createOrderJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)
	CreateOrderWithApplicationJsonPatchJsonBody(ctx context.Context, body createOrderApplicationJsonPatchJsonRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)
	CreateOrderWithApplicationMergePatchJsonBody(ctx context.Context, body createOrderApplicationMergePatchJsonRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)
	// CreatePetWithBody makes a POST request to /pets
	CreatePetWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)
	CreatePet(ctx context.Context, body createPetJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)
	// QueryWithBody makes a POST request to /query
	QueryWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)
	Query(ctx context.Context, body queryJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)
	// GetQux makes a GET request to /qux
	GetQux(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error)
	// PostQuxWithBody makes a POST request to /qux
	PostQuxWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)
	PostQux(ctx context.Context, body postQuxJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)
	// PatchResourceWithBody makes a PATCH request to /resources/{id}
	PatchResourceWithBody(ctx context.Context, id string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)
	PatchResource(ctx context.Context, id string, body patchResourceJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)
	PatchResourceWithApplicationJsonPatchJsonBody(ctx context.Context, id string, body patchResourceApplicationJsonPatchJsonRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)
	PatchResourceWithApplicationMergePatchJsonBody(ctx context.Context, id string, body patchResourceApplicationMergePatchJsonRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)
	// GetStatus makes a GET request to /status
	GetStatus(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error)
	// GetZap makes a GET request to /zap
	GetZap(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error)
	// PostZapWithBody makes a POST request to /zap
	PostZapWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)
	PostZap(ctx context.Context, body postZapJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)
}

// PostFooParams defines parameters for PostFoo.
type PostFooParams struct {
	// bar (optional)
	Bar *string `form:"bar" json:"bar"`
}

// ListEntities makes a GET request to /entities

func (c *Client) ListEntities(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewListEntitiesRequest(c.Server)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// PostFooWithBody makes a POST request to /foo

func (c *Client) PostFooWithBody(ctx context.Context, params *PostFooParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPostFooRequestWithBody(c.Server, params, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// PostFoo makes a POST request to /foo with application/json body
func (c *Client) PostFoo(ctx context.Context, params *PostFooParams, body postFooJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPostFooRequest(c.Server, params, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// ListItems makes a GET request to /items

func (c *Client) ListItems(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewListItemsRequest(c.Server)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// CreateItemWithBody makes a POST request to /items

func (c *Client) CreateItemWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewCreateItemRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// CreateItem makes a POST request to /items with application/json body
func (c *Client) CreateItem(ctx context.Context, body createItemJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewCreateItemRequest(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// CreateOrderWithBody makes a POST request to /orders

func (c *Client) CreateOrderWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewCreateOrderRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// CreateOrder makes a POST request to /orders with application/json body
func (c *Client) CreateOrder(ctx context.Context, body createOrderJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewCreateOrderRequest(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// CreateOrderWithApplicationJsonPatchJsonBody makes a POST request to /orders with application/json-patch+json body
func (c *Client) CreateOrderWithApplicationJsonPatchJsonBody(ctx context.Context, body createOrderApplicationJsonPatchJsonRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewCreateOrderRequestWithApplicationJsonPatchJsonBody(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// CreateOrderWithApplicationMergePatchJsonBody makes a POST request to /orders with application/merge-patch+json body
func (c *Client) CreateOrderWithApplicationMergePatchJsonBody(ctx context.Context, body createOrderApplicationMergePatchJsonRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewCreateOrderRequestWithApplicationMergePatchJsonBody(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// CreatePetWithBody makes a POST request to /pets

func (c *Client) CreatePetWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewCreatePetRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// CreatePet makes a POST request to /pets with application/json body
func (c *Client) CreatePet(ctx context.Context, body createPetJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewCreatePetRequest(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// QueryWithBody makes a POST request to /query

func (c *Client) QueryWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewQueryRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// Query makes a POST request to /query with application/json body
func (c *Client) Query(ctx context.Context, body queryJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewQueryRequest(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// GetQux makes a GET request to /qux

func (c *Client) GetQux(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetQuxRequest(c.Server)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// PostQuxWithBody makes a POST request to /qux

func (c *Client) PostQuxWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPostQuxRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// PostQux makes a POST request to /qux with application/json body
func (c *Client) PostQux(ctx context.Context, body postQuxJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPostQuxRequest(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// PatchResourceWithBody makes a PATCH request to /resources/{id}

func (c *Client) PatchResourceWithBody(ctx context.Context, id string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPatchResourceRequestWithBody(c.Server, id, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// PatchResource makes a PATCH request to /resources/{id} with application/json body
func (c *Client) PatchResource(ctx context.Context, id string, body patchResourceJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPatchResourceRequest(c.Server, id, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// PatchResourceWithApplicationJsonPatchJsonBody makes a PATCH request to /resources/{id} with application/json-patch+json body
func (c *Client) PatchResourceWithApplicationJsonPatchJsonBody(ctx context.Context, id string, body patchResourceApplicationJsonPatchJsonRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPatchResourceRequestWithApplicationJsonPatchJsonBody(c.Server, id, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// PatchResourceWithApplicationMergePatchJsonBody makes a PATCH request to /resources/{id} with application/merge-patch+json body
func (c *Client) PatchResourceWithApplicationMergePatchJsonBody(ctx context.Context, id string, body patchResourceApplicationMergePatchJsonRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPatchResourceRequestWithApplicationMergePatchJsonBody(c.Server, id, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// GetStatus makes a GET request to /status

func (c *Client) GetStatus(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetStatusRequest(c.Server)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// GetZap makes a GET request to /zap

func (c *Client) GetZap(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetZapRequest(c.Server)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// PostZapWithBody makes a POST request to /zap

func (c *Client) PostZapWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPostZapRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// PostZap makes a POST request to /zap with application/json body
func (c *Client) PostZap(ctx context.Context, body postZapJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPostZapRequest(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// NewListEntitiesRequest creates a GET request for /entities
func NewListEntitiesRequest(server string) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/entities")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	reqURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", reqURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewPostFooRequest creates a POST request for /foo with application/json body
func NewPostFooRequest(server string, params *PostFooParams, body postFooJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewPostFooRequestWithBody(server, params, "application/json", bodyReader)
}

// NewPostFooRequestWithBody creates a POST request for /foo with any body
func NewPostFooRequestWithBody(server string, params *PostFooParams, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/foo")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	reqURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	if params != nil {
		queryValues := reqURL.Query()
		if params.Bar != nil {
			if queryFrag, err := oapiCodegenParamsPkg.StyleFormExplodeParam("bar", oapiCodegenParamsPkg.ParamLocationQuery, *params.Bar); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}
		}
		reqURL.RawQuery = queryValues.Encode()
	}

	req, err := http.NewRequest("POST", reqURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewListItemsRequest creates a GET request for /items
func NewListItemsRequest(server string) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/items")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	reqURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", reqURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewCreateItemRequest creates a POST request for /items with application/json body
func NewCreateItemRequest(server string, body createItemJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewCreateItemRequestWithBody(server, "application/json", bodyReader)
}

// NewCreateItemRequestWithBody creates a POST request for /items with any body
func NewCreateItemRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/items")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	reqURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", reqURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewCreateOrderRequest creates a POST request for /orders with application/json body
func NewCreateOrderRequest(server string, body createOrderJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewCreateOrderRequestWithBody(server, "application/json", bodyReader)
}

// NewCreateOrderRequestWithApplicationJsonPatchJsonBody creates a POST request for /orders with application/json-patch+json body
func NewCreateOrderRequestWithApplicationJsonPatchJsonBody(server string, body createOrderApplicationJsonPatchJsonRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewCreateOrderRequestWithBody(server, "application/json-patch+json", bodyReader)
}

// NewCreateOrderRequestWithApplicationMergePatchJsonBody creates a POST request for /orders with application/merge-patch+json body
func NewCreateOrderRequestWithApplicationMergePatchJsonBody(server string, body createOrderApplicationMergePatchJsonRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewCreateOrderRequestWithBody(server, "application/merge-patch+json", bodyReader)
}

// NewCreateOrderRequestWithBody creates a POST request for /orders with any body
func NewCreateOrderRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/orders")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	reqURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", reqURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewCreatePetRequest creates a POST request for /pets with application/json body
func NewCreatePetRequest(server string, body createPetJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewCreatePetRequestWithBody(server, "application/json", bodyReader)
}

// NewCreatePetRequestWithBody creates a POST request for /pets with any body
func NewCreatePetRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/pets")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	reqURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", reqURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewQueryRequest creates a POST request for /query with application/json body
func NewQueryRequest(server string, body queryJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewQueryRequestWithBody(server, "application/json", bodyReader)
}

// NewQueryRequestWithBody creates a POST request for /query with any body
func NewQueryRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/query")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	reqURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", reqURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewGetQuxRequest creates a GET request for /qux
func NewGetQuxRequest(server string) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/qux")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	reqURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", reqURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewPostQuxRequest creates a POST request for /qux with application/json body
func NewPostQuxRequest(server string, body postQuxJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewPostQuxRequestWithBody(server, "application/json", bodyReader)
}

// NewPostQuxRequestWithBody creates a POST request for /qux with any body
func NewPostQuxRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/qux")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	reqURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", reqURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewPatchResourceRequest creates a PATCH request for /resources/{id} with application/json body
func NewPatchResourceRequest(server string, id string, body patchResourceJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewPatchResourceRequestWithBody(server, id, "application/json", bodyReader)
}

// NewPatchResourceRequestWithApplicationJsonPatchJsonBody creates a PATCH request for /resources/{id} with application/json-patch+json body
func NewPatchResourceRequestWithApplicationJsonPatchJsonBody(server string, id string, body patchResourceApplicationJsonPatchJsonRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewPatchResourceRequestWithBody(server, id, "application/json-patch+json", bodyReader)
}

// NewPatchResourceRequestWithApplicationMergePatchJsonBody creates a PATCH request for /resources/{id} with application/merge-patch+json body
func NewPatchResourceRequestWithApplicationMergePatchJsonBody(server string, id string, body patchResourceApplicationMergePatchJsonRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewPatchResourceRequestWithBody(server, id, "application/merge-patch+json", bodyReader)
}

// NewPatchResourceRequestWithBody creates a PATCH request for /resources/{id} with any body
func NewPatchResourceRequestWithBody(server string, id string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	var pathParam0 string
	pathParam0, err = oapiCodegenParamsPkg.StyleSimpleParam("id", oapiCodegenParamsPkg.ParamLocationPath, id)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/resources/%s", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	reqURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("PATCH", reqURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewGetStatusRequest creates a GET request for /status
func NewGetStatusRequest(server string) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/status")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	reqURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", reqURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewGetZapRequest creates a GET request for /zap
func NewGetZapRequest(server string) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/zap")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	reqURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", reqURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewPostZapRequest creates a POST request for /zap with application/json body
func NewPostZapRequest(server string, body postZapJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewPostZapRequestWithBody(server, "application/json", bodyReader)
}

// NewPostZapRequestWithBody creates a POST request for /zap with any body
func NewPostZapRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/zap")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	reqURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", reqURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// ClientHttpError represents an HTTP error response.
// The type parameter E is the type of the parsed error body.
type ClientHttpError[E any] struct {
	StatusCode int
	Body       E
	RawBody    []byte
}

func (e *ClientHttpError[E]) Error() string {
	return fmt.Sprintf("HTTP %d", e.StatusCode)
}

// SimpleClient wraps Client with typed responses for operations that have
// unambiguous response types. Methods return the success type directly,
// and HTTP errors are returned as *ClientHttpError[E] where E is the error type.
type SimpleClient struct {
	*Client
}

// NewSimpleClient creates a new SimpleClient which wraps a Client.
func NewSimpleClient(server string, opts ...ClientOption) (*SimpleClient, error) {
	inner, err := NewClient(server, opts...)
	if err != nil {
		return nil, err
	}
	return &SimpleClient{Client: inner}, nil
}

// ListEntities makes a GET request to /entities and returns the parsed response.

// On success, returns the response body. On HTTP error, returns *ClientHttpError[struct{}].
func (c *SimpleClient) ListEntities(ctx context.Context, reqEditors ...RequestEditorFn) (map[string]any, error) {
	var result map[string]any
	resp, err := c.Client.ListEntities(ctx, reqEditors...)
	if err != nil {
		return result, err
	}
	defer resp.Body.Close()

	rawBody, err := io.ReadAll(resp.Body)
	if err != nil {
		return result, err
	}

	if resp.StatusCode >= 200 && resp.StatusCode < 300 {
		if err := json.Unmarshal(rawBody, &result); err != nil {
			return result, err
		}
		return result, nil
	}

	// No typed error response defined
	return result, &ClientHttpError[struct{}]{
		StatusCode: resp.StatusCode,
		RawBody:    rawBody,
	}
}

// PostFoo makes a POST request to /foo and returns the parsed response.

// On success, returns the response body. On HTTP error, returns *ClientHttpError[struct{}].
func (c *SimpleClient) PostFoo(ctx context.Context, params *PostFooParams, body postFooJSONRequestBody, reqEditors ...RequestEditorFn) (map[string]any, error) {
	var result map[string]any
	resp, err := c.Client.PostFoo(ctx, params, body, reqEditors...)
	if err != nil {
		return result, err
	}
	defer resp.Body.Close()

	rawBody, err := io.ReadAll(resp.Body)
	if err != nil {
		return result, err
	}

	if resp.StatusCode >= 200 && resp.StatusCode < 300 {
		if err := json.Unmarshal(rawBody, &result); err != nil {
			return result, err
		}
		return result, nil
	}

	// No typed error response defined
	return result, &ClientHttpError[struct{}]{
		StatusCode: resp.StatusCode,
		RawBody:    rawBody,
	}
}

// ListItems makes a GET request to /items and returns the parsed response.

// On success, returns the response body. On HTTP error, returns *ClientHttpError[struct{}].
func (c *SimpleClient) ListItems(ctx context.Context, reqEditors ...RequestEditorFn) (ListItemsResponse, error) {
	var result ListItemsResponse
	resp, err := c.Client.ListItems(ctx, reqEditors...)
	if err != nil {
		return result, err
	}
	defer resp.Body.Close()

	rawBody, err := io.ReadAll(resp.Body)
	if err != nil {
		return result, err
	}

	if resp.StatusCode >= 200 && resp.StatusCode < 300 {
		if err := json.Unmarshal(rawBody, &result); err != nil {
			return result, err
		}
		return result, nil
	}

	// No typed error response defined
	return result, &ClientHttpError[struct{}]{
		StatusCode: resp.StatusCode,
		RawBody:    rawBody,
	}
}

// CreateItem makes a POST request to /items and returns the parsed response.

// On success, returns the response body. On HTTP error, returns *ClientHttpError[struct{}].
func (c *SimpleClient) CreateItem(ctx context.Context, body createItemJSONRequestBody, reqEditors ...RequestEditorFn) (CreateItemResponse, error) {
	var result CreateItemResponse
	resp, err := c.Client.CreateItem(ctx, body, reqEditors...)
	if err != nil {
		return result, err
	}
	defer resp.Body.Close()

	rawBody, err := io.ReadAll(resp.Body)
	if err != nil {
		return result, err
	}

	if resp.StatusCode >= 200 && resp.StatusCode < 300 {
		if err := json.Unmarshal(rawBody, &result); err != nil {
			return result, err
		}
		return result, nil
	}

	// No typed error response defined
	return result, &ClientHttpError[struct{}]{
		StatusCode: resp.StatusCode,
		RawBody:    rawBody,
	}
}

// CreateOrder makes a POST request to /orders and returns the parsed response.

// On success, returns the response body. On HTTP error, returns *ClientHttpError[struct{}].
func (c *SimpleClient) CreateOrder(ctx context.Context, body createOrderJSONRequestBody, reqEditors ...RequestEditorFn) (Order, error) {
	var result Order
	resp, err := c.Client.CreateOrder(ctx, body, reqEditors...)
	if err != nil {
		return result, err
	}
	defer resp.Body.Close()

	rawBody, err := io.ReadAll(resp.Body)
	if err != nil {
		return result, err
	}

	if resp.StatusCode >= 200 && resp.StatusCode < 300 {
		if err := json.Unmarshal(rawBody, &result); err != nil {
			return result, err
		}
		return result, nil
	}

	// No typed error response defined
	return result, &ClientHttpError[struct{}]{
		StatusCode: resp.StatusCode,
		RawBody:    rawBody,
	}
}

// CreatePet makes a POST request to /pets and returns the parsed response.

// On success, returns the response body. On HTTP error, returns *ClientHttpError[struct{}].
func (c *SimpleClient) CreatePet(ctx context.Context, body createPetJSONRequestBody, reqEditors ...RequestEditorFn) (Pet, error) {
	var result Pet
	resp, err := c.Client.CreatePet(ctx, body, reqEditors...)
	if err != nil {
		return result, err
	}
	defer resp.Body.Close()

	rawBody, err := io.ReadAll(resp.Body)
	if err != nil {
		return result, err
	}

	if resp.StatusCode >= 200 && resp.StatusCode < 300 {
		if err := json.Unmarshal(rawBody, &result); err != nil {
			return result, err
		}
		return result, nil
	}

	// No typed error response defined
	return result, &ClientHttpError[struct{}]{
		StatusCode: resp.StatusCode,
		RawBody:    rawBody,
	}
}

// Query makes a POST request to /query and returns the parsed response.

// On success, returns the response body. On HTTP error, returns *ClientHttpError[struct{}].
func (c *SimpleClient) Query(ctx context.Context, body queryJSONRequestBody, reqEditors ...RequestEditorFn) (QueryResponse, error) {
	var result QueryResponse
	resp, err := c.Client.Query(ctx, body, reqEditors...)
	if err != nil {
		return result, err
	}
	defer resp.Body.Close()

	rawBody, err := io.ReadAll(resp.Body)
	if err != nil {
		return result, err
	}

	if resp.StatusCode >= 200 && resp.StatusCode < 300 {
		if err := json.Unmarshal(rawBody, &result); err != nil {
			return result, err
		}
		return result, nil
	}

	// No typed error response defined
	return result, &ClientHttpError[struct{}]{
		StatusCode: resp.StatusCode,
		RawBody:    rawBody,
	}
}

// GetQux makes a GET request to /qux and returns the parsed response.

// On success, returns the response body. On HTTP error, returns *ClientHttpError[struct{}].
func (c *SimpleClient) GetQux(ctx context.Context, reqEditors ...RequestEditorFn) (map[string]any, error) {
	var result map[string]any
	resp, err := c.Client.GetQux(ctx, reqEditors...)
	if err != nil {
		return result, err
	}
	defer resp.Body.Close()

	rawBody, err := io.ReadAll(resp.Body)
	if err != nil {
		return result, err
	}

	if resp.StatusCode >= 200 && resp.StatusCode < 300 {
		if err := json.Unmarshal(rawBody, &result); err != nil {
			return result, err
		}
		return result, nil
	}

	// No typed error response defined
	return result, &ClientHttpError[struct{}]{
		StatusCode: resp.StatusCode,
		RawBody:    rawBody,
	}
}

// GetStatus makes a GET request to /status and returns the parsed response.

// On success, returns the response body. On HTTP error, returns *ClientHttpError[struct{}].
func (c *SimpleClient) GetStatus(ctx context.Context, reqEditors ...RequestEditorFn) (GetStatusResponse, error) {
	var result GetStatusResponse
	resp, err := c.Client.GetStatus(ctx, reqEditors...)
	if err != nil {
		return result, err
	}
	defer resp.Body.Close()

	rawBody, err := io.ReadAll(resp.Body)
	if err != nil {
		return result, err
	}

	if resp.StatusCode >= 200 && resp.StatusCode < 300 {
		if err := json.Unmarshal(rawBody, &result); err != nil {
			return result, err
		}
		return result, nil
	}

	// No typed error response defined
	return result, &ClientHttpError[struct{}]{
		StatusCode: resp.StatusCode,
		RawBody:    rawBody,
	}
}

// GetZap makes a GET request to /zap and returns the parsed response.

// On success, returns the response body. On HTTP error, returns *ClientHttpError[struct{}].
func (c *SimpleClient) GetZap(ctx context.Context, reqEditors ...RequestEditorFn) (map[string]any, error) {
	var result map[string]any
	resp, err := c.Client.GetZap(ctx, reqEditors...)
	if err != nil {
		return result, err
	}
	defer resp.Body.Close()

	rawBody, err := io.ReadAll(resp.Body)
	if err != nil {
		return result, err
	}

	if resp.StatusCode >= 200 && resp.StatusCode < 300 {
		if err := json.Unmarshal(rawBody, &result); err != nil {
			return result, err
		}
		return result, nil
	}

	// No typed error response defined
	return result, &ClientHttpError[struct{}]{
		StatusCode: resp.StatusCode,
		RawBody:    rawBody,
	}
}
