// Code generated by oapi-codegen; DO NOT EDIT.

package output

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"strings"
	"sync"
)

// #/components/schemas/ProblemDetails
type ProblemDetails struct {
	Type                 *string        `form:"type,omitempty" json:"type,omitempty"`
	Title                *string        `form:"title,omitempty" json:"title,omitempty"`
	Status               *int32         `form:"status,omitempty" json:"status,omitempty"`
	Detail               *string        `form:"detail,omitempty" json:"detail,omitempty"`
	Instance             *string        `form:"instance,omitempty" json:"instance,omitempty"`
	AdditionalProperties map[string]any `json:"-"`
}

// Get returns the specified additional property value and whether it was found.
func (a ProblemDetails) Get(fieldName string) (value any, found bool) {
	if a.AdditionalProperties != nil {
		value, found = a.AdditionalProperties[fieldName]
	}
	return
}

// Set sets an additional property value.
func (a *ProblemDetails) Set(fieldName string, value any) {
	if a.AdditionalProperties == nil {
		a.AdditionalProperties = make(map[string]any)
	}
	a.AdditionalProperties[fieldName] = value
}

func (a *ProblemDetails) UnmarshalJSON(b []byte) error {
	object := make(map[string]json.RawMessage)
	err := json.Unmarshal(b, &object)
	if err != nil {
		return err
	}

	if raw, found := object["type"]; found {
		var val string
		if err := json.Unmarshal(raw, &val); err != nil {
			return fmt.Errorf("error reading 'type': %w", err)
		}
		a.Type = &val
		delete(object, "type")
	}

	if raw, found := object["title"]; found {
		var val string
		if err := json.Unmarshal(raw, &val); err != nil {
			return fmt.Errorf("error reading 'title': %w", err)
		}
		a.Title = &val
		delete(object, "title")
	}

	if raw, found := object["status"]; found {
		var val int32
		if err := json.Unmarshal(raw, &val); err != nil {
			return fmt.Errorf("error reading 'status': %w", err)
		}
		a.Status = &val
		delete(object, "status")
	}

	if raw, found := object["detail"]; found {
		var val string
		if err := json.Unmarshal(raw, &val); err != nil {
			return fmt.Errorf("error reading 'detail': %w", err)
		}
		a.Detail = &val
		delete(object, "detail")
	}

	if raw, found := object["instance"]; found {
		var val string
		if err := json.Unmarshal(raw, &val); err != nil {
			return fmt.Errorf("error reading 'instance': %w", err)
		}
		a.Instance = &val
		delete(object, "instance")
	}

	if len(object) != 0 {
		a.AdditionalProperties = make(map[string]any)
		for fieldName, fieldBuf := range object {
			var fieldVal any
			err := json.Unmarshal(fieldBuf, &fieldVal)
			if err != nil {
				return fmt.Errorf("error unmarshaling field %s: %w", fieldName, err)
			}
			a.AdditionalProperties[fieldName] = fieldVal
		}
	}
	return nil
}

func (a ProblemDetails) MarshalJSON() ([]byte, error) {
	var err error
	object := make(map[string]json.RawMessage)

	if a.Type != nil {
		object["type"], err = json.Marshal(a.Type)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'type': %w", err)
		}
	}

	if a.Title != nil {
		object["title"], err = json.Marshal(a.Title)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'title': %w", err)
		}
	}

	if a.Status != nil {
		object["status"], err = json.Marshal(a.Status)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'status': %w", err)
		}
	}

	if a.Detail != nil {
		object["detail"], err = json.Marshal(a.Detail)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'detail': %w", err)
		}
	}

	if a.Instance != nil {
		object["instance"], err = json.Marshal(a.Instance)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'instance': %w", err)
		}
	}

	for fieldName, field := range a.AdditionalProperties {
		object[fieldName], err = json.Marshal(field)
		if err != nil {
			return nil, fmt.Errorf("error marshaling '%s': %w", fieldName, err)
		}
	}
	return json.Marshal(object)
}

// ApplyDefaults sets default values for fields that are nil.
func (s *ProblemDetails) ApplyDefaults() {
	if s.Type == nil {
		v := "about:blank"
		s.Type = &v
	}
}

// Base64-encoded, gzip-compressed OpenAPI spec.
var openAPISpecJSON = []string{
	"H4sIAAAAAAAC/8RW34/UNhB+z18x0lZaUG+T5e7ah1AhUWgLEtee4BC8eu1JMuCMU3u83PLXV86P3c3d",
	"Uqj6wL3k1hl/M9/nmc9ZrVbZAp65buepbgTO1+cX8Mx5F87So8vhqbXwOr0L8BoD+i2aPFtkC3jaKd0g",
	"nOdreEUaOaB5DNIgdM4LOQZibaNBA5V3bbaARqQLZVHUJE3c5Nq1xWdlFRtXdN5tLLYFUICrlzdgR8Bs",
	"kbkOWXVUwkW+zi8y4sqVGcAWfSDHJTzK1/k6AxASiyXcYJAMwGDQnjrpQ66925LBAEprDAHEgTTEdchg",
	"ypQgAVi1WE7ERlKJYP8yelv2HMqi+PTpU463qu0s9jzev3+fZb04PiSo1SE6nAhXHfWQd6s0UffKIW/J",
	"O26RJcs6JU0PWmwfFYJBhlprHP8BCLFtld+V8AcKkIyrHkPnOGCYwgCW5+v18vDzTgFvYi9PFe1+71Go",
	"dizIcrwbQPBWis4q4vk6gOw6LCGIJ64P+S/v5P/BY1XCclFo13aOkSUU+7qLKwr6cr3+zXvnl8cgl/8Z",
	"5HIEyQ4xCeKORscJpwwziX5VBjz+HYcmOymL6jpLWqX4qa1//BDcTKCgG2zVXLJTLIa4UFwPOM9RFNmw",
	"PKr18su1/ukEKhfZfM9KswliVHgBv6PoZjSF/YCkIQ8ueo35aAn9nEy2MEDkO9XaEUWxgWCTLdkdtM5Q",
	"RcmXhpfXygu46lsM53FvN+Oo99vnDCbmQzu7zQfU08krYyhpp+y1dx16IQwliI/T1HSH5Ww2FtlXxgSg",
	"cr5VUkL09KVpfbKaHcpTBrUJzkZBePv6JUijBMggS5ImDMY8UOuT5gDvGmQw6LFCj6zRnM0QSeDNi7/e",
	"vnqe9iX/hCa2ilcelVEbi2Ccjsmi+g5KJd9LMsN7gHmdn0EMxDW8uLl69TCfcatUtFLCUm1clHJjFX9c",
	"HgWM/lnCcjrWqVPG46XDqWrHQbwiltWWnO0LPGANN8XXD+Ff5YbQOC9nk/emdrsv8TtPIphuQkCuLYWm",
	"b9xJwRli0g+5Jkb0AR7EEJW1O2AnECJJmhjngR2DoG6YtLIQRH3ExlmTtqj9pA9/aad1Wln6jObh44OA",
	"b9BvSSO8ZbVVZGeVBFESw31xiAVr9CdalFguzr9RtZsG4cXNzfWYBrQzCDUyepUIbna9hs5TTQzDdTr2",
	"FQVwWkffN+oMcy78cUu1xNTGtoRH6/Xxsrodln+eLeOttjHQFq+m90ejPGvAn9YX2YFtson/3Uz9ZO37",
	"AvC2s4qHuQodaqpIj18txzqM3GdYJ3TYF/7MMePwhSEOjBK1UQFBqEUDLsp+D3EQxfr7OdWe9D2ypwgC",
	"vBRo1Q6c7x+p83eE1kAVvTToIX01pjr7z9JqZnrTpfFLcXQTPMn+CQAA//++yR1/GQsAAA==",
}

// decodeOpenAPISpec decodes and decompresses the embedded spec.
func decodeOpenAPISpec() ([]byte, error) {
	joined := strings.Join(openAPISpecJSON, "")
	raw, err := base64.StdEncoding.DecodeString(joined)
	if err != nil {
		return nil, fmt.Errorf("decoding base64: %w", err)
	}
	r, err := gzip.NewReader(bytes.NewReader(raw))
	if err != nil {
		return nil, fmt.Errorf("creating gzip reader: %w", err)
	}
	defer r.Close()
	var out bytes.Buffer
	if _, err := out.ReadFrom(r); err != nil {
		return nil, fmt.Errorf("decompressing: %w", err)
	}
	return out.Bytes(), nil
}

// decodeOpenAPISpecCached returns a closure that caches the decoded spec.
func decodeOpenAPISpecCached() func() ([]byte, error) {
	var cached []byte
	var cachedErr error
	var once sync.Once
	return func() ([]byte, error) {
		once.Do(func() {
			cached, cachedErr = decodeOpenAPISpec()
		})
		return cached, cachedErr
	}
}

var openAPISpec = decodeOpenAPISpecCached()

// GetOpenAPISpecJSON returns the raw OpenAPI spec as JSON bytes.
func GetOpenAPISpecJSON() ([]byte, error) {
	return openAPISpec()
}
