// Code generated by oapi-codegen; DO NOT EDIT.

package output

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"strings"
	"sync"

	oapiCodegenTypesPkg "github.com/oapi-codegen/oapi-codegen-exp/experimental/runtime/types"
)

// #/components/schemas/PatchRequest
// A request to patch an existing user object.
type PatchRequest struct {
	SimpleRequiredNullable    SimpleRequiredNullable                                `form:"simple_required_nullable" json:"simple_required_nullable"`
	SimpleOptionalNullable    SimpleOptionalNullable                                `form:"simple_optional_nullable,omitempty" json:"simple_optional_nullable,omitempty"`
	SimpleOptionalNonNullable *SimpleOptionalNonNullable                            `form:"simple_optional_non_nullable,omitempty" json:"simple_optional_non_nullable,omitempty"`
	ComplexRequiredNullable   oapiCodegenTypesPkg.Nullable[ComplexRequiredNullable] `form:"complex_required_nullable" json:"complex_required_nullable"`
	ComplexOptionalNullable   oapiCodegenTypesPkg.Nullable[ComplexOptionalNullable] `form:"complex_optional_nullable,omitempty" json:"complex_optional_nullable,omitempty"`
	AdditionalProperties      map[string]any                                        `json:"-"`
}

// Get returns the specified additional property value and whether it was found.
func (a PatchRequest) Get(fieldName string) (value any, found bool) {
	if a.AdditionalProperties != nil {
		value, found = a.AdditionalProperties[fieldName]
	}
	return
}

// Set sets an additional property value.
func (a *PatchRequest) Set(fieldName string, value any) {
	if a.AdditionalProperties == nil {
		a.AdditionalProperties = make(map[string]any)
	}
	a.AdditionalProperties[fieldName] = value
}

func (a *PatchRequest) UnmarshalJSON(b []byte) error {
	object := make(map[string]json.RawMessage)
	err := json.Unmarshal(b, &object)
	if err != nil {
		return err
	}

	if raw, found := object["simple_required_nullable"]; found {
		if err := json.Unmarshal(raw, &a.SimpleRequiredNullable); err != nil {
			return fmt.Errorf("error reading 'simple_required_nullable': %w", err)
		}
		delete(object, "simple_required_nullable")
	}

	if raw, found := object["simple_optional_nullable"]; found {
		if err := json.Unmarshal(raw, &a.SimpleOptionalNullable); err != nil {
			return fmt.Errorf("error reading 'simple_optional_nullable': %w", err)
		}
		delete(object, "simple_optional_nullable")
	}

	if raw, found := object["simple_optional_non_nullable"]; found {
		var val SimpleOptionalNonNullable
		if err := json.Unmarshal(raw, &val); err != nil {
			return fmt.Errorf("error reading 'simple_optional_non_nullable': %w", err)
		}
		a.SimpleOptionalNonNullable = &val
		delete(object, "simple_optional_non_nullable")
	}

	if raw, found := object["complex_required_nullable"]; found {
		if err := json.Unmarshal(raw, &a.ComplexRequiredNullable); err != nil {
			return fmt.Errorf("error reading 'complex_required_nullable': %w", err)
		}
		delete(object, "complex_required_nullable")
	}

	if raw, found := object["complex_optional_nullable"]; found {
		if err := json.Unmarshal(raw, &a.ComplexOptionalNullable); err != nil {
			return fmt.Errorf("error reading 'complex_optional_nullable': %w", err)
		}
		delete(object, "complex_optional_nullable")
	}

	if len(object) != 0 {
		a.AdditionalProperties = make(map[string]any)
		for fieldName, fieldBuf := range object {
			var fieldVal any
			err := json.Unmarshal(fieldBuf, &fieldVal)
			if err != nil {
				return fmt.Errorf("error unmarshaling field %s: %w", fieldName, err)
			}
			a.AdditionalProperties[fieldName] = fieldVal
		}
	}
	return nil
}

func (a PatchRequest) MarshalJSON() ([]byte, error) {
	var err error
	object := make(map[string]json.RawMessage)

	object["simple_required_nullable"], err = json.Marshal(a.SimpleRequiredNullable)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'simple_required_nullable': %w", err)
	}

	object["simple_optional_nullable"], err = json.Marshal(a.SimpleOptionalNullable)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'simple_optional_nullable': %w", err)
	}

	if a.SimpleOptionalNonNullable != nil {
		object["simple_optional_non_nullable"], err = json.Marshal(a.SimpleOptionalNonNullable)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'simple_optional_non_nullable': %w", err)
		}
	}

	object["complex_required_nullable"], err = json.Marshal(a.ComplexRequiredNullable)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'complex_required_nullable': %w", err)
	}

	object["complex_optional_nullable"], err = json.Marshal(a.ComplexOptionalNullable)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'complex_optional_nullable': %w", err)
	}

	for fieldName, field := range a.AdditionalProperties {
		object[fieldName], err = json.Marshal(field)
		if err != nil {
			return nil, fmt.Errorf("error marshaling '%s': %w", fieldName, err)
		}
	}
	return json.Marshal(object)
}

// ApplyDefaults sets default values for fields that are nil.
func (s *PatchRequest) ApplyDefaults() {
}

// #/components/schemas/simple_required_nullable
// Simple required and nullable
type SimpleRequiredNullable = oapiCodegenTypesPkg.Nullable[int]

// #/components/schemas/simple_optional_nullable
// Simple optional and nullable
type SimpleOptionalNullable = oapiCodegenTypesPkg.Nullable[int]

// #/components/schemas/simple_optional_non_nullable
// Simple optional and non nullable
type SimpleOptionalNonNullable = string

// #/components/schemas/complex_required_nullable
// Complex required and nullable
type ComplexRequiredNullable struct {
	// Optional and non nullable
	Name *string `form:"name,omitempty" json:"name,omitempty"`
}

// ApplyDefaults sets default values for fields that are nil.
func (s *ComplexRequiredNullable) ApplyDefaults() {
}

// #/components/schemas/complex_optional_nullable
// Complex, optional and nullable
type ComplexOptionalNullable struct {
	// Optional and nullable
	AliasName oapiCodegenTypesPkg.Nullable[string] `form:"alias_name,omitempty" json:"alias_name,omitempty"`
	// Optional and non nullable
	Name *string `form:"name,omitempty" json:"name,omitempty"`
}

// ApplyDefaults sets default values for fields that are nil.
func (s *ComplexOptionalNullable) ApplyDefaults() {
}

// Base64-encoded, gzip-compressed OpenAPI spec.
var openAPISpecJSON = []string{
	"H4sIAAAAAAAC/7RUTY/TMBC9+1eMEqReaNNlT+QGnFYIdgXcKzeZJl5S23gmqJX48SjfSZu0ge7eEnvm",
	"vTdvxuPDA1GOcLe+fx/C1zzL5DZD4KNFggQ1OsnKaOFDymwpDIJEcZpvV5HZB0ZatYxMjAnq4Y8qQCko",
	"UIUvfPgifyJQ7hA4lQx6yCMdNlwYg3XGosuOwljU0qoQ7lfr1Z1QemdCAfAbHSmjQ1isi/OFAGDFGYaA",
	"B7m3GQqAGClyynIZ90cAwP9JsJJTKkiDGjsssazkKK0+AYrQ0qSHuJXwVATU9w5/5Uj80cTHJuVE4I8U",
	"K0jYmvjYxhSJymEcArsc2+PIaEbNHRaAtDZTUSkieCaj+3cAFKW4l8MzgDcOdyF4fhCZvTUaNVNQRVJQ",
	"yv9W6fbaMsgaTUgd0OLder3o4w6q8h4/e0J06EVgTVDl9FkalKIbIZjtM0YsRkA/NHYCm9ozqQEPiljp",
	"BHJCV2evxImLrc4lkCqatGmuNs0w9EIK3RkeJmOqEWHV92MKtm+R3woCqWM4Y77cmCkG71SDKf2S2YSG",
	"5voGDWcMFzQYPUuH0ctbtfSYvN6LmejlyzVmkuJcxSu2ZpKiUSHjWFVXT938wk5mhELMGeHqfSrNmKCr",
	"z9qY/p4avNrvJeqEwWLO2N7EO26pmDuqFTexUzqZzWL0CdPVIRxZfdcr/FShXpzdsVWl5R4nN/fjZCVd",
	"wsAUMWu+r+32upa3F5/AWDEyU5I2/1DSlXK649EGvLR7o1R/AwAA///zkywGmQkAAA==",
}

// decodeOpenAPISpec decodes and decompresses the embedded spec.
func decodeOpenAPISpec() ([]byte, error) {
	joined := strings.Join(openAPISpecJSON, "")
	raw, err := base64.StdEncoding.DecodeString(joined)
	if err != nil {
		return nil, fmt.Errorf("decoding base64: %w", err)
	}
	r, err := gzip.NewReader(bytes.NewReader(raw))
	if err != nil {
		return nil, fmt.Errorf("creating gzip reader: %w", err)
	}
	defer r.Close()
	var out bytes.Buffer
	if _, err := out.ReadFrom(r); err != nil {
		return nil, fmt.Errorf("decompressing: %w", err)
	}
	return out.Bytes(), nil
}

// decodeOpenAPISpecCached returns a closure that caches the decoded spec.
func decodeOpenAPISpecCached() func() ([]byte, error) {
	var cached []byte
	var cachedErr error
	var once sync.Once
	return func() ([]byte, error) {
		once.Do(func() {
			cached, cachedErr = decodeOpenAPISpec()
		})
		return cached, cachedErr
	}
}

var openAPISpec = decodeOpenAPISpecCached()

// GetOpenAPISpecJSON returns the raw OpenAPI spec as JSON bytes.
func GetOpenAPISpecJSON() ([]byte, error) {
	return openAPISpec()
}
