// Code generated by oapi-codegen; DO NOT EDIT.

package output

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"encoding/json"
	"errors"
	"fmt"
	"strings"
	"sync"

	oapiCodegenHelpersPkg "github.com/oapi-codegen/oapi-codegen-exp/experimental/runtime/helpers"
)

// #/components/schemas/SchemaObject
type SchemaObject struct {
	Role      string `form:"role" json:"role"`
	FirstName string `form:"firstName" json:"firstName"`
	// This property is required and readOnly, so the go model should have it as a pointer,
	// as it will not be included when it is sent from client to server.
	//
	ReadOnlyRequiredProp  string `form:"readOnlyRequiredProp" json:"readOnlyRequiredProp"`
	WriteOnlyRequiredProp int    `form:"writeOnlyRequiredProp" json:"writeOnlyRequiredProp"`
}

// ApplyDefaults sets default values for fields that are nil.
func (s *SchemaObject) ApplyDefaults() {
}

// #/components/schemas/SchemaObjectNullable
type SchemaObjectNullable struct {
	Role      string `form:"role" json:"role"`
	FirstName string `form:"firstName" json:"firstName"`
	// This property is required and readOnly, so the go model should have it as a pointer,
	// as it will not be included when it is sent from client to server.
	//
	ReadOnlyRequiredProp  string `form:"readOnlyRequiredProp" json:"readOnlyRequiredProp"`
	WriteOnlyRequiredProp int    `form:"writeOnlyRequiredProp" json:"writeOnlyRequiredProp"`
}

// ApplyDefaults sets default values for fields that are nil.
func (s *SchemaObjectNullable) ApplyDefaults() {
}

// #/components/schemas/AdditionalPropertiesObject1
// Has additional properties of type int
type AdditionalPropertiesObject1 struct {
	Name                 string         `form:"name" json:"name"`
	ID                   int            `form:"id" json:"id"`
	Optional             *string        `form:"optional,omitempty" json:"optional,omitempty"`
	AdditionalProperties map[string]int `json:"-"`
}

// Get returns the specified additional property value and whether it was found.
func (a AdditionalPropertiesObject1) Get(fieldName string) (value int, found bool) {
	if a.AdditionalProperties != nil {
		value, found = a.AdditionalProperties[fieldName]
	}
	return
}

// Set sets an additional property value.
func (a *AdditionalPropertiesObject1) Set(fieldName string, value int) {
	if a.AdditionalProperties == nil {
		a.AdditionalProperties = make(map[string]int)
	}
	a.AdditionalProperties[fieldName] = value
}

func (a *AdditionalPropertiesObject1) UnmarshalJSON(b []byte) error {
	object := make(map[string]json.RawMessage)
	err := json.Unmarshal(b, &object)
	if err != nil {
		return err
	}

	if raw, found := object["name"]; found {
		if err := json.Unmarshal(raw, &a.Name); err != nil {
			return fmt.Errorf("error reading 'name': %w", err)
		}
		delete(object, "name")
	}

	if raw, found := object["id"]; found {
		if err := json.Unmarshal(raw, &a.ID); err != nil {
			return fmt.Errorf("error reading 'id': %w", err)
		}
		delete(object, "id")
	}

	if raw, found := object["optional"]; found {
		var val string
		if err := json.Unmarshal(raw, &val); err != nil {
			return fmt.Errorf("error reading 'optional': %w", err)
		}
		a.Optional = &val
		delete(object, "optional")
	}

	if len(object) != 0 {
		a.AdditionalProperties = make(map[string]int)
		for fieldName, fieldBuf := range object {
			var fieldVal int
			err := json.Unmarshal(fieldBuf, &fieldVal)
			if err != nil {
				return fmt.Errorf("error unmarshaling field %s: %w", fieldName, err)
			}
			a.AdditionalProperties[fieldName] = fieldVal
		}
	}
	return nil
}

func (a AdditionalPropertiesObject1) MarshalJSON() ([]byte, error) {
	var err error
	object := make(map[string]json.RawMessage)

	object["name"], err = json.Marshal(a.Name)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'name': %w", err)
	}

	object["id"], err = json.Marshal(a.ID)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'id': %w", err)
	}

	if a.Optional != nil {
		object["optional"], err = json.Marshal(a.Optional)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'optional': %w", err)
		}
	}

	for fieldName, field := range a.AdditionalProperties {
		object[fieldName], err = json.Marshal(field)
		if err != nil {
			return nil, fmt.Errorf("error marshaling '%s': %w", fieldName, err)
		}
	}
	return json.Marshal(object)
}

// ApplyDefaults sets default values for fields that are nil.
func (s *AdditionalPropertiesObject1) ApplyDefaults() {
}

// #/components/schemas/AdditionalPropertiesObject2
// Does not allow additional properties
type AdditionalPropertiesObject2 struct {
	Name                 string         `form:"name" json:"name"`
	ID                   int            `form:"id" json:"id"`
	AdditionalProperties map[string]any `json:"-"`
}

// Get returns the specified additional property value and whether it was found.
func (a AdditionalPropertiesObject2) Get(fieldName string) (value any, found bool) {
	if a.AdditionalProperties != nil {
		value, found = a.AdditionalProperties[fieldName]
	}
	return
}

// Set sets an additional property value.
func (a *AdditionalPropertiesObject2) Set(fieldName string, value any) {
	if a.AdditionalProperties == nil {
		a.AdditionalProperties = make(map[string]any)
	}
	a.AdditionalProperties[fieldName] = value
}

func (a *AdditionalPropertiesObject2) UnmarshalJSON(b []byte) error {
	object := make(map[string]json.RawMessage)
	err := json.Unmarshal(b, &object)
	if err != nil {
		return err
	}

	if raw, found := object["name"]; found {
		if err := json.Unmarshal(raw, &a.Name); err != nil {
			return fmt.Errorf("error reading 'name': %w", err)
		}
		delete(object, "name")
	}

	if raw, found := object["id"]; found {
		if err := json.Unmarshal(raw, &a.ID); err != nil {
			return fmt.Errorf("error reading 'id': %w", err)
		}
		delete(object, "id")
	}

	if len(object) != 0 {
		a.AdditionalProperties = make(map[string]any)
		for fieldName, fieldBuf := range object {
			var fieldVal any
			err := json.Unmarshal(fieldBuf, &fieldVal)
			if err != nil {
				return fmt.Errorf("error unmarshaling field %s: %w", fieldName, err)
			}
			a.AdditionalProperties[fieldName] = fieldVal
		}
	}
	return nil
}

func (a AdditionalPropertiesObject2) MarshalJSON() ([]byte, error) {
	var err error
	object := make(map[string]json.RawMessage)

	object["name"], err = json.Marshal(a.Name)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'name': %w", err)
	}

	object["id"], err = json.Marshal(a.ID)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'id': %w", err)
	}

	for fieldName, field := range a.AdditionalProperties {
		object[fieldName], err = json.Marshal(field)
		if err != nil {
			return nil, fmt.Errorf("error marshaling '%s': %w", fieldName, err)
		}
	}
	return json.Marshal(object)
}

// ApplyDefaults sets default values for fields that are nil.
func (s *AdditionalPropertiesObject2) ApplyDefaults() {
}

// #/components/schemas/AdditionalPropertiesObject3
// Allows any additional property
type AdditionalPropertiesObject3 struct {
	Name                 string         `form:"name" json:"name"`
	AdditionalProperties map[string]any `json:"-"`
}

// Get returns the specified additional property value and whether it was found.
func (a AdditionalPropertiesObject3) Get(fieldName string) (value any, found bool) {
	if a.AdditionalProperties != nil {
		value, found = a.AdditionalProperties[fieldName]
	}
	return
}

// Set sets an additional property value.
func (a *AdditionalPropertiesObject3) Set(fieldName string, value any) {
	if a.AdditionalProperties == nil {
		a.AdditionalProperties = make(map[string]any)
	}
	a.AdditionalProperties[fieldName] = value
}

func (a *AdditionalPropertiesObject3) UnmarshalJSON(b []byte) error {
	object := make(map[string]json.RawMessage)
	err := json.Unmarshal(b, &object)
	if err != nil {
		return err
	}

	if raw, found := object["name"]; found {
		if err := json.Unmarshal(raw, &a.Name); err != nil {
			return fmt.Errorf("error reading 'name': %w", err)
		}
		delete(object, "name")
	}

	if len(object) != 0 {
		a.AdditionalProperties = make(map[string]any)
		for fieldName, fieldBuf := range object {
			var fieldVal any
			err := json.Unmarshal(fieldBuf, &fieldVal)
			if err != nil {
				return fmt.Errorf("error unmarshaling field %s: %w", fieldName, err)
			}
			a.AdditionalProperties[fieldName] = fieldVal
		}
	}
	return nil
}

func (a AdditionalPropertiesObject3) MarshalJSON() ([]byte, error) {
	var err error
	object := make(map[string]json.RawMessage)

	object["name"], err = json.Marshal(a.Name)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'name': %w", err)
	}

	for fieldName, field := range a.AdditionalProperties {
		object[fieldName], err = json.Marshal(field)
		if err != nil {
			return nil, fmt.Errorf("error marshaling '%s': %w", fieldName, err)
		}
	}
	return json.Marshal(object)
}

// ApplyDefaults sets default values for fields that are nil.
func (s *AdditionalPropertiesObject3) ApplyDefaults() {
}

// #/components/schemas/AdditionalPropertiesObject4
// Has anonymous field which has additional properties
type AdditionalPropertiesObject4 struct {
	Name                 string                           `form:"name" json:"name"`
	Inner                AdditionalPropertiesObject4Inner `form:"inner" json:"inner"`
	AdditionalProperties map[string]any                   `json:"-"`
}

// Get returns the specified additional property value and whether it was found.
func (a AdditionalPropertiesObject4) Get(fieldName string) (value any, found bool) {
	if a.AdditionalProperties != nil {
		value, found = a.AdditionalProperties[fieldName]
	}
	return
}

// Set sets an additional property value.
func (a *AdditionalPropertiesObject4) Set(fieldName string, value any) {
	if a.AdditionalProperties == nil {
		a.AdditionalProperties = make(map[string]any)
	}
	a.AdditionalProperties[fieldName] = value
}

func (a *AdditionalPropertiesObject4) UnmarshalJSON(b []byte) error {
	object := make(map[string]json.RawMessage)
	err := json.Unmarshal(b, &object)
	if err != nil {
		return err
	}

	if raw, found := object["name"]; found {
		if err := json.Unmarshal(raw, &a.Name); err != nil {
			return fmt.Errorf("error reading 'name': %w", err)
		}
		delete(object, "name")
	}

	if raw, found := object["inner"]; found {
		if err := json.Unmarshal(raw, &a.Inner); err != nil {
			return fmt.Errorf("error reading 'inner': %w", err)
		}
		delete(object, "inner")
	}

	if len(object) != 0 {
		a.AdditionalProperties = make(map[string]any)
		for fieldName, fieldBuf := range object {
			var fieldVal any
			err := json.Unmarshal(fieldBuf, &fieldVal)
			if err != nil {
				return fmt.Errorf("error unmarshaling field %s: %w", fieldName, err)
			}
			a.AdditionalProperties[fieldName] = fieldVal
		}
	}
	return nil
}

func (a AdditionalPropertiesObject4) MarshalJSON() ([]byte, error) {
	var err error
	object := make(map[string]json.RawMessage)

	object["name"], err = json.Marshal(a.Name)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'name': %w", err)
	}

	object["inner"], err = json.Marshal(a.Inner)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'inner': %w", err)
	}

	for fieldName, field := range a.AdditionalProperties {
		object[fieldName], err = json.Marshal(field)
		if err != nil {
			return nil, fmt.Errorf("error marshaling '%s': %w", fieldName, err)
		}
	}
	return json.Marshal(object)
}

// ApplyDefaults sets default values for fields that are nil.
func (s *AdditionalPropertiesObject4) ApplyDefaults() {
}

// #/components/schemas/AdditionalPropertiesObject4/properties/inner
type AdditionalPropertiesObject4Inner struct {
	Name                 string         `form:"name" json:"name"`
	AdditionalProperties map[string]any `json:"-"`
}

// Get returns the specified additional property value and whether it was found.
func (a AdditionalPropertiesObject4Inner) Get(fieldName string) (value any, found bool) {
	if a.AdditionalProperties != nil {
		value, found = a.AdditionalProperties[fieldName]
	}
	return
}

// Set sets an additional property value.
func (a *AdditionalPropertiesObject4Inner) Set(fieldName string, value any) {
	if a.AdditionalProperties == nil {
		a.AdditionalProperties = make(map[string]any)
	}
	a.AdditionalProperties[fieldName] = value
}

func (a *AdditionalPropertiesObject4Inner) UnmarshalJSON(b []byte) error {
	object := make(map[string]json.RawMessage)
	err := json.Unmarshal(b, &object)
	if err != nil {
		return err
	}

	if raw, found := object["name"]; found {
		if err := json.Unmarshal(raw, &a.Name); err != nil {
			return fmt.Errorf("error reading 'name': %w", err)
		}
		delete(object, "name")
	}

	if len(object) != 0 {
		a.AdditionalProperties = make(map[string]any)
		for fieldName, fieldBuf := range object {
			var fieldVal any
			err := json.Unmarshal(fieldBuf, &fieldVal)
			if err != nil {
				return fmt.Errorf("error unmarshaling field %s: %w", fieldName, err)
			}
			a.AdditionalProperties[fieldName] = fieldVal
		}
	}
	return nil
}

func (a AdditionalPropertiesObject4Inner) MarshalJSON() ([]byte, error) {
	var err error
	object := make(map[string]json.RawMessage)

	object["name"], err = json.Marshal(a.Name)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'name': %w", err)
	}

	for fieldName, field := range a.AdditionalProperties {
		object[fieldName], err = json.Marshal(field)
		if err != nil {
			return nil, fmt.Errorf("error marshaling '%s': %w", fieldName, err)
		}
	}
	return json.Marshal(object)
}

// ApplyDefaults sets default values for fields that are nil.
func (s *AdditionalPropertiesObject4Inner) ApplyDefaults() {
}

// #/components/schemas/AdditionalPropertiesObject5
// Has additional properties with schema for dictionaries
type AdditionalPropertiesObject5 = map[string]any

// #/components/schemas/AdditionalPropertiesObject6
// Array of object with additional properties
type AdditionalPropertiesObject6 = []AdditionalPropertiesObject6Item

// #/components/schemas/AdditionalPropertiesObject6/items
type AdditionalPropertiesObject6Item = map[string]any

// #/components/schemas/AdditionalPropertiesObject7
// Has additional properties with schema for dictionaries
type AdditionalPropertiesObject7 = map[string]any

// #/components/schemas/OneOfObject1

// oneOf with references and no discriminator
type OneOfObject1 struct {
	union json.RawMessage
}

// AsOneOfVariant1 returns the union data inside the OneOfObject1 as a OneOfVariant1.
func (t OneOfObject1) AsOneOfVariant1() (OneOfVariant1, error) {
	var body OneOfVariant1
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromOneOfVariant1 overwrites any union data inside the OneOfObject1 as the provided OneOfVariant1.
func (t *OneOfObject1) FromOneOfVariant1(v OneOfVariant1) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeOneOfVariant1 performs a merge with any union data inside the OneOfObject1, using the provided OneOfVariant1.
func (t *OneOfObject1) MergeOneOfVariant1(v OneOfVariant1) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}
	merged, err := oapiCodegenHelpersPkg.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsOneOfVariant2 returns the union data inside the OneOfObject1 as a OneOfVariant2.
func (t OneOfObject1) AsOneOfVariant2() (OneOfVariant2, error) {
	var body OneOfVariant2
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromOneOfVariant2 overwrites any union data inside the OneOfObject1 as the provided OneOfVariant2.
func (t *OneOfObject1) FromOneOfVariant2(v OneOfVariant2) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeOneOfVariant2 performs a merge with any union data inside the OneOfObject1, using the provided OneOfVariant2.
func (t *OneOfObject1) MergeOneOfVariant2(v OneOfVariant2) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}
	merged, err := oapiCodegenHelpersPkg.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsOneOfVariant3 returns the union data inside the OneOfObject1 as a OneOfVariant3.
func (t OneOfObject1) AsOneOfVariant3() (OneOfVariant3, error) {
	var body OneOfVariant3
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromOneOfVariant3 overwrites any union data inside the OneOfObject1 as the provided OneOfVariant3.
func (t *OneOfObject1) FromOneOfVariant3(v OneOfVariant3) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeOneOfVariant3 performs a merge with any union data inside the OneOfObject1, using the provided OneOfVariant3.
func (t *OneOfObject1) MergeOneOfVariant3(v OneOfVariant3) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}
	merged, err := oapiCodegenHelpersPkg.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t OneOfObject1) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *OneOfObject1) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}

// ApplyDefaults sets default values for fields that are nil.
func (t *OneOfObject1) ApplyDefaults() {
}

// #/components/schemas/OneOfObject2

// oneOf with inline elements
type OneOfObject2 struct {
	union json.RawMessage
}

// AsOneOfObject2OneOf0 returns the union data inside the OneOfObject2 as a OneOfObject2OneOf0.
func (t OneOfObject2) AsOneOfObject2OneOf0() (OneOfObject2OneOf0, error) {
	var body OneOfObject2OneOf0
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromOneOfObject2OneOf0 overwrites any union data inside the OneOfObject2 as the provided OneOfObject2OneOf0.
func (t *OneOfObject2) FromOneOfObject2OneOf0(v OneOfObject2OneOf0) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeOneOfObject2OneOf0 performs a merge with any union data inside the OneOfObject2, using the provided OneOfObject2OneOf0.
func (t *OneOfObject2) MergeOneOfObject2OneOf0(v OneOfObject2OneOf0) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}
	merged, err := oapiCodegenHelpersPkg.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsLBracketFloat321 returns the union data inside the OneOfObject2 as a []float32.
func (t OneOfObject2) AsLBracketFloat321() ([]float32, error) {
	var body []float32
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromLBracketFloat321 overwrites any union data inside the OneOfObject2 as the provided []float32.
func (t *OneOfObject2) FromLBracketFloat321(v []float32) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeLBracketFloat321 performs a merge with any union data inside the OneOfObject2, using the provided []float32.
func (t *OneOfObject2) MergeLBracketFloat321(v []float32) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}
	merged, err := oapiCodegenHelpersPkg.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsBool2 returns the union data inside the OneOfObject2 as a bool.
func (t OneOfObject2) AsBool2() (bool, error) {
	var body bool
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromBool2 overwrites any union data inside the OneOfObject2 as the provided bool.
func (t *OneOfObject2) FromBool2(v bool) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeBool2 performs a merge with any union data inside the OneOfObject2, using the provided bool.
func (t *OneOfObject2) MergeBool2(v bool) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}
	merged, err := oapiCodegenHelpersPkg.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t OneOfObject2) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *OneOfObject2) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}

// ApplyDefaults sets default values for fields that are nil.
func (t *OneOfObject2) ApplyDefaults() {
}

// #/components/schemas/OneOfObject2/oneOf/0
type OneOfObject2OneOf0 struct {
	Name *string `form:"name,omitempty" json:"name,omitempty"`
}

// ApplyDefaults sets default values for fields that are nil.
func (s *OneOfObject2OneOf0) ApplyDefaults() {
}

// #/components/schemas/OneOfObject3
// inline OneOf
type OneOfObject3 struct {
	Union *OneOfObject3Union `form:"union,omitempty" json:"union,omitempty"`
}

// ApplyDefaults sets default values for fields that are nil.
func (s *OneOfObject3) ApplyDefaults() {
}

// #/components/schemas/OneOfObject3/properties/union

type OneOfObject3Union struct {
	union json.RawMessage
}

// AsOneOfVariant1 returns the union data inside the OneOfObject3Union as a OneOfVariant1.
func (t OneOfObject3Union) AsOneOfVariant1() (OneOfVariant1, error) {
	var body OneOfVariant1
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromOneOfVariant1 overwrites any union data inside the OneOfObject3Union as the provided OneOfVariant1.
func (t *OneOfObject3Union) FromOneOfVariant1(v OneOfVariant1) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeOneOfVariant1 performs a merge with any union data inside the OneOfObject3Union, using the provided OneOfVariant1.
func (t *OneOfObject3Union) MergeOneOfVariant1(v OneOfVariant1) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}
	merged, err := oapiCodegenHelpersPkg.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsOneOfVariant2 returns the union data inside the OneOfObject3Union as a OneOfVariant2.
func (t OneOfObject3Union) AsOneOfVariant2() (OneOfVariant2, error) {
	var body OneOfVariant2
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromOneOfVariant2 overwrites any union data inside the OneOfObject3Union as the provided OneOfVariant2.
func (t *OneOfObject3Union) FromOneOfVariant2(v OneOfVariant2) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeOneOfVariant2 performs a merge with any union data inside the OneOfObject3Union, using the provided OneOfVariant2.
func (t *OneOfObject3Union) MergeOneOfVariant2(v OneOfVariant2) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}
	merged, err := oapiCodegenHelpersPkg.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsOneOfVariant3 returns the union data inside the OneOfObject3Union as a OneOfVariant3.
func (t OneOfObject3Union) AsOneOfVariant3() (OneOfVariant3, error) {
	var body OneOfVariant3
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromOneOfVariant3 overwrites any union data inside the OneOfObject3Union as the provided OneOfVariant3.
func (t *OneOfObject3Union) FromOneOfVariant3(v OneOfVariant3) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeOneOfVariant3 performs a merge with any union data inside the OneOfObject3Union, using the provided OneOfVariant3.
func (t *OneOfObject3Union) MergeOneOfVariant3(v OneOfVariant3) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}
	merged, err := oapiCodegenHelpersPkg.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t OneOfObject3Union) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *OneOfObject3Union) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}

// ApplyDefaults sets default values for fields that are nil.
func (t *OneOfObject3Union) ApplyDefaults() {
}

// #/components/schemas/OneOfObject4

// oneOf plus fixed type - custom marshaling/unmarshaling
type OneOfObject4 struct {
	FixedProperty *string `form:"fixedProperty,omitempty" json:"fixedProperty,omitempty"`
	union         json.RawMessage
}

// AsOneOfVariant1 returns the union data inside the OneOfObject4 as a OneOfVariant1.
func (t OneOfObject4) AsOneOfVariant1() (OneOfVariant1, error) {
	var body OneOfVariant1
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromOneOfVariant1 overwrites any union data inside the OneOfObject4 as the provided OneOfVariant1.
func (t *OneOfObject4) FromOneOfVariant1(v OneOfVariant1) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeOneOfVariant1 performs a merge with any union data inside the OneOfObject4, using the provided OneOfVariant1.
func (t *OneOfObject4) MergeOneOfVariant1(v OneOfVariant1) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}
	merged, err := oapiCodegenHelpersPkg.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsOneOfVariant2 returns the union data inside the OneOfObject4 as a OneOfVariant2.
func (t OneOfObject4) AsOneOfVariant2() (OneOfVariant2, error) {
	var body OneOfVariant2
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromOneOfVariant2 overwrites any union data inside the OneOfObject4 as the provided OneOfVariant2.
func (t *OneOfObject4) FromOneOfVariant2(v OneOfVariant2) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeOneOfVariant2 performs a merge with any union data inside the OneOfObject4, using the provided OneOfVariant2.
func (t *OneOfObject4) MergeOneOfVariant2(v OneOfVariant2) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}
	merged, err := oapiCodegenHelpersPkg.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsOneOfVariant3 returns the union data inside the OneOfObject4 as a OneOfVariant3.
func (t OneOfObject4) AsOneOfVariant3() (OneOfVariant3, error) {
	var body OneOfVariant3
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromOneOfVariant3 overwrites any union data inside the OneOfObject4 as the provided OneOfVariant3.
func (t *OneOfObject4) FromOneOfVariant3(v OneOfVariant3) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeOneOfVariant3 performs a merge with any union data inside the OneOfObject4, using the provided OneOfVariant3.
func (t *OneOfObject4) MergeOneOfVariant3(v OneOfVariant3) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}
	merged, err := oapiCodegenHelpersPkg.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t OneOfObject4) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	if err != nil {
		return nil, err
	}
	object := make(map[string]json.RawMessage)
	if t.union != nil {
		err = json.Unmarshal(b, &object)
		if err != nil {
			return nil, err
		}
	}
	if t.FixedProperty != nil {
		object["fixedProperty"], err = json.Marshal(t.FixedProperty)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'fixedProperty': %w", err)
		}
	}
	b, err = json.Marshal(object)
	return b, err
}

func (t *OneOfObject4) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	if err != nil {
		return err
	}
	object := make(map[string]json.RawMessage)
	err = json.Unmarshal(b, &object)
	if err != nil {
		return err
	}
	if raw, found := object["fixedProperty"]; found {
		err = json.Unmarshal(raw, &t.FixedProperty)
		if err != nil {
			return fmt.Errorf("error reading 'fixedProperty': %w", err)
		}
	}
	return err
}

// ApplyDefaults sets default values for fields that are nil.
func (t *OneOfObject4) ApplyDefaults() {
}

// #/components/schemas/OneOfObject5

// oneOf with discriminator but no mapping
type OneOfObject5 struct {
	union json.RawMessage
}

// AsOneOfVariant4 returns the union data inside the OneOfObject5 as a OneOfVariant4.
func (t OneOfObject5) AsOneOfVariant4() (OneOfVariant4, error) {
	var body OneOfVariant4
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromOneOfVariant4 overwrites any union data inside the OneOfObject5 as the provided OneOfVariant4.
func (t *OneOfObject5) FromOneOfVariant4(v OneOfVariant4) error {
	v.Discriminator = "OneOfVariant4"
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeOneOfVariant4 performs a merge with any union data inside the OneOfObject5, using the provided OneOfVariant4.
func (t *OneOfObject5) MergeOneOfVariant4(v OneOfVariant4) error {
	v.Discriminator = "OneOfVariant4"
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}
	merged, err := oapiCodegenHelpersPkg.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsOneOfVariant5 returns the union data inside the OneOfObject5 as a OneOfVariant5.
func (t OneOfObject5) AsOneOfVariant5() (OneOfVariant5, error) {
	var body OneOfVariant5
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromOneOfVariant5 overwrites any union data inside the OneOfObject5 as the provided OneOfVariant5.
func (t *OneOfObject5) FromOneOfVariant5(v OneOfVariant5) error {
	v.Discriminator = "OneOfVariant5"
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeOneOfVariant5 performs a merge with any union data inside the OneOfObject5, using the provided OneOfVariant5.
func (t *OneOfObject5) MergeOneOfVariant5(v OneOfVariant5) error {
	v.Discriminator = "OneOfVariant5"
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}
	merged, err := oapiCodegenHelpersPkg.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// Discriminator extracts the discriminator property value from the union data.
func (t OneOfObject5) Discriminator() (string, error) {
	var discriminator struct {
		Discriminator string `json:"discriminator"`
	}
	err := json.Unmarshal(t.union, &discriminator)
	return discriminator.Discriminator, err
}

// ValueByDiscriminator returns the union member based on the discriminator value.
func (t OneOfObject5) ValueByDiscriminator() (any, error) {
	discriminator, err := t.Discriminator()
	if err != nil {
		return nil, err
	}
	switch discriminator {
	case "OneOfVariant4":
		return t.AsOneOfVariant4()
	case "OneOfVariant5":
		return t.AsOneOfVariant5()
	default:
		return nil, errors.New("unknown discriminator value: " + discriminator)
	}
}

func (t OneOfObject5) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *OneOfObject5) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}

// ApplyDefaults sets default values for fields that are nil.
func (t *OneOfObject5) ApplyDefaults() {
}

// #/components/schemas/OneOfObject6

// oneOf with discriminator and mapping
type OneOfObject6 struct {
	union json.RawMessage
}

// AsOneOfVariant4 returns the union data inside the OneOfObject6 as a OneOfVariant4.
func (t OneOfObject6) AsOneOfVariant4() (OneOfVariant4, error) {
	var body OneOfVariant4
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromOneOfVariant4 overwrites any union data inside the OneOfObject6 as the provided OneOfVariant4.
func (t *OneOfObject6) FromOneOfVariant4(v OneOfVariant4) error {
	v.Discriminator = "v4"
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeOneOfVariant4 performs a merge with any union data inside the OneOfObject6, using the provided OneOfVariant4.
func (t *OneOfObject6) MergeOneOfVariant4(v OneOfVariant4) error {
	v.Discriminator = "v4"
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}
	merged, err := oapiCodegenHelpersPkg.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsOneOfVariant5 returns the union data inside the OneOfObject6 as a OneOfVariant5.
func (t OneOfObject6) AsOneOfVariant5() (OneOfVariant5, error) {
	var body OneOfVariant5
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromOneOfVariant5 overwrites any union data inside the OneOfObject6 as the provided OneOfVariant5.
func (t *OneOfObject6) FromOneOfVariant5(v OneOfVariant5) error {
	v.Discriminator = "v5"
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeOneOfVariant5 performs a merge with any union data inside the OneOfObject6, using the provided OneOfVariant5.
func (t *OneOfObject6) MergeOneOfVariant5(v OneOfVariant5) error {
	v.Discriminator = "v5"
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}
	merged, err := oapiCodegenHelpersPkg.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// Discriminator extracts the discriminator property value from the union data.
func (t OneOfObject6) Discriminator() (string, error) {
	var discriminator struct {
		Discriminator string `json:"discriminator"`
	}
	err := json.Unmarshal(t.union, &discriminator)
	return discriminator.Discriminator, err
}

// ValueByDiscriminator returns the union member based on the discriminator value.
func (t OneOfObject6) ValueByDiscriminator() (any, error) {
	discriminator, err := t.Discriminator()
	if err != nil {
		return nil, err
	}
	switch discriminator {
	case "v4":
		return t.AsOneOfVariant4()
	case "v5":
		return t.AsOneOfVariant5()
	default:
		return nil, errors.New("unknown discriminator value: " + discriminator)
	}
}

func (t OneOfObject6) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *OneOfObject6) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}

// ApplyDefaults sets default values for fields that are nil.
func (t *OneOfObject6) ApplyDefaults() {
}

// #/components/schemas/OneOfObject61

// oneOf with discriminator and partial mapping
type OneOfObject61 struct {
	union json.RawMessage
}

// AsOneOfVariant4 returns the union data inside the OneOfObject61 as a OneOfVariant4.
func (t OneOfObject61) AsOneOfVariant4() (OneOfVariant4, error) {
	var body OneOfVariant4
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromOneOfVariant4 overwrites any union data inside the OneOfObject61 as the provided OneOfVariant4.
func (t *OneOfObject61) FromOneOfVariant4(v OneOfVariant4) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeOneOfVariant4 performs a merge with any union data inside the OneOfObject61, using the provided OneOfVariant4.
func (t *OneOfObject61) MergeOneOfVariant4(v OneOfVariant4) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}
	merged, err := oapiCodegenHelpersPkg.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsOneOfVariant5 returns the union data inside the OneOfObject61 as a OneOfVariant5.
func (t OneOfObject61) AsOneOfVariant5() (OneOfVariant5, error) {
	var body OneOfVariant5
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromOneOfVariant5 overwrites any union data inside the OneOfObject61 as the provided OneOfVariant5.
func (t *OneOfObject61) FromOneOfVariant5(v OneOfVariant5) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeOneOfVariant5 performs a merge with any union data inside the OneOfObject61, using the provided OneOfVariant5.
func (t *OneOfObject61) MergeOneOfVariant5(v OneOfVariant5) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}
	merged, err := oapiCodegenHelpersPkg.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// Discriminator extracts the discriminator property value from the union data.
func (t OneOfObject61) Discriminator() (string, error) {
	var discriminator struct {
		Discriminator string `json:"discriminator"`
	}
	err := json.Unmarshal(t.union, &discriminator)
	return discriminator.Discriminator, err
}

// ValueByDiscriminator returns the union member based on the discriminator value.
func (t OneOfObject61) ValueByDiscriminator() (any, error) {
	discriminator, err := t.Discriminator()
	if err != nil {
		return nil, err
	}
	switch discriminator {
	case "v4":
		return t.AsOneOfVariant4()
	default:
		return nil, errors.New("unknown discriminator value: " + discriminator)
	}
}

func (t OneOfObject61) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *OneOfObject61) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}

// ApplyDefaults sets default values for fields that are nil.
func (t *OneOfObject61) ApplyDefaults() {
}

// #/components/schemas/OneOfObject62

// oneOf with snake_case discriminator and partial snake_case mapping
type OneOfObject62 struct {
	union json.RawMessage
}

// AsOneOfVariant4 returns the union data inside the OneOfObject62 as a OneOfVariant4.
func (t OneOfObject62) AsOneOfVariant4() (OneOfVariant4, error) {
	var body OneOfVariant4
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromOneOfVariant4 overwrites any union data inside the OneOfObject62 as the provided OneOfVariant4.
func (t *OneOfObject62) FromOneOfVariant4(v OneOfVariant4) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeOneOfVariant4 performs a merge with any union data inside the OneOfObject62, using the provided OneOfVariant4.
func (t *OneOfObject62) MergeOneOfVariant4(v OneOfVariant4) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}
	merged, err := oapiCodegenHelpersPkg.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsOneOfVariant51 returns the union data inside the OneOfObject62 as a OneOfVariant51.
func (t OneOfObject62) AsOneOfVariant51() (OneOfVariant51, error) {
	var body OneOfVariant51
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromOneOfVariant51 overwrites any union data inside the OneOfObject62 as the provided OneOfVariant51.
func (t *OneOfObject62) FromOneOfVariant51(v OneOfVariant51) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeOneOfVariant51 performs a merge with any union data inside the OneOfObject62, using the provided OneOfVariant51.
func (t *OneOfObject62) MergeOneOfVariant51(v OneOfVariant51) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}
	merged, err := oapiCodegenHelpersPkg.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// Discriminator extracts the discriminator property value from the union data.
func (t OneOfObject62) Discriminator() (string, error) {
	var discriminator struct {
		Discriminator string `json:"discriminator"`
	}
	err := json.Unmarshal(t.union, &discriminator)
	return discriminator.Discriminator, err
}

// ValueByDiscriminator returns the union member based on the discriminator value.
func (t OneOfObject62) ValueByDiscriminator() (any, error) {
	discriminator, err := t.Discriminator()
	if err != nil {
		return nil, err
	}
	switch discriminator {
	case "variant_four":
		return t.AsOneOfVariant4()
	default:
		return nil, errors.New("unknown discriminator value: " + discriminator)
	}
}

func (t OneOfObject62) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *OneOfObject62) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}

// ApplyDefaults sets default values for fields that are nil.
func (t *OneOfObject62) ApplyDefaults() {
}

// #/components/schemas/OneOfObject7
// array of oneOf
type OneOfObject7 = []OneOfObject7Item

// #/components/schemas/OneOfObject7/items

type OneOfObject7Item struct {
	union json.RawMessage
}

// AsOneOfVariant1 returns the union data inside the OneOfObject7Item as a OneOfVariant1.
func (t OneOfObject7Item) AsOneOfVariant1() (OneOfVariant1, error) {
	var body OneOfVariant1
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromOneOfVariant1 overwrites any union data inside the OneOfObject7Item as the provided OneOfVariant1.
func (t *OneOfObject7Item) FromOneOfVariant1(v OneOfVariant1) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeOneOfVariant1 performs a merge with any union data inside the OneOfObject7Item, using the provided OneOfVariant1.
func (t *OneOfObject7Item) MergeOneOfVariant1(v OneOfVariant1) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}
	merged, err := oapiCodegenHelpersPkg.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsOneOfVariant2 returns the union data inside the OneOfObject7Item as a OneOfVariant2.
func (t OneOfObject7Item) AsOneOfVariant2() (OneOfVariant2, error) {
	var body OneOfVariant2
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromOneOfVariant2 overwrites any union data inside the OneOfObject7Item as the provided OneOfVariant2.
func (t *OneOfObject7Item) FromOneOfVariant2(v OneOfVariant2) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeOneOfVariant2 performs a merge with any union data inside the OneOfObject7Item, using the provided OneOfVariant2.
func (t *OneOfObject7Item) MergeOneOfVariant2(v OneOfVariant2) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}
	merged, err := oapiCodegenHelpersPkg.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t OneOfObject7Item) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *OneOfObject7Item) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}

// ApplyDefaults sets default values for fields that are nil.
func (t *OneOfObject7Item) ApplyDefaults() {
}

// #/components/schemas/OneOfObject8

// oneOf with fixed properties
type OneOfObject8 struct {
	Fixed *string `form:"fixed,omitempty" json:"fixed,omitempty"`
	union json.RawMessage
}

// AsOneOfVariant1 returns the union data inside the OneOfObject8 as a OneOfVariant1.
func (t OneOfObject8) AsOneOfVariant1() (OneOfVariant1, error) {
	var body OneOfVariant1
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromOneOfVariant1 overwrites any union data inside the OneOfObject8 as the provided OneOfVariant1.
func (t *OneOfObject8) FromOneOfVariant1(v OneOfVariant1) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeOneOfVariant1 performs a merge with any union data inside the OneOfObject8, using the provided OneOfVariant1.
func (t *OneOfObject8) MergeOneOfVariant1(v OneOfVariant1) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}
	merged, err := oapiCodegenHelpersPkg.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsOneOfVariant2 returns the union data inside the OneOfObject8 as a OneOfVariant2.
func (t OneOfObject8) AsOneOfVariant2() (OneOfVariant2, error) {
	var body OneOfVariant2
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromOneOfVariant2 overwrites any union data inside the OneOfObject8 as the provided OneOfVariant2.
func (t *OneOfObject8) FromOneOfVariant2(v OneOfVariant2) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeOneOfVariant2 performs a merge with any union data inside the OneOfObject8, using the provided OneOfVariant2.
func (t *OneOfObject8) MergeOneOfVariant2(v OneOfVariant2) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}
	merged, err := oapiCodegenHelpersPkg.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t OneOfObject8) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	if err != nil {
		return nil, err
	}
	object := make(map[string]json.RawMessage)
	if t.union != nil {
		err = json.Unmarshal(b, &object)
		if err != nil {
			return nil, err
		}
	}
	if t.Fixed != nil {
		object["fixed"], err = json.Marshal(t.Fixed)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'fixed': %w", err)
		}
	}
	b, err = json.Marshal(object)
	return b, err
}

func (t *OneOfObject8) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	if err != nil {
		return err
	}
	object := make(map[string]json.RawMessage)
	err = json.Unmarshal(b, &object)
	if err != nil {
		return err
	}
	if raw, found := object["fixed"]; found {
		err = json.Unmarshal(raw, &t.Fixed)
		if err != nil {
			return fmt.Errorf("error reading 'fixed': %w", err)
		}
	}
	return err
}

// ApplyDefaults sets default values for fields that are nil.
func (t *OneOfObject8) ApplyDefaults() {
}

// #/components/schemas/OneOfObject9

// oneOf with fixed discriminator
type OneOfObject9 struct {
	Type  string `form:"type" json:"type"`
	union json.RawMessage
}

// AsOneOfVariant1 returns the union data inside the OneOfObject9 as a OneOfVariant1.
func (t OneOfObject9) AsOneOfVariant1() (OneOfVariant1, error) {
	var body OneOfVariant1
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromOneOfVariant1 overwrites any union data inside the OneOfObject9 as the provided OneOfVariant1.
func (t *OneOfObject9) FromOneOfVariant1(v OneOfVariant1) error {
	t.Type = "v1"
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeOneOfVariant1 performs a merge with any union data inside the OneOfObject9, using the provided OneOfVariant1.
func (t *OneOfObject9) MergeOneOfVariant1(v OneOfVariant1) error {
	t.Type = "v1"
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}
	merged, err := oapiCodegenHelpersPkg.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsOneOfVariant6 returns the union data inside the OneOfObject9 as a OneOfVariant6.
func (t OneOfObject9) AsOneOfVariant6() (OneOfVariant6, error) {
	var body OneOfVariant6
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromOneOfVariant6 overwrites any union data inside the OneOfObject9 as the provided OneOfVariant6.
func (t *OneOfObject9) FromOneOfVariant6(v OneOfVariant6) error {
	t.Type = "v6"
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeOneOfVariant6 performs a merge with any union data inside the OneOfObject9, using the provided OneOfVariant6.
func (t *OneOfObject9) MergeOneOfVariant6(v OneOfVariant6) error {
	t.Type = "v6"
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}
	merged, err := oapiCodegenHelpersPkg.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// Discriminator extracts the discriminator property value from the union data.
func (t OneOfObject9) Discriminator() (string, error) {
	var discriminator struct {
		Discriminator string `json:"type"`
	}
	err := json.Unmarshal(t.union, &discriminator)
	return discriminator.Discriminator, err
}

// ValueByDiscriminator returns the union member based on the discriminator value.
func (t OneOfObject9) ValueByDiscriminator() (any, error) {
	discriminator, err := t.Discriminator()
	if err != nil {
		return nil, err
	}
	switch discriminator {
	case "v1":
		return t.AsOneOfVariant1()
	case "v6":
		return t.AsOneOfVariant6()
	default:
		return nil, errors.New("unknown discriminator value: " + discriminator)
	}
}

func (t OneOfObject9) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	if err != nil {
		return nil, err
	}
	object := make(map[string]json.RawMessage)
	if t.union != nil {
		err = json.Unmarshal(b, &object)
		if err != nil {
			return nil, err
		}
	}
	object["type"], err = json.Marshal(t.Type)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'type': %w", err)
	}
	b, err = json.Marshal(object)
	return b, err
}

func (t *OneOfObject9) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	if err != nil {
		return err
	}
	object := make(map[string]json.RawMessage)
	err = json.Unmarshal(b, &object)
	if err != nil {
		return err
	}
	if raw, found := object["type"]; found {
		err = json.Unmarshal(raw, &t.Type)
		if err != nil {
			return fmt.Errorf("error reading 'type': %w", err)
		}
	}
	return err
}

// ApplyDefaults sets default values for fields that are nil.
func (t *OneOfObject9) ApplyDefaults() {
}

// #/components/schemas/OneOfObject10

// fixed properties, variable required - will compile, but not much sense
type OneOfObject10 struct {
	One   *string `form:"one,omitempty" json:"one,omitempty"`
	Two   *int    `form:"two,omitempty" json:"two,omitempty"`
	Three *bool   `form:"three,omitempty" json:"three,omitempty"`
	union json.RawMessage
}

// AsAny0 returns the union data inside the OneOfObject10 as a any.
func (t OneOfObject10) AsAny0() (any, error) {
	var body any
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromAny0 overwrites any union data inside the OneOfObject10 as the provided any.
func (t *OneOfObject10) FromAny0(v any) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeAny0 performs a merge with any union data inside the OneOfObject10, using the provided any.
func (t *OneOfObject10) MergeAny0(v any) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}
	merged, err := oapiCodegenHelpersPkg.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsAny1 returns the union data inside the OneOfObject10 as a any.
func (t OneOfObject10) AsAny1() (any, error) {
	var body any
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromAny1 overwrites any union data inside the OneOfObject10 as the provided any.
func (t *OneOfObject10) FromAny1(v any) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeAny1 performs a merge with any union data inside the OneOfObject10, using the provided any.
func (t *OneOfObject10) MergeAny1(v any) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}
	merged, err := oapiCodegenHelpersPkg.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t OneOfObject10) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	if err != nil {
		return nil, err
	}
	object := make(map[string]json.RawMessage)
	if t.union != nil {
		err = json.Unmarshal(b, &object)
		if err != nil {
			return nil, err
		}
	}
	if t.One != nil {
		object["one"], err = json.Marshal(t.One)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'one': %w", err)
		}
	}
	if t.Two != nil {
		object["two"], err = json.Marshal(t.Two)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'two': %w", err)
		}
	}
	if t.Three != nil {
		object["three"], err = json.Marshal(t.Three)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'three': %w", err)
		}
	}
	b, err = json.Marshal(object)
	return b, err
}

func (t *OneOfObject10) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	if err != nil {
		return err
	}
	object := make(map[string]json.RawMessage)
	err = json.Unmarshal(b, &object)
	if err != nil {
		return err
	}
	if raw, found := object["one"]; found {
		err = json.Unmarshal(raw, &t.One)
		if err != nil {
			return fmt.Errorf("error reading 'one': %w", err)
		}
	}
	if raw, found := object["two"]; found {
		err = json.Unmarshal(raw, &t.Two)
		if err != nil {
			return fmt.Errorf("error reading 'two': %w", err)
		}
	}
	if raw, found := object["three"]; found {
		err = json.Unmarshal(raw, &t.Three)
		if err != nil {
			return fmt.Errorf("error reading 'three': %w", err)
		}
	}
	return err
}

// ApplyDefaults sets default values for fields that are nil.
func (t *OneOfObject10) ApplyDefaults() {
}

// #/components/schemas/OneOfObject11
// additional properties of oneOf
type OneOfObject11 = map[string]any

// #/components/schemas/OneOfObject11/additionalProperties

type OneOfObject11Value struct {
	union json.RawMessage
}

// AsBool0 returns the union data inside the OneOfObject11Value as a bool.
func (t OneOfObject11Value) AsBool0() (bool, error) {
	var body bool
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromBool0 overwrites any union data inside the OneOfObject11Value as the provided bool.
func (t *OneOfObject11Value) FromBool0(v bool) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeBool0 performs a merge with any union data inside the OneOfObject11Value, using the provided bool.
func (t *OneOfObject11Value) MergeBool0(v bool) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}
	merged, err := oapiCodegenHelpersPkg.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsFloat321 returns the union data inside the OneOfObject11Value as a float32.
func (t OneOfObject11Value) AsFloat321() (float32, error) {
	var body float32
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromFloat321 overwrites any union data inside the OneOfObject11Value as the provided float32.
func (t *OneOfObject11Value) FromFloat321(v float32) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeFloat321 performs a merge with any union data inside the OneOfObject11Value, using the provided float32.
func (t *OneOfObject11Value) MergeFloat321(v float32) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}
	merged, err := oapiCodegenHelpersPkg.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsString2 returns the union data inside the OneOfObject11Value as a string.
func (t OneOfObject11Value) AsString2() (string, error) {
	var body string
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromString2 overwrites any union data inside the OneOfObject11Value as the provided string.
func (t *OneOfObject11Value) FromString2(v string) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeString2 performs a merge with any union data inside the OneOfObject11Value, using the provided string.
func (t *OneOfObject11Value) MergeString2(v string) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}
	merged, err := oapiCodegenHelpersPkg.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t OneOfObject11Value) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *OneOfObject11Value) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}

// ApplyDefaults sets default values for fields that are nil.
func (t *OneOfObject11Value) ApplyDefaults() {
}

// #/components/schemas/OneOfObject12
// allOf of oneOfs
type OneOfObject12 struct {
	OneOfObject12AllOf0 *OneOfObject12AllOf0 `json:"-"`
	OneOfObject12AllOf1 *OneOfObject12AllOf1 `json:"-"`
}

func (s OneOfObject12) MarshalJSON() ([]byte, error) {
	result := make(map[string]any)

	if s.OneOfObject12AllOf0 != nil {
		unionData, err := json.Marshal(s.OneOfObject12AllOf0)
		if err != nil {
			return nil, err
		}
		var unionMap map[string]any
		if err := json.Unmarshal(unionData, &unionMap); err == nil {
			for k, v := range unionMap {
				result[k] = v
			}
		}
	}

	if s.OneOfObject12AllOf1 != nil {
		unionData, err := json.Marshal(s.OneOfObject12AllOf1)
		if err != nil {
			return nil, err
		}
		var unionMap map[string]any
		if err := json.Unmarshal(unionData, &unionMap); err == nil {
			for k, v := range unionMap {
				result[k] = v
			}
		}
	}

	return json.Marshal(result)
}

func (s *OneOfObject12) UnmarshalJSON(data []byte) error {
	var raw map[string]json.RawMessage
	if err := json.Unmarshal(data, &raw); err != nil {
		return err
	}

	var OneOfObject12AllOf0Val OneOfObject12AllOf0
	if err := json.Unmarshal(data, &OneOfObject12AllOf0Val); err != nil {
		return err
	}
	s.OneOfObject12AllOf0 = &OneOfObject12AllOf0Val

	var OneOfObject12AllOf1Val OneOfObject12AllOf1
	if err := json.Unmarshal(data, &OneOfObject12AllOf1Val); err != nil {
		return err
	}
	s.OneOfObject12AllOf1 = &OneOfObject12AllOf1Val

	return nil
}

// ApplyDefaults sets default values for fields that are nil.
func (s *OneOfObject12) ApplyDefaults() {
}

// #/components/schemas/OneOfObject12/allOf/0

type OneOfObject12AllOf0 struct {
	union json.RawMessage
}

// AsString0 returns the union data inside the OneOfObject12AllOf0 as a string.
func (t OneOfObject12AllOf0) AsString0() (string, error) {
	var body string
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromString0 overwrites any union data inside the OneOfObject12AllOf0 as the provided string.
func (t *OneOfObject12AllOf0) FromString0(v string) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeString0 performs a merge with any union data inside the OneOfObject12AllOf0, using the provided string.
func (t *OneOfObject12AllOf0) MergeString0(v string) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}
	merged, err := oapiCodegenHelpersPkg.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsFloat321 returns the union data inside the OneOfObject12AllOf0 as a float32.
func (t OneOfObject12AllOf0) AsFloat321() (float32, error) {
	var body float32
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromFloat321 overwrites any union data inside the OneOfObject12AllOf0 as the provided float32.
func (t *OneOfObject12AllOf0) FromFloat321(v float32) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeFloat321 performs a merge with any union data inside the OneOfObject12AllOf0, using the provided float32.
func (t *OneOfObject12AllOf0) MergeFloat321(v float32) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}
	merged, err := oapiCodegenHelpersPkg.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t OneOfObject12AllOf0) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *OneOfObject12AllOf0) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}

// ApplyDefaults sets default values for fields that are nil.
func (t *OneOfObject12AllOf0) ApplyDefaults() {
}

// #/components/schemas/OneOfObject12/allOf/1

type OneOfObject12AllOf1 struct {
	union json.RawMessage
}

// AsOneOfVariant3 returns the union data inside the OneOfObject12AllOf1 as a OneOfVariant3.
func (t OneOfObject12AllOf1) AsOneOfVariant3() (OneOfVariant3, error) {
	var body OneOfVariant3
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromOneOfVariant3 overwrites any union data inside the OneOfObject12AllOf1 as the provided OneOfVariant3.
func (t *OneOfObject12AllOf1) FromOneOfVariant3(v OneOfVariant3) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeOneOfVariant3 performs a merge with any union data inside the OneOfObject12AllOf1, using the provided OneOfVariant3.
func (t *OneOfObject12AllOf1) MergeOneOfVariant3(v OneOfVariant3) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}
	merged, err := oapiCodegenHelpersPkg.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsOneOfVariant4 returns the union data inside the OneOfObject12AllOf1 as a OneOfVariant4.
func (t OneOfObject12AllOf1) AsOneOfVariant4() (OneOfVariant4, error) {
	var body OneOfVariant4
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromOneOfVariant4 overwrites any union data inside the OneOfObject12AllOf1 as the provided OneOfVariant4.
func (t *OneOfObject12AllOf1) FromOneOfVariant4(v OneOfVariant4) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeOneOfVariant4 performs a merge with any union data inside the OneOfObject12AllOf1, using the provided OneOfVariant4.
func (t *OneOfObject12AllOf1) MergeOneOfVariant4(v OneOfVariant4) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}
	merged, err := oapiCodegenHelpersPkg.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t OneOfObject12AllOf1) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *OneOfObject12AllOf1) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}

// ApplyDefaults sets default values for fields that are nil.
func (t *OneOfObject12AllOf1) ApplyDefaults() {
}

// #/components/schemas/OneOfObject13

// oneOf with fixed discriminator and other fields allowed
type OneOfObject13 struct {
	Type  string `form:"type" json:"type"`
	union json.RawMessage
}

// AsOneOfVariant1 returns the union data inside the OneOfObject13 as a OneOfVariant1.
func (t OneOfObject13) AsOneOfVariant1() (OneOfVariant1, error) {
	var body OneOfVariant1
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromOneOfVariant1 overwrites any union data inside the OneOfObject13 as the provided OneOfVariant1.
func (t *OneOfObject13) FromOneOfVariant1(v OneOfVariant1) error {
	t.Type = "v1"
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeOneOfVariant1 performs a merge with any union data inside the OneOfObject13, using the provided OneOfVariant1.
func (t *OneOfObject13) MergeOneOfVariant1(v OneOfVariant1) error {
	t.Type = "v1"
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}
	merged, err := oapiCodegenHelpersPkg.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsOneOfVariant6 returns the union data inside the OneOfObject13 as a OneOfVariant6.
func (t OneOfObject13) AsOneOfVariant6() (OneOfVariant6, error) {
	var body OneOfVariant6
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromOneOfVariant6 overwrites any union data inside the OneOfObject13 as the provided OneOfVariant6.
func (t *OneOfObject13) FromOneOfVariant6(v OneOfVariant6) error {
	t.Type = "v6"
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeOneOfVariant6 performs a merge with any union data inside the OneOfObject13, using the provided OneOfVariant6.
func (t *OneOfObject13) MergeOneOfVariant6(v OneOfVariant6) error {
	t.Type = "v6"
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}
	merged, err := oapiCodegenHelpersPkg.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// Discriminator extracts the discriminator property value from the union data.
func (t OneOfObject13) Discriminator() (string, error) {
	var discriminator struct {
		Discriminator string `json:"type"`
	}
	err := json.Unmarshal(t.union, &discriminator)
	return discriminator.Discriminator, err
}

// ValueByDiscriminator returns the union member based on the discriminator value.
func (t OneOfObject13) ValueByDiscriminator() (any, error) {
	discriminator, err := t.Discriminator()
	if err != nil {
		return nil, err
	}
	switch discriminator {
	case "v1":
		return t.AsOneOfVariant1()
	case "v6":
		return t.AsOneOfVariant6()
	default:
		return nil, errors.New("unknown discriminator value: " + discriminator)
	}
}

func (t OneOfObject13) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	if err != nil {
		return nil, err
	}
	object := make(map[string]json.RawMessage)
	if t.union != nil {
		err = json.Unmarshal(b, &object)
		if err != nil {
			return nil, err
		}
	}
	object["type"], err = json.Marshal(t.Type)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'type': %w", err)
	}
	b, err = json.Marshal(object)
	return b, err
}

func (t *OneOfObject13) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	if err != nil {
		return err
	}
	object := make(map[string]json.RawMessage)
	err = json.Unmarshal(b, &object)
	if err != nil {
		return err
	}
	if raw, found := object["type"]; found {
		err = json.Unmarshal(raw, &t.Type)
		if err != nil {
			return fmt.Errorf("error reading 'type': %w", err)
		}
	}
	return err
}

// ApplyDefaults sets default values for fields that are nil.
func (t *OneOfObject13) ApplyDefaults() {
}

// #/components/schemas/AnyOfObject1

// simple anyOf case
type AnyOfObject1 struct {
	union json.RawMessage
}

// AsOneOfVariant4 returns the union data inside the AnyOfObject1 as a OneOfVariant4.
func (t AnyOfObject1) AsOneOfVariant4() (OneOfVariant4, error) {
	var body OneOfVariant4
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromOneOfVariant4 overwrites any union data inside the AnyOfObject1 as the provided OneOfVariant4.
func (t *AnyOfObject1) FromOneOfVariant4(v OneOfVariant4) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeOneOfVariant4 performs a merge with any union data inside the AnyOfObject1, using the provided OneOfVariant4.
func (t *AnyOfObject1) MergeOneOfVariant4(v OneOfVariant4) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}
	merged, err := oapiCodegenHelpersPkg.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsOneOfVariant5 returns the union data inside the AnyOfObject1 as a OneOfVariant5.
func (t AnyOfObject1) AsOneOfVariant5() (OneOfVariant5, error) {
	var body OneOfVariant5
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromOneOfVariant5 overwrites any union data inside the AnyOfObject1 as the provided OneOfVariant5.
func (t *AnyOfObject1) FromOneOfVariant5(v OneOfVariant5) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeOneOfVariant5 performs a merge with any union data inside the AnyOfObject1, using the provided OneOfVariant5.
func (t *AnyOfObject1) MergeOneOfVariant5(v OneOfVariant5) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}
	merged, err := oapiCodegenHelpersPkg.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t AnyOfObject1) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *AnyOfObject1) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}

// ApplyDefaults sets default values for fields that are nil.
func (t *AnyOfObject1) ApplyDefaults() {
}

// #/components/schemas/OneOfVariant1
type OneOfVariant1 struct {
	Name string `form:"name" json:"name"`
}

// ApplyDefaults sets default values for fields that are nil.
func (s *OneOfVariant1) ApplyDefaults() {
}

// #/components/schemas/OneOfVariant2
type OneOfVariant2 = []int

// #/components/schemas/OneOfVariant3
type OneOfVariant3 = bool

// #/components/schemas/OneOfVariant4
type OneOfVariant4 struct {
	Discriminator string `form:"discriminator" json:"discriminator"`
	Name          string `form:"name" json:"name"`
}

// ApplyDefaults sets default values for fields that are nil.
func (s *OneOfVariant4) ApplyDefaults() {
}

// #/components/schemas/OneOfVariant5
type OneOfVariant5 struct {
	Discriminator string `form:"discriminator" json:"discriminator"`
	ID            int    `form:"id" json:"id"`
}

// ApplyDefaults sets default values for fields that are nil.
func (s *OneOfVariant5) ApplyDefaults() {
}

// #/components/schemas/one_of_variant51
type OneOfVariant51 struct {
	Discriminator string `form:"discriminator" json:"discriminator"`
	ID            int    `form:"id" json:"id"`
}

// ApplyDefaults sets default values for fields that are nil.
func (s *OneOfVariant51) ApplyDefaults() {
}

// #/components/schemas/OneOfVariant6
type OneOfVariant6 struct {
	Values OneOfVariant2 `form:"values" json:"values"`
}

// ApplyDefaults sets default values for fields that are nil.
func (s *OneOfVariant6) ApplyDefaults() {
}

// #/components/schemas/ObjectWithJsonField
type ObjectWithJSONField struct {
	Name   string           `form:"name" json:"name"`
	Value1 json.RawMessage  `form:"value1" json:"value1"`
	Value2 *json.RawMessage `form:"value2,omitempty" json:"value2,omitempty"`
}

// ApplyDefaults sets default values for fields that are nil.
func (s *ObjectWithJSONField) ApplyDefaults() {
}

// #/components/schemas/Enum1
// Conflicts with Enum2, enum values need to be prefixed with type
// name.
type Enum1 string

const (
	Enum1One   Enum1 = "One"
	Enum1Two   Enum1 = "Two"
	Enum1Three Enum1 = "Three"
)

// #/components/schemas/Enum2
// Conflicts with Enum1, enum values need to be prefixed with type
// name.
type Enum2 string

const (
	Enum2Two   Enum2 = "Two"
	Enum2Three Enum2 = "Three"
	Enum2Four  Enum2 = "Four"
)

// #/components/schemas/Enum3
// Enum values conflict with Enums above, need to be prefixed
// with type name.
type Enum3 string

const (
	Enum3Enum1One Enum3 = "Enum1One"
	Enum3Foo      Enum3 = "Foo"
	Enum3Bar      Enum3 = "Bar"
)

// #/components/schemas/Enum4
// No conflicts here, should have unmodified enums
type Enum4 string

const (
	Cat   Enum4 = "Cat"
	Dog   Enum4 = "Dog"
	Mouse Enum4 = "Mouse"
)

// #/components/schemas/Enum5
// Numerical enum
type Enum5 int

const (
	Enum5N5 Enum5 = 5
	Enum5N6 Enum5 = 6
	Enum5N7 Enum5 = 7
)

// #/components/schemas/EnumUnion
// Two enums of the same type combined with allOf.
type EnumUnion struct {
}

// ApplyDefaults sets default values for fields that are nil.
func (s *EnumUnion) ApplyDefaults() {
}

// #/components/schemas/EnumUnion2
// Two enums of the same type combined with allOf.
type EnumUnion2 struct {
}

// ApplyDefaults sets default values for fields that are nil.
func (s *EnumUnion2) ApplyDefaults() {
}

// #/components/schemas/FunnyValues
// Edge cases for enum names
type FunnyValues string

const (
	FunnyValuesAsterisk FunnyValues = "*"
	FunnyValuesN5       FunnyValues = "5"
	FunnyValuesAnd      FunnyValues = "&"
	FunnyValuesPercent  FunnyValues = "%"
	FunnyValuesEmpty    FunnyValues = ""
)

// #/components/schemas/RenameMe
// This schema should be renamed via x-go-name when generating
type RenameMe struct {
	Prop1 string `form:"prop1" json:"prop1"`
	Prop2 string `form:"prop2" json:"prop2"`
}

// ApplyDefaults sets default values for fields that are nil.
func (s *RenameMe) ApplyDefaults() {
}

// #/components/schemas/ReferenceToRenameMe
// When a Schema is renamed, $ref should refer to the new name
type ReferenceToRenameMe struct {
	NewName RenameMe `form:"ToNewName" json:"ToNewName"`
}

// ApplyDefaults sets default values for fields that are nil.
func (s *ReferenceToRenameMe) ApplyDefaults() {
}

// #/paths//ensure-everything-is-referenced/get/requestBody/content/application/json/schema
type EnsureEverythingIsReferencedJSONRequest struct {
	Field SchemaObject `form:"Field" json:"Field"`
}

// ApplyDefaults sets default values for fields that are nil.
func (s *EnsureEverythingIsReferencedJSONRequest) ApplyDefaults() {
}

// #/paths//ensure-everything-is-referenced/get/responses/200/content/application/json/schema
type EnsureEverythingIsReferencedJSONResponse struct {
	One       *AdditionalPropertiesObject1 `form:"one,omitempty" json:"one,omitempty"`
	Two       *AdditionalPropertiesObject2 `form:"two,omitempty" json:"two,omitempty"`
	Three     *AdditionalPropertiesObject3 `form:"three,omitempty" json:"three,omitempty"`
	Four      *AdditionalPropertiesObject4 `form:"four,omitempty" json:"four,omitempty"`
	Five      *AdditionalPropertiesObject5 `form:"five,omitempty" json:"five,omitempty"`
	Six       *AdditionalPropertiesObject6 `form:"six,omitempty" json:"six,omitempty"`
	OneOf1    *OneOfObject1                `form:"oneOf1,omitempty" json:"oneOf1,omitempty"`
	OneOf2    *OneOfObject2                `form:"oneOf2,omitempty" json:"oneOf2,omitempty"`
	OneOf3    *OneOfObject3                `form:"oneOf3,omitempty" json:"oneOf3,omitempty"`
	OneOf4    *OneOfObject4                `form:"oneOf4,omitempty" json:"oneOf4,omitempty"`
	OneOf5    *OneOfObject5                `form:"oneOf5,omitempty" json:"oneOf5,omitempty"`
	OneOf6    *OneOfObject6                `form:"oneOf6,omitempty" json:"oneOf6,omitempty"`
	OneOf7    *OneOfObject7                `form:"oneOf7,omitempty" json:"oneOf7,omitempty"`
	OneOf8    *OneOfObject8                `form:"oneOf8,omitempty" json:"oneOf8,omitempty"`
	OneOf9    *OneOfObject9                `form:"oneOf9,omitempty" json:"oneOf9,omitempty"`
	OneOf10   *OneOfObject10               `form:"oneOf10,omitempty" json:"oneOf10,omitempty"`
	OneOf11   *OneOfObject11               `form:"oneOf11,omitempty" json:"oneOf11,omitempty"`
	OneOf12   *OneOfObject12               `form:"oneOf12,omitempty" json:"oneOf12,omitempty"`
	AnyOf1    *AnyOfObject1                `form:"anyOf1,omitempty" json:"anyOf1,omitempty"`
	JSONField *ObjectWithJSONField         `form:"jsonField,omitempty" json:"jsonField,omitempty"`
}

// ApplyDefaults sets default values for fields that are nil.
func (s *EnsureEverythingIsReferencedJSONResponse) ApplyDefaults() {
	if s.One != nil {
		s.One.ApplyDefaults()
	}
	if s.Two != nil {
		s.Two.ApplyDefaults()
	}
	if s.Three != nil {
		s.Three.ApplyDefaults()
	}
	if s.Four != nil {
		s.Four.ApplyDefaults()
	}
	if s.OneOf1 != nil {
		s.OneOf1.ApplyDefaults()
	}
	if s.OneOf2 != nil {
		s.OneOf2.ApplyDefaults()
	}
	if s.OneOf3 != nil {
		s.OneOf3.ApplyDefaults()
	}
	if s.OneOf4 != nil {
		s.OneOf4.ApplyDefaults()
	}
	if s.OneOf5 != nil {
		s.OneOf5.ApplyDefaults()
	}
	if s.OneOf6 != nil {
		s.OneOf6.ApplyDefaults()
	}
	if s.OneOf8 != nil {
		s.OneOf8.ApplyDefaults()
	}
	if s.OneOf9 != nil {
		s.OneOf9.ApplyDefaults()
	}
	if s.OneOf10 != nil {
		s.OneOf10.ApplyDefaults()
	}
	if s.OneOf12 != nil {
		s.OneOf12.ApplyDefaults()
	}
	if s.AnyOf1 != nil {
		s.AnyOf1.ApplyDefaults()
	}
	if s.JSONField != nil {
		s.JSONField.ApplyDefaults()
	}
}

// #/paths//params_with_add_props/get/parameters/0/schema
type GetParamsWithAddPropsParameter0 = map[string]any

// #/paths//params_with_add_props/get/parameters/1/schema
type GetParamsWithAddPropsParameter11 struct {
	Inner map[string]string `form:"inner" json:"inner"`
}

// ApplyDefaults sets default values for fields that are nil.
func (s *GetParamsWithAddPropsParameter11) ApplyDefaults() {
}

// #/paths//params_with_add_props/get/parameters/1/schema/properties/inner
type GetParamsWithAddPropsParameter12 = map[string]string

// #/paths//params_with_add_props/post/requestBody/content/application/json/schema
type BodyWithAddPropsJSONRequest struct {
	Name                 string         `form:"name" json:"name"`
	Inner                map[string]int `form:"inner" json:"inner"`
	AdditionalProperties map[string]any `json:"-"`
}

// Get returns the specified additional property value and whether it was found.
func (a BodyWithAddPropsJSONRequest) Get(fieldName string) (value any, found bool) {
	if a.AdditionalProperties != nil {
		value, found = a.AdditionalProperties[fieldName]
	}
	return
}

// Set sets an additional property value.
func (a *BodyWithAddPropsJSONRequest) Set(fieldName string, value any) {
	if a.AdditionalProperties == nil {
		a.AdditionalProperties = make(map[string]any)
	}
	a.AdditionalProperties[fieldName] = value
}

func (a *BodyWithAddPropsJSONRequest) UnmarshalJSON(b []byte) error {
	object := make(map[string]json.RawMessage)
	err := json.Unmarshal(b, &object)
	if err != nil {
		return err
	}

	if raw, found := object["name"]; found {
		if err := json.Unmarshal(raw, &a.Name); err != nil {
			return fmt.Errorf("error reading 'name': %w", err)
		}
		delete(object, "name")
	}

	if raw, found := object["inner"]; found {
		if err := json.Unmarshal(raw, &a.Inner); err != nil {
			return fmt.Errorf("error reading 'inner': %w", err)
		}
		delete(object, "inner")
	}

	if len(object) != 0 {
		a.AdditionalProperties = make(map[string]any)
		for fieldName, fieldBuf := range object {
			var fieldVal any
			err := json.Unmarshal(fieldBuf, &fieldVal)
			if err != nil {
				return fmt.Errorf("error unmarshaling field %s: %w", fieldName, err)
			}
			a.AdditionalProperties[fieldName] = fieldVal
		}
	}
	return nil
}

func (a BodyWithAddPropsJSONRequest) MarshalJSON() ([]byte, error) {
	var err error
	object := make(map[string]json.RawMessage)

	object["name"], err = json.Marshal(a.Name)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'name': %w", err)
	}

	object["inner"], err = json.Marshal(a.Inner)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'inner': %w", err)
	}

	for fieldName, field := range a.AdditionalProperties {
		object[fieldName], err = json.Marshal(field)
		if err != nil {
			return nil, fmt.Errorf("error marshaling '%s': %w", fieldName, err)
		}
	}
	return json.Marshal(object)
}

// ApplyDefaults sets default values for fields that are nil.
func (s *BodyWithAddPropsJSONRequest) ApplyDefaults() {
}

// #/paths//params_with_add_props/post/requestBody/content/application/json/schema/properties/inner
type PostParamsWithAddPropsRequest = map[string]int

// Base64-encoded, gzip-compressed OpenAPI spec.
var openAPISpecJSON = []string{
	"H4sIAAAAAAAC/+xbX4/bNhJ/96cYbO8uwEH7x/Z60+otbRO0BzRbJHvtw+GwoKWRxVYiVZKyY6Af/kDq",
	"HyVTkmXv5hI0+7SWyOFvhsOZH8kRz5CRjPpwsby6uZpfzCiLuD8D2KKQlDMf5lc3VzczAEVVgj48oFTw",
	"HsUWxQwgoQEyiboDACMp+vDTjw+zjKhY6ofXyGQu8BK3KPYqpmxzSeWlwAgFsgDDouMGVfEPAM9QEEU5",
	"+zH0oej8uu77o3xX9yzbhygDQTNloP5ZPgR4iKkEZGHGKVOAH6hUEiQHFRMFAU8zzpApCQFhsEYIBBKF",
	"IVAGKqayFiMzDICwEBhXul0mclYP/RU83H9/70NEN7lA4LmCXbyHnAU8TZEpyjZGGgQklyghIjTJBcq6",
	"O0BGBElRoZC+9RTgEv4mMPLh4qvrBux10/r65+rf+/VvGKiLsrfAP3KU6lse7v1aCZeopiFFef2u6dZI",
	"khlnEmUjZ3Fz0/zoWD5LSIAxT0LjFdVfwJlCpuxeACTLEhqYOb7+TXLWfgsggxhT0n0KoPYZ+sCNvgcv",
	"M6EdR1Ebb/PHGboeu01TjC+vX4Uh1SBJ8nMtvLD2/MIhTO34U46xcI4RC3xSTZauUSKei6cc5NY5CN0+",
	"qSYr1yCSfnjKMe4u3L51H82nD3Ov+w34k5G7OEvuolfu8iy5y165t2fJve2VuzpL7qpX7t1Zcvv94eVZ",
	"cl/2yv36LLlf98r95iy53/Svi5vzFsZNv+Qzl1z/mpuft+jmzlVH2P6kKPFK9xuIEjqBvqGYhCdgNlJ/",
	"pSr+VyWkGSHEiORJK3O7aUTJEq7flf81fKSgK/JxR1X8SMLwUedoOUz4DK2RGtOrMNThVw7TvFegmSbo",
	"ISwuZRgbgTUP97CLaRAbXkQFAqlju8UYSmmHXEzzsILTZvM+4vNny+6GdtaCICZycEj9R5kPf+Qo9taz",
	"Em7ogxI5Wi+k2msOLmmaJa3nDs7Uy5eII8F1Rqr1XpyuNwPCONunPJdAGUNR6V9NCkMMJSgOa2wDzwUz",
	"XFxxIGUnow1EXDjRayE7Ln4/2awO8/UzSqPMRH7qtLmL4RkhUgnKNq3XDfb/lNb8bz9Td6zeU9m6wg/q",
	"OksIncjTLRUyLt2rXe83jl/rP2inqnY49uLWuAll+m1IBQbKaW1PR4VZE48HvFNHE5eIoU1Wj285bDq8",
	"/3FbdWh7Y1bqFFca8OERLz7ejytBlCnctLys68wavtdx6aMj1Sft+02e1A3LtFv0eW9+FLmykuKaY8GT",
	"1tw65zSiQqq3HS9wthRIwnuW7N+V9tdW9adE+GqJUFnPoUm2lWCvOGNB2HBIeYgJyJjnSQgx2SJQBWYN",
	"m0MZFF47K0n9fkeTpDpsoSxI8hBD2MXI9EsqQSJTEAmeQpBQ/b/iIM1h1NVs1PUrlJ01uhNU4ZBZ+ly5",
	"7tjxydK5rWyq59H6Wc+Y3cQxN9ZrJ8gDX3qbJwlZNz7zxae++NQpPgXAKk9qYAwciPmu1P1DH/sFHhV8",
	"jrIqxzjSjst32TEeScNxQ/OsQDUizJGowjpLDefCw3EHDvuc9vueozR+S5KE7wY3Eh/XfNOtAhFJ5JgX",
	"LZ1WeKWV19uJvcMC+yfXv6vbiF5HLI7b/sVRM9BI775LOju2aXzSue7SwB7618c/XdyzN1D2GPZIotfZ",
	"/nhPNDuriaHLbA4KLme2oyENTCMxOEHDoaI4WXnhPKWxs/uLEV3u3AtICLLXIbdA1N3e9DkY0d3KJ1Rh",
	"ehDaOk4ytjN4KiVffkYTVtGxQif7kNCphDl+LADXN6SyvH6EkOqWKWVE8SoQmw42JxgCZob/hQhKmJq/",
	"OKHT4pROywPdF2O6U5ZQhoAJplpsn67PFaouHQvAsQia/ixP1xa1qPqvOU+QsK767ixX6mzaTYvzOaPt",
	"M4SOoU52jJOd41wHuR1wkCwx2fIDhgWDvIQgl4qnkBIhY5JQtrnOWfNjmi2N4HLB70eS52e59lZja68V",
	"ZWCdKx16UpJlT6D47Sk6rKpOLWTN8BURNHtVR5C0r+umKa/j7uesuf4r8duuvL2diBhgu5qA1zb4fLrF",
	"MyIUJclf3vK2GUczpmTkd3wMiMQBi1qNPrZxOcNHHj1uS/POn8m+hfhHU79ykqXd3JLUBPogOw+Q5IM0",
	"fGISnpwj7Av/MccpMumpW0zT+1NMk3ZtwnEmcDnZkVYwzT4lI9xNWl4a7uCqmk922e3dJJiuw80aVasa",
	"xDmXXR/2ikCwTrA5T74sDoE1IpqgVxIbBWkexCCRSZw2552CQuc+olMQ6D6HPKjoO9w7ONzn0GLFc87w",
	"iFZqx7tPNIoDc7uzd++JLh/euwzvqB3R0mUJ+01n29W8sOahVZfjVidJ7qMafhUAzVPb4s5NVe8N62Xf",
	"zvCsvdny1C3WYaKbL08Ii4ZNcBWjKM4rZXEwXddDf4mXn0C8HD8KtSrKnE5QFBcVFWug6eLMKmH72By8",
	"ZTP/+U77O5VPB2Mv/GmHo3acb63htpyDM6LKZBNV7fHcnsx0omHcRLzHYKtn1WDCHdURCtAignV3KZ+f",
	"Bq1wMRH+liT58Sf2zrMpF+JCbIHusODUf4Y7LTPi3B+/uo+4SInyTQ1tu/fitN6H96IFlvKW6jXLU3fI",
	"bcoivuMsSmigynsL3WXhAbI8LS1pqiaLoknIBBZp2rRtJSY9/NWsVwEtUKO8Z+jBw4578KApoAV0MR3o",
	"/BmBNhg9eMNzYSFdjiB9bWEKStQNaAlkzbfoueA21RwV7GPhGnMY477h3INviQ34dgTwW17jlBCjQK9V",
	"8ZKzlIc0ohia4eQ4mu+I8uB7vvHgJ55Le5ZXY1DyFAUNSGJkzfqDVTXUyoM7D15aQ/zbvp/o+1pvxwtd",
	"TGVIjCBJioXBA56uKatcx/Dyqz6SPlTtbmbkYkLjsoy/VmHxCepQWf09bpGVNn+TM7b/pRXMW4hfhxs0",
	"tE6a61CzYrVXj/mRNeyLf9qM7sWq9esfrV9/b/0qfrxDPd5P6IRnasLK69rS69d6I6+7hLClBD5cbvil",
	"ufw3NVwbZKakuEZbv/fhLe6siqgjk4x+Np4+dKvFhFoSI9UrupUzVX/L+sAHTfKrVpOUdX5FmZyxhmec",
	"pbKSuTHWAUz7HsNdQ8uO1vyBlwYb++yjcsgK9oVD4VqY0bZTqNv+WsQ/nLlCcthu56xuqPYr1QhtNQ/q",
	"eoeqr6d9BtDz2c2QvezagIve8n4j2CqPcZch93/yUftg94uWzkfD/WbvNJxZ7Avc79pnKs3IM/fXGH/p",
	"aSmSirFjHWcs25oof5pZu4M7I1eVNDjzgEeRB2uuYithGxCLHmCL/zewZQ+w5UcARhIaoAeo6eKar8vA",
	"Zn1IXwW3g+9DXJGtbvRlTfwvAAD//9rLIRuFQgAA",
}

// decodeOpenAPISpec decodes and decompresses the embedded spec.
func decodeOpenAPISpec() ([]byte, error) {
	joined := strings.Join(openAPISpecJSON, "")
	raw, err := base64.StdEncoding.DecodeString(joined)
	if err != nil {
		return nil, fmt.Errorf("decoding base64: %w", err)
	}
	r, err := gzip.NewReader(bytes.NewReader(raw))
	if err != nil {
		return nil, fmt.Errorf("creating gzip reader: %w", err)
	}
	defer r.Close()
	var out bytes.Buffer
	if _, err := out.ReadFrom(r); err != nil {
		return nil, fmt.Errorf("decompressing: %w", err)
	}
	return out.Bytes(), nil
}

// decodeOpenAPISpecCached returns a closure that caches the decoded spec.
func decodeOpenAPISpecCached() func() ([]byte, error) {
	var cached []byte
	var cachedErr error
	var once sync.Once
	return func() ([]byte, error) {
		once.Do(func() {
			cached, cachedErr = decodeOpenAPISpec()
		})
		return cached, cachedErr
	}
}

var openAPISpec = decodeOpenAPISpecCached()

// GetOpenAPISpecJSON returns the raw OpenAPI spec as JSON bytes.
func GetOpenAPISpecJSON() ([]byte, error) {
	return openAPISpec()
}
