// Code generated by oapi-codegen; DO NOT EDIT.

package output

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"strings"
	"sync"

	oapiCodegenHelpersPkg "github.com/oapi-codegen/oapi-codegen-exp/experimental/runtime/helpers"
)

// #/paths//something/get/responses/200/content/application/json/schema
type GetSomethingJSONResponse struct {
	Results []GetSomething200ResponseJSON2 `form:"results" json:"results"`
}

// ApplyDefaults sets default values for fields that are nil.
func (s *GetSomethingJSONResponse) ApplyDefaults() {
}

// #/paths//something/get/responses/200/content/application/json/schema/properties/results
type GetSomething200ResponseJSON1 = []GetSomething200ResponseJSON2

// #/paths//something/get/responses/200/content/application/json/schema/properties/results/items

type GetSomething200ResponseJSON2 struct {
	union json.RawMessage
}

// AsGetSomething200ResponseJSONAnyOf0 returns the union data inside the GetSomething200ResponseJSON2 as a GetSomething200ResponseJSONAnyOf0.
func (t GetSomething200ResponseJSON2) AsGetSomething200ResponseJSONAnyOf0() (GetSomething200ResponseJSONAnyOf0, error) {
	var body GetSomething200ResponseJSONAnyOf0
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromGetSomething200ResponseJSONAnyOf0 overwrites any union data inside the GetSomething200ResponseJSON2 as the provided GetSomething200ResponseJSONAnyOf0.
func (t *GetSomething200ResponseJSON2) FromGetSomething200ResponseJSONAnyOf0(v GetSomething200ResponseJSONAnyOf0) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeGetSomething200ResponseJSONAnyOf0 performs a merge with any union data inside the GetSomething200ResponseJSON2, using the provided GetSomething200ResponseJSONAnyOf0.
func (t *GetSomething200ResponseJSON2) MergeGetSomething200ResponseJSONAnyOf0(v GetSomething200ResponseJSONAnyOf0) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}
	merged, err := oapiCodegenHelpersPkg.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsGetSomething200ResponseJSONAnyOf11 returns the union data inside the GetSomething200ResponseJSON2 as a GetSomething200ResponseJSONAnyOf11.
func (t GetSomething200ResponseJSON2) AsGetSomething200ResponseJSONAnyOf11() (GetSomething200ResponseJSONAnyOf11, error) {
	var body GetSomething200ResponseJSONAnyOf11
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromGetSomething200ResponseJSONAnyOf11 overwrites any union data inside the GetSomething200ResponseJSON2 as the provided GetSomething200ResponseJSONAnyOf11.
func (t *GetSomething200ResponseJSON2) FromGetSomething200ResponseJSONAnyOf11(v GetSomething200ResponseJSONAnyOf11) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeGetSomething200ResponseJSONAnyOf11 performs a merge with any union data inside the GetSomething200ResponseJSON2, using the provided GetSomething200ResponseJSONAnyOf11.
func (t *GetSomething200ResponseJSON2) MergeGetSomething200ResponseJSONAnyOf11(v GetSomething200ResponseJSONAnyOf11) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}
	merged, err := oapiCodegenHelpersPkg.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t GetSomething200ResponseJSON2) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *GetSomething200ResponseJSON2) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}

// ApplyDefaults sets default values for fields that are nil.
func (t *GetSomething200ResponseJSON2) ApplyDefaults() {
}

// #/paths//something/get/responses/200/content/application/json/schema/properties/results/items/anyOf/0
type GetSomething200ResponseJSONAnyOf0 struct {
	Order *string `form:"order,omitempty" json:"order,omitempty"`
}

// ApplyDefaults sets default values for fields that are nil.
func (s *GetSomething200ResponseJSONAnyOf0) ApplyDefaults() {
}

// #/paths//something/get/responses/200/content/application/json/schema/properties/results/items/anyOf/1
type GetSomething200ResponseJSONAnyOf11 struct {
	Error *GetSomething200ResponseJSONAnyOf12 `form:"error,omitempty" json:"error,omitempty"`
}

// ApplyDefaults sets default values for fields that are nil.
func (s *GetSomething200ResponseJSONAnyOf11) ApplyDefaults() {
	if s.Error != nil {
		s.Error.ApplyDefaults()
	}
}

// #/paths//something/get/responses/200/content/application/json/schema/properties/results/items/anyOf/1/properties/error
type GetSomething200ResponseJSONAnyOf12 struct {
	Code    *float32 `form:"code,omitempty" json:"code,omitempty"`
	Message *string  `form:"message,omitempty" json:"message,omitempty"`
}

// ApplyDefaults sets default values for fields that are nil.
func (s *GetSomething200ResponseJSONAnyOf12) ApplyDefaults() {
}

// Base64-encoded, gzip-compressed OpenAPI spec.
var openAPISpecJSON = []string{
	"H4sIAAAAAAAC/7xTTW+bQBC98yue4ksrJeC0VaVy66nyKVJTqcdoDWOYyMxud4ZY/vfVgqlJncTJJZyY",
	"fTP7PhgWWKn2hOsv376W+C5e9p3vFX59T5VBq5Y6hx1bCy90s0FDQtEZKVge3JZrcE1ivGGK2QKtWdCy",
	"KBq2tl/nle8K7wJfVb6mhuRxwYlai8SdLbIFfrckcAKWLQtN5CxwiKTBixJ6JYWT/c2mGARdwlr6p6qG",
	"7QNBXEfZAjunUHPRWJrRg4P03ZoiPlDe5Jf4tFze/STtt6Z3K6PuI3YtVy14Zk/ww+eZDyQucInP+TJf",
	"ZiwbX2aAsW2pnIWIX6SWAQ8Ulb2UuB76g7NW00ChviNrWZpUAQ3Z+AL4kDywl1VdpvPbqfOATxnoNICk",
	"/1gANWkVOdhAfHHbVxWpXswaKi9GYvMZwIWw5WpgLu7Vy2MUh+/w/ymGqMvDppyAkf70HKk+HQOukpWU",
	"+QkWYgrBeO5xfucw9RQ0qXExuv2TOBt1z4xiXKjnwCT4Ra+v1X98fKwpvtwyOVKLxxV4B2kUo3+ltLOc",
	"b+Ed17Om810T/fgrn23vSNU1b7j3kPjfAAAA///mDrwBGwUAAA==",
}

// decodeOpenAPISpec decodes and decompresses the embedded spec.
func decodeOpenAPISpec() ([]byte, error) {
	joined := strings.Join(openAPISpecJSON, "")
	raw, err := base64.StdEncoding.DecodeString(joined)
	if err != nil {
		return nil, fmt.Errorf("decoding base64: %w", err)
	}
	r, err := gzip.NewReader(bytes.NewReader(raw))
	if err != nil {
		return nil, fmt.Errorf("creating gzip reader: %w", err)
	}
	defer r.Close()
	var out bytes.Buffer
	if _, err := out.ReadFrom(r); err != nil {
		return nil, fmt.Errorf("decompressing: %w", err)
	}
	return out.Bytes(), nil
}

// decodeOpenAPISpecCached returns a closure that caches the decoded spec.
func decodeOpenAPISpecCached() func() ([]byte, error) {
	var cached []byte
	var cachedErr error
	var once sync.Once
	return func() ([]byte, error) {
		once.Do(func() {
			cached, cachedErr = decodeOpenAPISpec()
		})
		return cached, cachedErr
	}
}

var openAPISpec = decodeOpenAPISpecCached()

// GetOpenAPISpecJSON returns the raw OpenAPI spec as JSON bytes.
func GetOpenAPISpecJSON() ([]byte, error) {
	return openAPISpec()
}
