// Code generated by oapi-codegen; DO NOT EDIT.

package output

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"encoding/json"
	"errors"
	"fmt"
	"strings"
	"sync"
	"time"

	oapiCodegenHelpersPkg "github.com/oapi-codegen/oapi-codegen-exp/experimental/runtime/helpers"
	oapiCodegenTypesPkg "github.com/oapi-codegen/oapi-codegen-exp/experimental/runtime/types"
)

// #/components/schemas/AllTypesRequired
type AllTypesRequired struct {
	IntField      int                       `form:"intField" json:"intField"`
	Int32Field    int32                     `form:"int32Field" json:"int32Field"`
	Int64Field    int64                     `form:"int64Field" json:"int64Field"`
	FloatField    float32                   `form:"floatField" json:"floatField"`
	DoubleField   float64                   `form:"doubleField" json:"doubleField"`
	NumberField   float32                   `form:"numberField" json:"numberField"`
	StringField   string                    `form:"stringField" json:"stringField"`
	BoolField     bool                      `form:"boolField" json:"boolField"`
	DateField     oapiCodegenTypesPkg.Date  `form:"dateField" json:"dateField"`
	DateTimeField time.Time                 `form:"dateTimeField" json:"dateTimeField"`
	UUIDField     oapiCodegenTypesPkg.UUID  `form:"uuidField" json:"uuidField"`
	EmailField    oapiCodegenTypesPkg.Email `form:"emailField" json:"emailField"`
	URIField      string                    `form:"uriField" json:"uriField"`
	HostnameField string                    `form:"hostnameField" json:"hostnameField"`
	Ipv4Field     string                    `form:"ipv4Field" json:"ipv4Field"`
	Ipv6Field     string                    `form:"ipv6Field" json:"ipv6Field"`
	ByteField     []byte                    `form:"byteField" json:"byteField"`
	BinaryField   oapiCodegenTypesPkg.File  `form:"binaryField" json:"binaryField"`
	PasswordField string                    `form:"passwordField" json:"passwordField"`
}

// ApplyDefaults sets default values for fields that are nil.
func (s *AllTypesRequired) ApplyDefaults() {
}

// #/components/schemas/AllTypesOptional
type AllTypesOptional struct {
	IntField      *int                       `form:"intField,omitempty" json:"intField,omitempty"`
	Int32Field    *int32                     `form:"int32Field,omitempty" json:"int32Field,omitempty"`
	Int64Field    *int64                     `form:"int64Field,omitempty" json:"int64Field,omitempty"`
	FloatField    *float32                   `form:"floatField,omitempty" json:"floatField,omitempty"`
	DoubleField   *float64                   `form:"doubleField,omitempty" json:"doubleField,omitempty"`
	NumberField   *float32                   `form:"numberField,omitempty" json:"numberField,omitempty"`
	StringField   *string                    `form:"stringField,omitempty" json:"stringField,omitempty"`
	BoolField     *bool                      `form:"boolField,omitempty" json:"boolField,omitempty"`
	DateField     *oapiCodegenTypesPkg.Date  `form:"dateField,omitempty" json:"dateField,omitempty"`
	DateTimeField *time.Time                 `form:"dateTimeField,omitempty" json:"dateTimeField,omitempty"`
	UUIDField     *oapiCodegenTypesPkg.UUID  `form:"uuidField,omitempty" json:"uuidField,omitempty"`
	EmailField    *oapiCodegenTypesPkg.Email `form:"emailField,omitempty" json:"emailField,omitempty"`
}

// ApplyDefaults sets default values for fields that are nil.
func (s *AllTypesOptional) ApplyDefaults() {
}

// #/components/schemas/NullableRequired
type NullableRequired struct {
	NullableString oapiCodegenTypesPkg.Nullable[string]                         `form:"nullableString" json:"nullableString"`
	NullableInt    oapiCodegenTypesPkg.Nullable[int]                            `form:"nullableInt" json:"nullableInt"`
	NullableObject oapiCodegenTypesPkg.Nullable[NullableRequiredNullableObject] `form:"nullableObject" json:"nullableObject"`
}

// ApplyDefaults sets default values for fields that are nil.
func (s *NullableRequired) ApplyDefaults() {
}

// #/components/schemas/NullableRequired/properties/nullableObject
type NullableRequiredNullableObject struct {
	Name *string `form:"name,omitempty" json:"name,omitempty"`
}

// ApplyDefaults sets default values for fields that are nil.
func (s *NullableRequiredNullableObject) ApplyDefaults() {
}

// #/components/schemas/NullableOptional
type NullableOptional struct {
	NullableString oapiCodegenTypesPkg.Nullable[string] `form:"nullableString,omitempty" json:"nullableString,omitempty"`
	NullableInt    oapiCodegenTypesPkg.Nullable[int]    `form:"nullableInt,omitempty" json:"nullableInt,omitempty"`
}

// ApplyDefaults sets default values for fields that are nil.
func (s *NullableOptional) ApplyDefaults() {
}

// #/components/schemas/NullableRefOneOf
type NullableRefOneOf struct {
	NullableObject         oapiCodegenTypesPkg.Nullable[SimpleObject] `form:"nullableObject" json:"nullableObject"`
	NullableObjectOptional oapiCodegenTypesPkg.Nullable[SimpleObject] `form:"nullableObjectOptional,omitempty" json:"nullableObjectOptional,omitempty"`
}

// ApplyDefaults sets default values for fields that are nil.
func (s *NullableRefOneOf) ApplyDefaults() {
}

// #/components/schemas/NullableRefAnyOf
type NullableRefAnyOf struct {
	NullableObject oapiCodegenTypesPkg.Nullable[SimpleObject] `form:"nullableObject" json:"nullableObject"`
}

// ApplyDefaults sets default values for fields that are nil.
func (s *NullableRefAnyOf) ApplyDefaults() {
}

// #/components/schemas/ArrayTypes
type ArrayTypes struct {
	StringArray          []string                          `form:"stringArray,omitempty" json:"stringArray,omitempty"`
	IntArray             []int                             `form:"intArray,omitempty" json:"intArray,omitempty"`
	ObjectArray          []SimpleObject                    `form:"objectArray,omitempty" json:"objectArray,omitempty"`
	InlineObjectArray    []ArrayTypesInlineObjectArrayItem `form:"inlineObjectArray,omitempty" json:"inlineObjectArray,omitempty"`
	NestedArray          [][]string                        `form:"nestedArray,omitempty" json:"nestedArray,omitempty"`
	NullableArray        []string                          `form:"nullableArray,omitempty" json:"nullableArray,omitempty"`
	ArrayWithConstraints []string                          `form:"arrayWithConstraints,omitempty" json:"arrayWithConstraints,omitempty"`
}

// ApplyDefaults sets default values for fields that are nil.
func (s *ArrayTypes) ApplyDefaults() {
}

// #/components/schemas/ArrayTypes/properties/objectArray
type ArrayTypesObjectArray = []SimpleObject

// #/components/schemas/ArrayTypes/properties/inlineObjectArray
type ArrayTypesInlineObjectArray = []ArrayTypesInlineObjectArrayItem

// #/components/schemas/ArrayTypes/properties/inlineObjectArray/items
type ArrayTypesInlineObjectArrayItem struct {
	ID   *int    `form:"id,omitempty" json:"id,omitempty"`
	Name *string `form:"name,omitempty" json:"name,omitempty"`
}

// ApplyDefaults sets default values for fields that are nil.
func (s *ArrayTypesInlineObjectArrayItem) ApplyDefaults() {
}

// #/components/schemas/SimpleObject
type SimpleObject struct {
	ID   int     `form:"id" json:"id"`
	Name *string `form:"name,omitempty" json:"name,omitempty"`
}

// ApplyDefaults sets default values for fields that are nil.
func (s *SimpleObject) ApplyDefaults() {
}

// #/components/schemas/NestedObject
type NestedObject struct {
	Outer *NestedObjectOuter `form:"outer,omitempty" json:"outer,omitempty"`
}

// ApplyDefaults sets default values for fields that are nil.
func (s *NestedObject) ApplyDefaults() {
	if s.Outer != nil {
		s.Outer.ApplyDefaults()
	}
}

// #/components/schemas/NestedObject/properties/outer
type NestedObjectOuter struct {
	Inner *NestedObjectOuterInner `form:"inner,omitempty" json:"inner,omitempty"`
}

// ApplyDefaults sets default values for fields that are nil.
func (s *NestedObjectOuter) ApplyDefaults() {
	if s.Inner != nil {
		s.Inner.ApplyDefaults()
	}
}

// #/components/schemas/NestedObject/properties/outer/properties/inner
type NestedObjectOuterInner struct {
	Value *string `form:"value,omitempty" json:"value,omitempty"`
}

// ApplyDefaults sets default values for fields that are nil.
func (s *NestedObjectOuterInner) ApplyDefaults() {
}

// #/components/schemas/AdditionalPropsAny
type AdditionalPropsAny = map[string]any

// #/components/schemas/AdditionalPropsNone
type AdditionalPropsNone struct {
	Known                *string        `form:"known,omitempty" json:"known,omitempty"`
	AdditionalProperties map[string]any `json:"-"`
}

// Get returns the specified additional property value and whether it was found.
func (a AdditionalPropsNone) Get(fieldName string) (value any, found bool) {
	if a.AdditionalProperties != nil {
		value, found = a.AdditionalProperties[fieldName]
	}
	return
}

// Set sets an additional property value.
func (a *AdditionalPropsNone) Set(fieldName string, value any) {
	if a.AdditionalProperties == nil {
		a.AdditionalProperties = make(map[string]any)
	}
	a.AdditionalProperties[fieldName] = value
}

func (a *AdditionalPropsNone) UnmarshalJSON(b []byte) error {
	object := make(map[string]json.RawMessage)
	err := json.Unmarshal(b, &object)
	if err != nil {
		return err
	}

	if raw, found := object["known"]; found {
		var val string
		if err := json.Unmarshal(raw, &val); err != nil {
			return fmt.Errorf("error reading 'known': %w", err)
		}
		a.Known = &val
		delete(object, "known")
	}

	if len(object) != 0 {
		a.AdditionalProperties = make(map[string]any)
		for fieldName, fieldBuf := range object {
			var fieldVal any
			err := json.Unmarshal(fieldBuf, &fieldVal)
			if err != nil {
				return fmt.Errorf("error unmarshaling field %s: %w", fieldName, err)
			}
			a.AdditionalProperties[fieldName] = fieldVal
		}
	}
	return nil
}

func (a AdditionalPropsNone) MarshalJSON() ([]byte, error) {
	var err error
	object := make(map[string]json.RawMessage)

	if a.Known != nil {
		object["known"], err = json.Marshal(a.Known)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'known': %w", err)
		}
	}

	for fieldName, field := range a.AdditionalProperties {
		object[fieldName], err = json.Marshal(field)
		if err != nil {
			return nil, fmt.Errorf("error marshaling '%s': %w", fieldName, err)
		}
	}
	return json.Marshal(object)
}

// ApplyDefaults sets default values for fields that are nil.
func (s *AdditionalPropsNone) ApplyDefaults() {
}

// #/components/schemas/AdditionalPropsTyped
type AdditionalPropsTyped = map[string]int

// #/components/schemas/AdditionalPropsObject
type AdditionalPropsObject = map[string]any

// #/components/schemas/AdditionalPropsWithProps
type AdditionalPropsWithProps struct {
	ID                   *int              `form:"id,omitempty" json:"id,omitempty"`
	AdditionalProperties map[string]string `json:"-"`
}

// Get returns the specified additional property value and whether it was found.
func (a AdditionalPropsWithProps) Get(fieldName string) (value string, found bool) {
	if a.AdditionalProperties != nil {
		value, found = a.AdditionalProperties[fieldName]
	}
	return
}

// Set sets an additional property value.
func (a *AdditionalPropsWithProps) Set(fieldName string, value string) {
	if a.AdditionalProperties == nil {
		a.AdditionalProperties = make(map[string]string)
	}
	a.AdditionalProperties[fieldName] = value
}

func (a *AdditionalPropsWithProps) UnmarshalJSON(b []byte) error {
	object := make(map[string]json.RawMessage)
	err := json.Unmarshal(b, &object)
	if err != nil {
		return err
	}

	if raw, found := object["id"]; found {
		var val int
		if err := json.Unmarshal(raw, &val); err != nil {
			return fmt.Errorf("error reading 'id': %w", err)
		}
		a.ID = &val
		delete(object, "id")
	}

	if len(object) != 0 {
		a.AdditionalProperties = make(map[string]string)
		for fieldName, fieldBuf := range object {
			var fieldVal string
			err := json.Unmarshal(fieldBuf, &fieldVal)
			if err != nil {
				return fmt.Errorf("error unmarshaling field %s: %w", fieldName, err)
			}
			a.AdditionalProperties[fieldName] = fieldVal
		}
	}
	return nil
}

func (a AdditionalPropsWithProps) MarshalJSON() ([]byte, error) {
	var err error
	object := make(map[string]json.RawMessage)

	if a.ID != nil {
		object["id"], err = json.Marshal(a.ID)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'id': %w", err)
		}
	}

	for fieldName, field := range a.AdditionalProperties {
		object[fieldName], err = json.Marshal(field)
		if err != nil {
			return nil, fmt.Errorf("error marshaling '%s': %w", fieldName, err)
		}
	}
	return json.Marshal(object)
}

// ApplyDefaults sets default values for fields that are nil.
func (s *AdditionalPropsWithProps) ApplyDefaults() {
}

// #/components/schemas/StringEnum
type StringEnum string

const (
	Value1 StringEnum = "value1"
	Value2 StringEnum = "value2"
	Value3 StringEnum = "value3"
)

// #/components/schemas/IntegerEnum
type IntegerEnum int

const (
	IntegerEnumN1 IntegerEnum = 1
	IntegerEnumN2 IntegerEnum = 2
	IntegerEnumN3 IntegerEnum = 3
)

// #/components/schemas/ObjectWithEnum
type ObjectWithEnum struct {
	Status   *string `form:"status,omitempty" json:"status,omitempty"`
	Priority *int    `form:"priority,omitempty" json:"priority,omitempty"`
}

// ApplyDefaults sets default values for fields that are nil.
func (s *ObjectWithEnum) ApplyDefaults() {
}

// #/components/schemas/ObjectWithEnum/properties/status
type ObjectWithEnumStatus string

const (
	Pending   ObjectWithEnumStatus = "pending"
	Active    ObjectWithEnumStatus = "active"
	Completed ObjectWithEnumStatus = "completed"
)

// #/components/schemas/ObjectWithEnum/properties/priority
type ObjectWithEnumPriority int

const (
	ObjectWithEnumPriorityN1 ObjectWithEnumPriority = 1
	ObjectWithEnumPriorityN2 ObjectWithEnumPriority = 2
	ObjectWithEnumPriorityN3 ObjectWithEnumPriority = 3
)

// #/components/schemas/InlineEnumInProperty
type InlineEnumInProperty struct {
	InlineStatus *string `form:"inlineStatus,omitempty" json:"inlineStatus,omitempty"`
}

// ApplyDefaults sets default values for fields that are nil.
func (s *InlineEnumInProperty) ApplyDefaults() {
}

// #/components/schemas/InlineEnumInProperty/properties/inlineStatus
type InlineEnumInPropertyInlineStatus string

const (
	On  InlineEnumInPropertyInlineStatus = "on"
	Off InlineEnumInPropertyInlineStatus = "off"
)

// #/components/schemas/BaseProperties
type BaseProperties struct {
	ID        *int       `form:"id,omitempty" json:"id,omitempty"`
	CreatedAt *time.Time `form:"createdAt,omitempty" json:"createdAt,omitempty"`
}

// ApplyDefaults sets default values for fields that are nil.
func (s *BaseProperties) ApplyDefaults() {
}

// #/components/schemas/ExtendedObject
type ExtendedObject struct {
	ID          *int       `form:"id,omitempty" json:"id,omitempty"`
	CreatedAt   *time.Time `form:"createdAt,omitempty" json:"createdAt,omitempty"`
	Name        string     `form:"name" json:"name"`
	Description *string    `form:"description,omitempty" json:"description,omitempty"`
}

// ApplyDefaults sets default values for fields that are nil.
func (s *ExtendedObject) ApplyDefaults() {
}

// #/components/schemas/DeepInheritance
type DeepInheritance struct {
	ID          *int       `form:"id,omitempty" json:"id,omitempty"`
	CreatedAt   *time.Time `form:"createdAt,omitempty" json:"createdAt,omitempty"`
	Name        string     `form:"name" json:"name"`
	Description *string    `form:"description,omitempty" json:"description,omitempty"`
	Extra       *string    `form:"extra,omitempty" json:"extra,omitempty"`
}

// ApplyDefaults sets default values for fields that are nil.
func (s *DeepInheritance) ApplyDefaults() {
}

// #/components/schemas/AllOfMultipleRefs
type AllOfMultipleRefs struct {
	ID        int        `form:"id" json:"id"`
	CreatedAt *time.Time `form:"createdAt,omitempty" json:"createdAt,omitempty"`
	Name      *string    `form:"name,omitempty" json:"name,omitempty"`
	Merged    *bool      `form:"merged,omitempty" json:"merged,omitempty"`
}

// ApplyDefaults sets default values for fields that are nil.
func (s *AllOfMultipleRefs) ApplyDefaults() {
}

// #/components/schemas/AllOfInlineOnly
type AllOfInlineOnly struct {
	First  *string `form:"first,omitempty" json:"first,omitempty"`
	Second *int    `form:"second,omitempty" json:"second,omitempty"`
}

// ApplyDefaults sets default values for fields that are nil.
func (s *AllOfInlineOnly) ApplyDefaults() {
}

// #/components/schemas/AnyOfPrimitives

type AnyOfPrimitives struct {
	union json.RawMessage
}

// AsString0 returns the union data inside the AnyOfPrimitives as a string.
func (t AnyOfPrimitives) AsString0() (string, error) {
	var body string
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromString0 overwrites any union data inside the AnyOfPrimitives as the provided string.
func (t *AnyOfPrimitives) FromString0(v string) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeString0 performs a merge with any union data inside the AnyOfPrimitives, using the provided string.
func (t *AnyOfPrimitives) MergeString0(v string) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}
	merged, err := oapiCodegenHelpersPkg.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsInt1 returns the union data inside the AnyOfPrimitives as a int.
func (t AnyOfPrimitives) AsInt1() (int, error) {
	var body int
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromInt1 overwrites any union data inside the AnyOfPrimitives as the provided int.
func (t *AnyOfPrimitives) FromInt1(v int) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeInt1 performs a merge with any union data inside the AnyOfPrimitives, using the provided int.
func (t *AnyOfPrimitives) MergeInt1(v int) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}
	merged, err := oapiCodegenHelpersPkg.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t AnyOfPrimitives) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *AnyOfPrimitives) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}

// ApplyDefaults sets default values for fields that are nil.
func (t *AnyOfPrimitives) ApplyDefaults() {
}

// #/components/schemas/AnyOfObjects

type AnyOfObjects struct {
	union json.RawMessage
}

// AsSimpleObject returns the union data inside the AnyOfObjects as a SimpleObject.
func (t AnyOfObjects) AsSimpleObject() (SimpleObject, error) {
	var body SimpleObject
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromSimpleObject overwrites any union data inside the AnyOfObjects as the provided SimpleObject.
func (t *AnyOfObjects) FromSimpleObject(v SimpleObject) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeSimpleObject performs a merge with any union data inside the AnyOfObjects, using the provided SimpleObject.
func (t *AnyOfObjects) MergeSimpleObject(v SimpleObject) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}
	merged, err := oapiCodegenHelpersPkg.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsBaseProperties returns the union data inside the AnyOfObjects as a BaseProperties.
func (t AnyOfObjects) AsBaseProperties() (BaseProperties, error) {
	var body BaseProperties
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromBaseProperties overwrites any union data inside the AnyOfObjects as the provided BaseProperties.
func (t *AnyOfObjects) FromBaseProperties(v BaseProperties) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeBaseProperties performs a merge with any union data inside the AnyOfObjects, using the provided BaseProperties.
func (t *AnyOfObjects) MergeBaseProperties(v BaseProperties) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}
	merged, err := oapiCodegenHelpersPkg.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t AnyOfObjects) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *AnyOfObjects) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}

// ApplyDefaults sets default values for fields that are nil.
func (t *AnyOfObjects) ApplyDefaults() {
}

// #/components/schemas/AnyOfMixed

type AnyOfMixed struct {
	union json.RawMessage
}

// AsString0 returns the union data inside the AnyOfMixed as a string.
func (t AnyOfMixed) AsString0() (string, error) {
	var body string
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromString0 overwrites any union data inside the AnyOfMixed as the provided string.
func (t *AnyOfMixed) FromString0(v string) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeString0 performs a merge with any union data inside the AnyOfMixed, using the provided string.
func (t *AnyOfMixed) MergeString0(v string) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}
	merged, err := oapiCodegenHelpersPkg.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsSimpleObject returns the union data inside the AnyOfMixed as a SimpleObject.
func (t AnyOfMixed) AsSimpleObject() (SimpleObject, error) {
	var body SimpleObject
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromSimpleObject overwrites any union data inside the AnyOfMixed as the provided SimpleObject.
func (t *AnyOfMixed) FromSimpleObject(v SimpleObject) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeSimpleObject performs a merge with any union data inside the AnyOfMixed, using the provided SimpleObject.
func (t *AnyOfMixed) MergeSimpleObject(v SimpleObject) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}
	merged, err := oapiCodegenHelpersPkg.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsAnyOfMixedAnyOf2 returns the union data inside the AnyOfMixed as a AnyOfMixedAnyOf2.
func (t AnyOfMixed) AsAnyOfMixedAnyOf2() (AnyOfMixedAnyOf2, error) {
	var body AnyOfMixedAnyOf2
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromAnyOfMixedAnyOf2 overwrites any union data inside the AnyOfMixed as the provided AnyOfMixedAnyOf2.
func (t *AnyOfMixed) FromAnyOfMixedAnyOf2(v AnyOfMixedAnyOf2) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeAnyOfMixedAnyOf2 performs a merge with any union data inside the AnyOfMixed, using the provided AnyOfMixedAnyOf2.
func (t *AnyOfMixed) MergeAnyOfMixedAnyOf2(v AnyOfMixedAnyOf2) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}
	merged, err := oapiCodegenHelpersPkg.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t AnyOfMixed) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *AnyOfMixed) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}

// ApplyDefaults sets default values for fields that are nil.
func (t *AnyOfMixed) ApplyDefaults() {
}

// #/components/schemas/AnyOfMixed/anyOf/2
type AnyOfMixedAnyOf2 struct {
	Inline *bool `form:"inline,omitempty" json:"inline,omitempty"`
}

// ApplyDefaults sets default values for fields that are nil.
func (s *AnyOfMixedAnyOf2) ApplyDefaults() {
}

// #/components/schemas/AnyOfNullable
type AnyOfNullable = oapiCodegenTypesPkg.Nullable[string]

// #/components/schemas/ObjectWithAnyOfProperty
type ObjectWithAnyOfProperty struct {
	Value *ObjectWithAnyOfPropertyValue `form:"value,omitempty" json:"value,omitempty"`
}

// ApplyDefaults sets default values for fields that are nil.
func (s *ObjectWithAnyOfProperty) ApplyDefaults() {
}

// #/components/schemas/ObjectWithAnyOfProperty/properties/value

type ObjectWithAnyOfPropertyValue struct {
	union json.RawMessage
}

// AsString0 returns the union data inside the ObjectWithAnyOfPropertyValue as a string.
func (t ObjectWithAnyOfPropertyValue) AsString0() (string, error) {
	var body string
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromString0 overwrites any union data inside the ObjectWithAnyOfPropertyValue as the provided string.
func (t *ObjectWithAnyOfPropertyValue) FromString0(v string) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeString0 performs a merge with any union data inside the ObjectWithAnyOfPropertyValue, using the provided string.
func (t *ObjectWithAnyOfPropertyValue) MergeString0(v string) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}
	merged, err := oapiCodegenHelpersPkg.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsInt1 returns the union data inside the ObjectWithAnyOfPropertyValue as a int.
func (t ObjectWithAnyOfPropertyValue) AsInt1() (int, error) {
	var body int
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromInt1 overwrites any union data inside the ObjectWithAnyOfPropertyValue as the provided int.
func (t *ObjectWithAnyOfPropertyValue) FromInt1(v int) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeInt1 performs a merge with any union data inside the ObjectWithAnyOfPropertyValue, using the provided int.
func (t *ObjectWithAnyOfPropertyValue) MergeInt1(v int) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}
	merged, err := oapiCodegenHelpersPkg.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsBool2 returns the union data inside the ObjectWithAnyOfPropertyValue as a bool.
func (t ObjectWithAnyOfPropertyValue) AsBool2() (bool, error) {
	var body bool
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromBool2 overwrites any union data inside the ObjectWithAnyOfPropertyValue as the provided bool.
func (t *ObjectWithAnyOfPropertyValue) FromBool2(v bool) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeBool2 performs a merge with any union data inside the ObjectWithAnyOfPropertyValue, using the provided bool.
func (t *ObjectWithAnyOfPropertyValue) MergeBool2(v bool) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}
	merged, err := oapiCodegenHelpersPkg.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t ObjectWithAnyOfPropertyValue) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *ObjectWithAnyOfPropertyValue) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}

// ApplyDefaults sets default values for fields that are nil.
func (t *ObjectWithAnyOfPropertyValue) ApplyDefaults() {
}

// #/components/schemas/ArrayOfAnyOf
type ArrayOfAnyOf = []ArrayOfAnyOfItem

// #/components/schemas/ArrayOfAnyOf/items

type ArrayOfAnyOfItem struct {
	union json.RawMessage
}

// AsSimpleObject returns the union data inside the ArrayOfAnyOfItem as a SimpleObject.
func (t ArrayOfAnyOfItem) AsSimpleObject() (SimpleObject, error) {
	var body SimpleObject
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromSimpleObject overwrites any union data inside the ArrayOfAnyOfItem as the provided SimpleObject.
func (t *ArrayOfAnyOfItem) FromSimpleObject(v SimpleObject) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeSimpleObject performs a merge with any union data inside the ArrayOfAnyOfItem, using the provided SimpleObject.
func (t *ArrayOfAnyOfItem) MergeSimpleObject(v SimpleObject) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}
	merged, err := oapiCodegenHelpersPkg.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsBaseProperties returns the union data inside the ArrayOfAnyOfItem as a BaseProperties.
func (t ArrayOfAnyOfItem) AsBaseProperties() (BaseProperties, error) {
	var body BaseProperties
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromBaseProperties overwrites any union data inside the ArrayOfAnyOfItem as the provided BaseProperties.
func (t *ArrayOfAnyOfItem) FromBaseProperties(v BaseProperties) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeBaseProperties performs a merge with any union data inside the ArrayOfAnyOfItem, using the provided BaseProperties.
func (t *ArrayOfAnyOfItem) MergeBaseProperties(v BaseProperties) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}
	merged, err := oapiCodegenHelpersPkg.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t ArrayOfAnyOfItem) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *ArrayOfAnyOfItem) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}

// ApplyDefaults sets default values for fields that are nil.
func (t *ArrayOfAnyOfItem) ApplyDefaults() {
}

// #/components/schemas/OneOfSimple

type OneOfSimple struct {
	union json.RawMessage
}

// AsSimpleObject returns the union data inside the OneOfSimple as a SimpleObject.
func (t OneOfSimple) AsSimpleObject() (SimpleObject, error) {
	var body SimpleObject
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromSimpleObject overwrites any union data inside the OneOfSimple as the provided SimpleObject.
func (t *OneOfSimple) FromSimpleObject(v SimpleObject) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeSimpleObject performs a merge with any union data inside the OneOfSimple, using the provided SimpleObject.
func (t *OneOfSimple) MergeSimpleObject(v SimpleObject) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}
	merged, err := oapiCodegenHelpersPkg.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsBaseProperties returns the union data inside the OneOfSimple as a BaseProperties.
func (t OneOfSimple) AsBaseProperties() (BaseProperties, error) {
	var body BaseProperties
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromBaseProperties overwrites any union data inside the OneOfSimple as the provided BaseProperties.
func (t *OneOfSimple) FromBaseProperties(v BaseProperties) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeBaseProperties performs a merge with any union data inside the OneOfSimple, using the provided BaseProperties.
func (t *OneOfSimple) MergeBaseProperties(v BaseProperties) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}
	merged, err := oapiCodegenHelpersPkg.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t OneOfSimple) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *OneOfSimple) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}

// ApplyDefaults sets default values for fields that are nil.
func (t *OneOfSimple) ApplyDefaults() {
}

// #/components/schemas/OneOfWithDiscriminator

type OneOfWithDiscriminator struct {
	union json.RawMessage
}

// AsCat returns the union data inside the OneOfWithDiscriminator as a Cat.
func (t OneOfWithDiscriminator) AsCat() (Cat, error) {
	var body Cat
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromCat overwrites any union data inside the OneOfWithDiscriminator as the provided Cat.
func (t *OneOfWithDiscriminator) FromCat(v Cat) error {
	v.PetType = "Cat"
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeCat performs a merge with any union data inside the OneOfWithDiscriminator, using the provided Cat.
func (t *OneOfWithDiscriminator) MergeCat(v Cat) error {
	v.PetType = "Cat"
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}
	merged, err := oapiCodegenHelpersPkg.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsDog returns the union data inside the OneOfWithDiscriminator as a Dog.
func (t OneOfWithDiscriminator) AsDog() (Dog, error) {
	var body Dog
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromDog overwrites any union data inside the OneOfWithDiscriminator as the provided Dog.
func (t *OneOfWithDiscriminator) FromDog(v Dog) error {
	v.PetType = "Dog"
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeDog performs a merge with any union data inside the OneOfWithDiscriminator, using the provided Dog.
func (t *OneOfWithDiscriminator) MergeDog(v Dog) error {
	v.PetType = "Dog"
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}
	merged, err := oapiCodegenHelpersPkg.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// Discriminator extracts the discriminator property value from the union data.
func (t OneOfWithDiscriminator) Discriminator() (string, error) {
	var discriminator struct {
		Discriminator string `json:"petType"`
	}
	err := json.Unmarshal(t.union, &discriminator)
	return discriminator.Discriminator, err
}

// ValueByDiscriminator returns the union member based on the discriminator value.
func (t OneOfWithDiscriminator) ValueByDiscriminator() (any, error) {
	discriminator, err := t.Discriminator()
	if err != nil {
		return nil, err
	}
	switch discriminator {
	case "Cat":
		return t.AsCat()
	case "Dog":
		return t.AsDog()
	default:
		return nil, errors.New("unknown discriminator value: " + discriminator)
	}
}

func (t OneOfWithDiscriminator) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *OneOfWithDiscriminator) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}

// ApplyDefaults sets default values for fields that are nil.
func (t *OneOfWithDiscriminator) ApplyDefaults() {
}

// #/components/schemas/OneOfWithDiscriminatorMapping

type OneOfWithDiscriminatorMapping struct {
	union json.RawMessage
}

// AsCat returns the union data inside the OneOfWithDiscriminatorMapping as a Cat.
func (t OneOfWithDiscriminatorMapping) AsCat() (Cat, error) {
	var body Cat
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromCat overwrites any union data inside the OneOfWithDiscriminatorMapping as the provided Cat.
func (t *OneOfWithDiscriminatorMapping) FromCat(v Cat) error {
	v.PetType = "cat"
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeCat performs a merge with any union data inside the OneOfWithDiscriminatorMapping, using the provided Cat.
func (t *OneOfWithDiscriminatorMapping) MergeCat(v Cat) error {
	v.PetType = "cat"
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}
	merged, err := oapiCodegenHelpersPkg.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsDog returns the union data inside the OneOfWithDiscriminatorMapping as a Dog.
func (t OneOfWithDiscriminatorMapping) AsDog() (Dog, error) {
	var body Dog
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromDog overwrites any union data inside the OneOfWithDiscriminatorMapping as the provided Dog.
func (t *OneOfWithDiscriminatorMapping) FromDog(v Dog) error {
	v.PetType = "dog"
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeDog performs a merge with any union data inside the OneOfWithDiscriminatorMapping, using the provided Dog.
func (t *OneOfWithDiscriminatorMapping) MergeDog(v Dog) error {
	v.PetType = "dog"
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}
	merged, err := oapiCodegenHelpersPkg.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// Discriminator extracts the discriminator property value from the union data.
func (t OneOfWithDiscriminatorMapping) Discriminator() (string, error) {
	var discriminator struct {
		Discriminator string `json:"petType"`
	}
	err := json.Unmarshal(t.union, &discriminator)
	return discriminator.Discriminator, err
}

// ValueByDiscriminator returns the union member based on the discriminator value.
func (t OneOfWithDiscriminatorMapping) ValueByDiscriminator() (any, error) {
	discriminator, err := t.Discriminator()
	if err != nil {
		return nil, err
	}
	switch discriminator {
	case "cat":
		return t.AsCat()
	case "dog":
		return t.AsDog()
	default:
		return nil, errors.New("unknown discriminator value: " + discriminator)
	}
}

func (t OneOfWithDiscriminatorMapping) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *OneOfWithDiscriminatorMapping) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}

// ApplyDefaults sets default values for fields that are nil.
func (t *OneOfWithDiscriminatorMapping) ApplyDefaults() {
}

// #/components/schemas/Cat
type Cat struct {
	PetType       string   `form:"petType" json:"petType"`
	Meow          string   `form:"meow" json:"meow"`
	WhiskerLength *float32 `form:"whiskerLength,omitempty" json:"whiskerLength,omitempty"`
}

// ApplyDefaults sets default values for fields that are nil.
func (s *Cat) ApplyDefaults() {
}

// #/components/schemas/Dog
type Dog struct {
	PetType    string   `form:"petType" json:"petType"`
	Bark       string   `form:"bark" json:"bark"`
	TailLength *float32 `form:"tailLength,omitempty" json:"tailLength,omitempty"`
}

// ApplyDefaults sets default values for fields that are nil.
func (s *Dog) ApplyDefaults() {
}

// #/components/schemas/OneOfInline

type OneOfInline struct {
	union json.RawMessage
}

// AsOneOfInlineOneOf0 returns the union data inside the OneOfInline as a OneOfInlineOneOf0.
func (t OneOfInline) AsOneOfInlineOneOf0() (OneOfInlineOneOf0, error) {
	var body OneOfInlineOneOf0
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromOneOfInlineOneOf0 overwrites any union data inside the OneOfInline as the provided OneOfInlineOneOf0.
func (t *OneOfInline) FromOneOfInlineOneOf0(v OneOfInlineOneOf0) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeOneOfInlineOneOf0 performs a merge with any union data inside the OneOfInline, using the provided OneOfInlineOneOf0.
func (t *OneOfInline) MergeOneOfInlineOneOf0(v OneOfInlineOneOf0) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}
	merged, err := oapiCodegenHelpersPkg.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsOneOfInlineOneOf1 returns the union data inside the OneOfInline as a OneOfInlineOneOf1.
func (t OneOfInline) AsOneOfInlineOneOf1() (OneOfInlineOneOf1, error) {
	var body OneOfInlineOneOf1
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromOneOfInlineOneOf1 overwrites any union data inside the OneOfInline as the provided OneOfInlineOneOf1.
func (t *OneOfInline) FromOneOfInlineOneOf1(v OneOfInlineOneOf1) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeOneOfInlineOneOf1 performs a merge with any union data inside the OneOfInline, using the provided OneOfInlineOneOf1.
func (t *OneOfInline) MergeOneOfInlineOneOf1(v OneOfInlineOneOf1) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}
	merged, err := oapiCodegenHelpersPkg.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t OneOfInline) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *OneOfInline) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}

// ApplyDefaults sets default values for fields that are nil.
func (t *OneOfInline) ApplyDefaults() {
}

// #/components/schemas/OneOfInline/oneOf/0
type OneOfInlineOneOf0 struct {
	OptionA *string `form:"optionA,omitempty" json:"optionA,omitempty"`
}

// ApplyDefaults sets default values for fields that are nil.
func (s *OneOfInlineOneOf0) ApplyDefaults() {
}

// #/components/schemas/OneOfInline/oneOf/1
type OneOfInlineOneOf1 struct {
	OptionB *int `form:"optionB,omitempty" json:"optionB,omitempty"`
}

// ApplyDefaults sets default values for fields that are nil.
func (s *OneOfInlineOneOf1) ApplyDefaults() {
}

// #/components/schemas/OneOfPrimitives

type OneOfPrimitives struct {
	union json.RawMessage
}

// AsString0 returns the union data inside the OneOfPrimitives as a string.
func (t OneOfPrimitives) AsString0() (string, error) {
	var body string
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromString0 overwrites any union data inside the OneOfPrimitives as the provided string.
func (t *OneOfPrimitives) FromString0(v string) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeString0 performs a merge with any union data inside the OneOfPrimitives, using the provided string.
func (t *OneOfPrimitives) MergeString0(v string) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}
	merged, err := oapiCodegenHelpersPkg.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsFloat321 returns the union data inside the OneOfPrimitives as a float32.
func (t OneOfPrimitives) AsFloat321() (float32, error) {
	var body float32
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromFloat321 overwrites any union data inside the OneOfPrimitives as the provided float32.
func (t *OneOfPrimitives) FromFloat321(v float32) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeFloat321 performs a merge with any union data inside the OneOfPrimitives, using the provided float32.
func (t *OneOfPrimitives) MergeFloat321(v float32) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}
	merged, err := oapiCodegenHelpersPkg.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsBool2 returns the union data inside the OneOfPrimitives as a bool.
func (t OneOfPrimitives) AsBool2() (bool, error) {
	var body bool
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromBool2 overwrites any union data inside the OneOfPrimitives as the provided bool.
func (t *OneOfPrimitives) FromBool2(v bool) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeBool2 performs a merge with any union data inside the OneOfPrimitives, using the provided bool.
func (t *OneOfPrimitives) MergeBool2(v bool) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}
	merged, err := oapiCodegenHelpersPkg.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t OneOfPrimitives) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *OneOfPrimitives) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}

// ApplyDefaults sets default values for fields that are nil.
func (t *OneOfPrimitives) ApplyDefaults() {
}

// #/components/schemas/ObjectWithOneOfProperty
type ObjectWithOneOfProperty struct {
	ID      *int                            `form:"id,omitempty" json:"id,omitempty"`
	Variant *ObjectWithOneOfPropertyVariant `form:"variant,omitempty" json:"variant,omitempty"`
}

// ApplyDefaults sets default values for fields that are nil.
func (s *ObjectWithOneOfProperty) ApplyDefaults() {
}

// #/components/schemas/ObjectWithOneOfProperty/properties/variant

type ObjectWithOneOfPropertyVariant struct {
	union json.RawMessage
}

// AsCat returns the union data inside the ObjectWithOneOfPropertyVariant as a Cat.
func (t ObjectWithOneOfPropertyVariant) AsCat() (Cat, error) {
	var body Cat
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromCat overwrites any union data inside the ObjectWithOneOfPropertyVariant as the provided Cat.
func (t *ObjectWithOneOfPropertyVariant) FromCat(v Cat) error {
	v.PetType = "Cat"
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeCat performs a merge with any union data inside the ObjectWithOneOfPropertyVariant, using the provided Cat.
func (t *ObjectWithOneOfPropertyVariant) MergeCat(v Cat) error {
	v.PetType = "Cat"
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}
	merged, err := oapiCodegenHelpersPkg.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsDog returns the union data inside the ObjectWithOneOfPropertyVariant as a Dog.
func (t ObjectWithOneOfPropertyVariant) AsDog() (Dog, error) {
	var body Dog
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromDog overwrites any union data inside the ObjectWithOneOfPropertyVariant as the provided Dog.
func (t *ObjectWithOneOfPropertyVariant) FromDog(v Dog) error {
	v.PetType = "Dog"
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeDog performs a merge with any union data inside the ObjectWithOneOfPropertyVariant, using the provided Dog.
func (t *ObjectWithOneOfPropertyVariant) MergeDog(v Dog) error {
	v.PetType = "Dog"
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}
	merged, err := oapiCodegenHelpersPkg.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// Discriminator extracts the discriminator property value from the union data.
func (t ObjectWithOneOfPropertyVariant) Discriminator() (string, error) {
	var discriminator struct {
		Discriminator string `json:"petType"`
	}
	err := json.Unmarshal(t.union, &discriminator)
	return discriminator.Discriminator, err
}

// ValueByDiscriminator returns the union member based on the discriminator value.
func (t ObjectWithOneOfPropertyVariant) ValueByDiscriminator() (any, error) {
	discriminator, err := t.Discriminator()
	if err != nil {
		return nil, err
	}
	switch discriminator {
	case "Cat":
		return t.AsCat()
	case "Dog":
		return t.AsDog()
	default:
		return nil, errors.New("unknown discriminator value: " + discriminator)
	}
}

func (t ObjectWithOneOfPropertyVariant) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *ObjectWithOneOfPropertyVariant) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}

// ApplyDefaults sets default values for fields that are nil.
func (t *ObjectWithOneOfPropertyVariant) ApplyDefaults() {
}

// #/components/schemas/AllOfWithOneOf
type AllOfWithOneOf struct {
	ID                   *int                  `form:"id,omitempty" json:"id,omitempty"`
	CreatedAt            *time.Time            `form:"createdAt,omitempty" json:"createdAt,omitempty"`
	AllOfWithOneOfAllOf1 *AllOfWithOneOfAllOf1 `json:"-"`
}

func (s AllOfWithOneOf) MarshalJSON() ([]byte, error) {
	result := make(map[string]any)

	if s.ID != nil {
		result["id"] = s.ID
	}
	if s.CreatedAt != nil {
		result["createdAt"] = s.CreatedAt
	}

	if s.AllOfWithOneOfAllOf1 != nil {
		unionData, err := json.Marshal(s.AllOfWithOneOfAllOf1)
		if err != nil {
			return nil, err
		}
		var unionMap map[string]any
		if err := json.Unmarshal(unionData, &unionMap); err == nil {
			for k, v := range unionMap {
				result[k] = v
			}
		}
	}

	return json.Marshal(result)
}

func (s *AllOfWithOneOf) UnmarshalJSON(data []byte) error {
	var raw map[string]json.RawMessage
	if err := json.Unmarshal(data, &raw); err != nil {
		return err
	}

	if v, ok := raw["id"]; ok {
		var val int
		if err := json.Unmarshal(v, &val); err != nil {
			return err
		}
		s.ID = &val
	}
	if v, ok := raw["createdAt"]; ok {
		var val time.Time
		if err := json.Unmarshal(v, &val); err != nil {
			return err
		}
		s.CreatedAt = &val
	}

	var AllOfWithOneOfAllOf1Val AllOfWithOneOfAllOf1
	if err := json.Unmarshal(data, &AllOfWithOneOfAllOf1Val); err != nil {
		return err
	}
	s.AllOfWithOneOfAllOf1 = &AllOfWithOneOfAllOf1Val

	return nil
}

// ApplyDefaults sets default values for fields that are nil.
func (s *AllOfWithOneOf) ApplyDefaults() {
}

// #/components/schemas/AllOfWithOneOf/allOf/1

type AllOfWithOneOfAllOf1 struct {
	union json.RawMessage
}

// AsCat returns the union data inside the AllOfWithOneOfAllOf1 as a Cat.
func (t AllOfWithOneOfAllOf1) AsCat() (Cat, error) {
	var body Cat
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromCat overwrites any union data inside the AllOfWithOneOfAllOf1 as the provided Cat.
func (t *AllOfWithOneOfAllOf1) FromCat(v Cat) error {
	v.PetType = "Cat"
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeCat performs a merge with any union data inside the AllOfWithOneOfAllOf1, using the provided Cat.
func (t *AllOfWithOneOfAllOf1) MergeCat(v Cat) error {
	v.PetType = "Cat"
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}
	merged, err := oapiCodegenHelpersPkg.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsDog returns the union data inside the AllOfWithOneOfAllOf1 as a Dog.
func (t AllOfWithOneOfAllOf1) AsDog() (Dog, error) {
	var body Dog
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromDog overwrites any union data inside the AllOfWithOneOfAllOf1 as the provided Dog.
func (t *AllOfWithOneOfAllOf1) FromDog(v Dog) error {
	v.PetType = "Dog"
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeDog performs a merge with any union data inside the AllOfWithOneOfAllOf1, using the provided Dog.
func (t *AllOfWithOneOfAllOf1) MergeDog(v Dog) error {
	v.PetType = "Dog"
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}
	merged, err := oapiCodegenHelpersPkg.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// Discriminator extracts the discriminator property value from the union data.
func (t AllOfWithOneOfAllOf1) Discriminator() (string, error) {
	var discriminator struct {
		Discriminator string `json:"petType"`
	}
	err := json.Unmarshal(t.union, &discriminator)
	return discriminator.Discriminator, err
}

// ValueByDiscriminator returns the union member based on the discriminator value.
func (t AllOfWithOneOfAllOf1) ValueByDiscriminator() (any, error) {
	discriminator, err := t.Discriminator()
	if err != nil {
		return nil, err
	}
	switch discriminator {
	case "Cat":
		return t.AsCat()
	case "Dog":
		return t.AsDog()
	default:
		return nil, errors.New("unknown discriminator value: " + discriminator)
	}
}

func (t AllOfWithOneOfAllOf1) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *AllOfWithOneOfAllOf1) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}

// ApplyDefaults sets default values for fields that are nil.
func (t *AllOfWithOneOfAllOf1) ApplyDefaults() {
}

// #/components/schemas/OneOfWithAllOf

type OneOfWithAllOf struct {
	union json.RawMessage
}

// AsOneOfWithAllOfOneOf0 returns the union data inside the OneOfWithAllOf as a OneOfWithAllOfOneOf0.
func (t OneOfWithAllOf) AsOneOfWithAllOfOneOf0() (OneOfWithAllOfOneOf0, error) {
	var body OneOfWithAllOfOneOf0
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromOneOfWithAllOfOneOf0 overwrites any union data inside the OneOfWithAllOf as the provided OneOfWithAllOfOneOf0.
func (t *OneOfWithAllOf) FromOneOfWithAllOfOneOf0(v OneOfWithAllOfOneOf0) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeOneOfWithAllOfOneOf0 performs a merge with any union data inside the OneOfWithAllOf, using the provided OneOfWithAllOfOneOf0.
func (t *OneOfWithAllOf) MergeOneOfWithAllOfOneOf0(v OneOfWithAllOfOneOf0) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}
	merged, err := oapiCodegenHelpersPkg.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsOneOfWithAllOfOneOf1 returns the union data inside the OneOfWithAllOf as a OneOfWithAllOfOneOf1.
func (t OneOfWithAllOf) AsOneOfWithAllOfOneOf1() (OneOfWithAllOfOneOf1, error) {
	var body OneOfWithAllOfOneOf1
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromOneOfWithAllOfOneOf1 overwrites any union data inside the OneOfWithAllOf as the provided OneOfWithAllOfOneOf1.
func (t *OneOfWithAllOf) FromOneOfWithAllOfOneOf1(v OneOfWithAllOfOneOf1) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeOneOfWithAllOfOneOf1 performs a merge with any union data inside the OneOfWithAllOf, using the provided OneOfWithAllOfOneOf1.
func (t *OneOfWithAllOf) MergeOneOfWithAllOfOneOf1(v OneOfWithAllOfOneOf1) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}
	merged, err := oapiCodegenHelpersPkg.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t OneOfWithAllOf) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *OneOfWithAllOf) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}

// ApplyDefaults sets default values for fields that are nil.
func (t *OneOfWithAllOf) ApplyDefaults() {
}

// #/components/schemas/OneOfWithAllOf/oneOf/0
type OneOfWithAllOfOneOf0 struct {
	ID        *int       `form:"id,omitempty" json:"id,omitempty"`
	CreatedAt *time.Time `form:"createdAt,omitempty" json:"createdAt,omitempty"`
	Variant   *string    `form:"variant,omitempty" json:"variant,omitempty"`
}

// ApplyDefaults sets default values for fields that are nil.
func (s *OneOfWithAllOfOneOf0) ApplyDefaults() {
}

// #/components/schemas/OneOfWithAllOf/oneOf/1
type OneOfWithAllOfOneOf1 struct {
	ID        *int       `form:"id,omitempty" json:"id,omitempty"`
	CreatedAt *time.Time `form:"createdAt,omitempty" json:"createdAt,omitempty"`
	Variant   *string    `form:"variant,omitempty" json:"variant,omitempty"`
}

// ApplyDefaults sets default values for fields that are nil.
func (s *OneOfWithAllOfOneOf1) ApplyDefaults() {
}

// #/components/schemas/TreeNode
type TreeNode struct {
	Value    *string    `form:"value,omitempty" json:"value,omitempty"`
	Children []TreeNode `form:"children,omitempty" json:"children,omitempty"`
}

// ApplyDefaults sets default values for fields that are nil.
func (s *TreeNode) ApplyDefaults() {
}

// #/components/schemas/TreeNode/properties/children
type TreeNodeChildren = []TreeNode

// #/components/schemas/LinkedListNode
type LinkedListNode struct {
	Value *int            `form:"value,omitempty" json:"value,omitempty"`
	Next  *LinkedListNode `form:"next,omitempty" json:"next,omitempty"`
}

// ApplyDefaults sets default values for fields that are nil.
func (s *LinkedListNode) ApplyDefaults() {
	if s.Next != nil {
		s.Next.ApplyDefaults()
	}
}

// #/components/schemas/RecursiveOneOf

type RecursiveOneOf struct {
	union json.RawMessage
}

// AsString0 returns the union data inside the RecursiveOneOf as a string.
func (t RecursiveOneOf) AsString0() (string, error) {
	var body string
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromString0 overwrites any union data inside the RecursiveOneOf as the provided string.
func (t *RecursiveOneOf) FromString0(v string) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeString0 performs a merge with any union data inside the RecursiveOneOf, using the provided string.
func (t *RecursiveOneOf) MergeString0(v string) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}
	merged, err := oapiCodegenHelpersPkg.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsRecursiveOneOfOneOf1 returns the union data inside the RecursiveOneOf as a RecursiveOneOfOneOf1.
func (t RecursiveOneOf) AsRecursiveOneOfOneOf1() (RecursiveOneOfOneOf1, error) {
	var body RecursiveOneOfOneOf1
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromRecursiveOneOfOneOf1 overwrites any union data inside the RecursiveOneOf as the provided RecursiveOneOfOneOf1.
func (t *RecursiveOneOf) FromRecursiveOneOfOneOf1(v RecursiveOneOfOneOf1) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeRecursiveOneOfOneOf1 performs a merge with any union data inside the RecursiveOneOf, using the provided RecursiveOneOfOneOf1.
func (t *RecursiveOneOf) MergeRecursiveOneOfOneOf1(v RecursiveOneOfOneOf1) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}
	merged, err := oapiCodegenHelpersPkg.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t RecursiveOneOf) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *RecursiveOneOf) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}

// ApplyDefaults sets default values for fields that are nil.
func (t *RecursiveOneOf) ApplyDefaults() {
}

// #/components/schemas/RecursiveOneOf/oneOf/1
type RecursiveOneOfOneOf1 struct {
	Nested *RecursiveOneOf `form:"nested,omitempty" json:"nested,omitempty"`
}

// ApplyDefaults sets default values for fields that are nil.
func (s *RecursiveOneOfOneOf1) ApplyDefaults() {
	if s.Nested != nil {
		s.Nested.ApplyDefaults()
	}
}

// #/components/schemas/ReadWriteOnly
type ReadWriteOnly struct {
	ID       int     `form:"id" json:"id"`
	Password string  `form:"password" json:"password"`
	Name     *string `form:"name,omitempty" json:"name,omitempty"`
}

// ApplyDefaults sets default values for fields that are nil.
func (s *ReadWriteOnly) ApplyDefaults() {
}

// #/components/schemas/WithDefaults
type WithDefaults struct {
	StringWithDefault *string  `form:"stringWithDefault,omitempty" json:"stringWithDefault,omitempty"`
	IntWithDefault    *int     `form:"intWithDefault,omitempty" json:"intWithDefault,omitempty"`
	BoolWithDefault   *bool    `form:"boolWithDefault,omitempty" json:"boolWithDefault,omitempty"`
	ArrayWithDefault  []string `form:"arrayWithDefault,omitempty" json:"arrayWithDefault,omitempty"`
}

// ApplyDefaults sets default values for fields that are nil.
func (s *WithDefaults) ApplyDefaults() {
	if s.StringWithDefault == nil {
		v := "default_value"
		s.StringWithDefault = &v
	}
	if s.IntWithDefault == nil {
		v := 42
		s.IntWithDefault = &v
	}
	if s.BoolWithDefault == nil {
		v := true
		s.BoolWithDefault = &v
	}
}

// #/components/schemas/WithConst
type WithConst struct {
	Version *string `form:"version,omitempty" json:"version,omitempty"`
	Type    *string `form:"type,omitempty" json:"type,omitempty"`
}

// ApplyDefaults sets default values for fields that are nil.
func (s *WithConst) ApplyDefaults() {
}

// #/components/schemas/WithConstraints
type WithConstraints struct {
	BoundedInt          *int     `form:"boundedInt,omitempty" json:"boundedInt,omitempty"`
	ExclusiveBoundedInt *int     `form:"exclusiveBoundedInt,omitempty" json:"exclusiveBoundedInt,omitempty"`
	MultipleOf          *int     `form:"multipleOf,omitempty" json:"multipleOf,omitempty"`
	BoundedString       *string  `form:"boundedString,omitempty" json:"boundedString,omitempty"`
	PatternString       *string  `form:"patternString,omitempty" json:"patternString,omitempty"`
	BoundedArray        []string `form:"boundedArray,omitempty" json:"boundedArray,omitempty"`
	UniqueArray         []string `form:"uniqueArray,omitempty" json:"uniqueArray,omitempty"`
}

// ApplyDefaults sets default values for fields that are nil.
func (s *WithConstraints) ApplyDefaults() {
}

// #/components/schemas/TypeArray31
type TypeArray31 struct {
	Name *string `form:"name,omitempty" json:"name,omitempty"`
}

// ApplyDefaults sets default values for fields that are nil.
func (s *TypeArray31) ApplyDefaults() {
}

// #/components/schemas/PrefixItems31
type PrefixItems31 = []string

// #/components/schemas/EmptySchema
type EmptySchema = any

// #/components/schemas/AnyValue
// Accepts any JSON value
type AnyValue = any

// #/components/schemas/ExplicitAny
type ExplicitAny = oapiCodegenTypesPkg.Nullable[string]

// #/components/schemas/ComplexNested
type ComplexNested struct {
	Metadata map[string]any          `form:"metadata,omitempty" json:"metadata,omitempty"`
	Items    []ComplexNestedItemItem `form:"items,omitempty" json:"items,omitempty"`
	Config   *ComplexNestedConfig    `form:"config,omitempty" json:"config,omitempty"`
}

// ApplyDefaults sets default values for fields that are nil.
func (s *ComplexNested) ApplyDefaults() {
}

// #/components/schemas/ComplexNested/properties/metadata
type ComplexNestedMetadata = map[string]any

// #/components/schemas/ComplexNested/properties/metadata/additionalProperties

type ComplexNestedMetadataValue struct {
	union json.RawMessage
}

// AsString0 returns the union data inside the ComplexNestedMetadataValue as a string.
func (t ComplexNestedMetadataValue) AsString0() (string, error) {
	var body string
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromString0 overwrites any union data inside the ComplexNestedMetadataValue as the provided string.
func (t *ComplexNestedMetadataValue) FromString0(v string) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeString0 performs a merge with any union data inside the ComplexNestedMetadataValue, using the provided string.
func (t *ComplexNestedMetadataValue) MergeString0(v string) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}
	merged, err := oapiCodegenHelpersPkg.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsInt1 returns the union data inside the ComplexNestedMetadataValue as a int.
func (t ComplexNestedMetadataValue) AsInt1() (int, error) {
	var body int
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromInt1 overwrites any union data inside the ComplexNestedMetadataValue as the provided int.
func (t *ComplexNestedMetadataValue) FromInt1(v int) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeInt1 performs a merge with any union data inside the ComplexNestedMetadataValue, using the provided int.
func (t *ComplexNestedMetadataValue) MergeInt1(v int) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}
	merged, err := oapiCodegenHelpersPkg.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsLBracketString2 returns the union data inside the ComplexNestedMetadataValue as a []string.
func (t ComplexNestedMetadataValue) AsLBracketString2() ([]string, error) {
	var body []string
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromLBracketString2 overwrites any union data inside the ComplexNestedMetadataValue as the provided []string.
func (t *ComplexNestedMetadataValue) FromLBracketString2(v []string) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeLBracketString2 performs a merge with any union data inside the ComplexNestedMetadataValue, using the provided []string.
func (t *ComplexNestedMetadataValue) MergeLBracketString2(v []string) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}
	merged, err := oapiCodegenHelpersPkg.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t ComplexNestedMetadataValue) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *ComplexNestedMetadataValue) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}

// ApplyDefaults sets default values for fields that are nil.
func (t *ComplexNestedMetadataValue) ApplyDefaults() {
}

// #/components/schemas/ComplexNested/properties/items
type ComplexNestedItem = []ComplexNestedItemItem

// #/components/schemas/ComplexNested/properties/items/items
type ComplexNestedItemItem struct {
	ID        *int       `form:"id,omitempty" json:"id,omitempty"`
	CreatedAt *time.Time `form:"createdAt,omitempty" json:"createdAt,omitempty"`
	Tags      []string   `form:"tags,omitempty" json:"tags,omitempty"`
}

// ApplyDefaults sets default values for fields that are nil.
func (s *ComplexNestedItemItem) ApplyDefaults() {
}

// #/components/schemas/ComplexNested/properties/config

type ComplexNestedConfig struct {
	union json.RawMessage
}

// AsComplexNestedConfigOneOf0 returns the union data inside the ComplexNestedConfig as a ComplexNestedConfigOneOf0.
func (t ComplexNestedConfig) AsComplexNestedConfigOneOf0() (ComplexNestedConfigOneOf0, error) {
	var body ComplexNestedConfigOneOf0
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromComplexNestedConfigOneOf0 overwrites any union data inside the ComplexNestedConfig as the provided ComplexNestedConfigOneOf0.
func (t *ComplexNestedConfig) FromComplexNestedConfigOneOf0(v ComplexNestedConfigOneOf0) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeComplexNestedConfigOneOf0 performs a merge with any union data inside the ComplexNestedConfig, using the provided ComplexNestedConfigOneOf0.
func (t *ComplexNestedConfig) MergeComplexNestedConfigOneOf0(v ComplexNestedConfigOneOf0) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}
	merged, err := oapiCodegenHelpersPkg.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsComplexNestedConfigOneOf1 returns the union data inside the ComplexNestedConfig as a ComplexNestedConfigOneOf1.
func (t ComplexNestedConfig) AsComplexNestedConfigOneOf1() (ComplexNestedConfigOneOf1, error) {
	var body ComplexNestedConfigOneOf1
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromComplexNestedConfigOneOf1 overwrites any union data inside the ComplexNestedConfig as the provided ComplexNestedConfigOneOf1.
func (t *ComplexNestedConfig) FromComplexNestedConfigOneOf1(v ComplexNestedConfigOneOf1) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeComplexNestedConfigOneOf1 performs a merge with any union data inside the ComplexNestedConfig, using the provided ComplexNestedConfigOneOf1.
func (t *ComplexNestedConfig) MergeComplexNestedConfigOneOf1(v ComplexNestedConfigOneOf1) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}
	merged, err := oapiCodegenHelpersPkg.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t ComplexNestedConfig) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *ComplexNestedConfig) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}

// ApplyDefaults sets default values for fields that are nil.
func (t *ComplexNestedConfig) ApplyDefaults() {
}

// #/components/schemas/ComplexNested/properties/config/oneOf/0
type ComplexNestedConfigOneOf0 struct {
	Mode  *string `form:"mode,omitempty" json:"mode,omitempty"`
	Value *string `form:"value,omitempty" json:"value,omitempty"`
}

// ApplyDefaults sets default values for fields that are nil.
func (s *ComplexNestedConfigOneOf0) ApplyDefaults() {
}

// #/components/schemas/ComplexNested/properties/config/oneOf/1
type ComplexNestedConfigOneOf1 struct {
	Mode    *string           `form:"mode,omitempty" json:"mode,omitempty"`
	Options map[string]string `form:"options,omitempty" json:"options,omitempty"`
}

// ApplyDefaults sets default values for fields that are nil.
func (s *ComplexNestedConfigOneOf1) ApplyDefaults() {
}

// #/components/schemas/ComplexNested/properties/config/oneOf/1/properties/options
type ComplexNestedConfigOneOf1Options = map[string]string

// #/components/schemas/StringMap
type StringMap = map[string]string

// #/components/schemas/ObjectMap
type ObjectMap = map[string]any

// #/components/schemas/NestedMap
type NestedMap = map[string]map[string]string

// #/components/schemas/NestedMap/additionalProperties
type NestedMapValue = map[string]string

// #/paths//inline-response/get/responses/200/content/application/json/schema
type GetInlineResponseJSONResponse struct {
	ID   int    `form:"id" json:"id"`
	Name string `form:"name" json:"name"`
}

// ApplyDefaults sets default values for fields that are nil.
func (s *GetInlineResponseJSONResponse) ApplyDefaults() {
}

// Base64-encoded, gzip-compressed OpenAPI spec.
var openAPISpecJSON = []string{
	"H4sIAAAAAAAC/+w8W28iOdbv/AqLmbdPNEm6px+QvgdCaIlZAgjI9Eaj2ZVDHYKnq+wal0nCjkbaH7G/",
	"cH/Jyq6CKl/qZtKtntbkifhybj43Hx9gMVAckwHqvn1z+eai2yF0ywYdhAQRIQzQiEUxhx3QhDwBWkMi",
	"0Gqzgwh3EHoCnhBGB6h7+eZC7kUogGTDSSzUsFydIByGKFFbUIyFAE4TtGUcMRyT3oYF8Ai004mx2CUS",
	"bz8hURyC/IjQI4j0A0IsBo4l3EkwkOMrtSyb5JDEjCaQHFcj1L26uOjm/xqkpbtP+wrLNowKoKK4EyEc",
	"xyHZKPT9XxNG9VmU8WeOIvQ9h+0Adb/rb1gUMwpUJP10bdJPSZg//Aob0e1IzgkNCYXekahaEUzU+qXO",
	"Q2tRpFAQU4QgQj+7UMQhhkGGz5rk8NuecAjsbQj1EAmcwxRHYE3EXMpLkKIk8j/ixHAkjlABj8AdKySq",
	"qp2J4IQ+quOMMccRCOBJ/3ep3gv5/x/p5nzuCCzlYoBOK09ICE1HO5aMkOD7nHFb3hpJ+fCW8QiLAdrv",
	"M3lW6NhHkpGjiM0W2dTn9P+2B35YmSglD2qmU60fToo10BMqvOGax6oBHnKOD96gsbEbISIgslSvkr8d",
	"4AC4fvgpHelMe9m1dgbzv30drlCqOCSi98CCQ2YxLHErqZxYpsuvWXDo5DaSjQzqDMfBZzWXbh6rOByG",
	"4foQQ7LMKOj+2Q8o2odChu8CAZUndCvXj9LlVUf0Bc5CZ8aN56X3/Pzck46yt+chUJmnBJ8LsZJljLno",
	"K4QBFrgJqoo4WhX7tiR0RrCSYGEGjQdCMT9YCyIQ2Cb823JMGk/wIvpxiEnLtOeYH+TI5MoMX7rpO/T/",
	"zf+yHYvl5Haynvw0Ruv7xXiFemgYhtmZJR5Q1RbTaR15ciienbb1ZLT9QCAM9KG3V47B9+/MwW3IsLU9",
	"YPuHEMxRuo8egJujqaDN0QfGQgsqFuAaW5PIGpcpkzkGESYW0D0n5tCOJUIGeov/+OmdY+y9RfvBpjO1",
	"RnM0xknyzLhGqcslHE/IzhnNTCk/uPq1ua9Qu4owsnNuCeP9u9N4rhY2jFQPHCDUptN4QYlawEh3nSYK",
	"OlcLpKCJtcn5ST/tlXIKMM35OKpti4xf7tEAnHS8JZCeIIUr18kqfC4f8i83oRYQ1Kachszg2pDAyWlU",
	"M84WMI77ci0/WnMLIHJPEcB7DwDvcx06tFcMuScHkDuVNiD0xEDzQS3AHPfpIWiu0gAcVoSgvxzcXw7u",
	"W3Rw3jnh7G46HV5Ps5TQNwmc7cMQP4TgmQTSbPvKKnlkE8V6Tj46r7NsHa4l1I5eIHTcanqoK2F0LYgT",
	"/WLhAucqD5bCS1mpA+m4xlkQy+91rqqkWY/Mj9LTmX69Is90ex4DHS4m6O2byxNodb1DTwQjRmG+7WN6",
	"mG/Rf//9HyR2gBgND+gZH5BgKMKfIAOEEYctcKAbCBQ1ObiE0A2gA9ujDaaUCbRh0QOhGZ5nInbpBlUP",
	"TN4YJrSdSyI8TaixTdgax4poj3D9Lr69jOxKbTc17PPSYAp5KM/4ywsZF9G+PoM+IWC4XA7vvV2/qoir",
	"9Kulp0htX223w51ZKXfUyZ1xkVBxLkTTiaSM+ENtf7jpE9/8TLyllb/yup/rvavqrcv9zuU8GAqJgOBc",
	"bs55QDnapJsGw7JsRI5A21QpFbCPROxGjCaCY5IV9Kp5iwidKATosjiKX46jFy1I8XYO8+sfx6O1t3co",
	"KnjbymBlUarB7cnUTkeuo5SyljoXAWwvgNvQLXMrMzZCqb7/jGL9Ew739dV6//hwczNZT+az4RQtlvPF",
	"eLme+N8UhkFA0rC/4CxOhvRQIXisLc7YT5/lXMBmjEJraFscnroYXEL+RNkzrVYjgwwZDIO2dHTcuuyC",
	"X6uv1QhaPeFZyNVTv/zQtshSa7BNxHKuKo9nd7f+vkwhH9N9pPOueXsoTEsvpmzz0hy4MgfepigmqURs",
	"HLqoTCRF+EXQGdT0POXJ2YAbpGlY7JMGBQmdqOyNAWhgX/DwRpAnMAalNoYgIC+HxJwwTsShSZ3MhfzS",
	"+P/K+P8kc5ltSclMaKZ5h9YVRAlidY6kGDUHttszXPZ0Ov+AemhCd8CJwHQD/ZE090SZmK8FXOMEbON8",
	"NQ+A0IYDlmmi8CrEqcnxiwAamFEdh2Hx2lV95dLZ7HbMC5cVoN39aFbLmXdhpjhRfPCuLebcAMQFHfCS",
	"hi7QBtIoYxNeBMf1NA8lcaoTJFYX9eSVz7D9faw1pxHwR7s7US9g57ymDmhOw0Mppy3xbwlPRMOuspag",
	"E9gwWsKalrR4ua3ZvXJbd5QwilRRwTvPpIf5dsFJRGSsyXVIL7/0qqWiZ2Fya6oa5eB8lKuNGueU3JKX",
	"XMWasvUFdD+NhU10X9J8LMj5nU+x8pUnOdnRe0Vy6yrlrNeVOudeRbmk5xSCvPTPXcXIYjnAuN1bNPlV",
	"ED00z6uCMBsro74hMnBFhMoIn5q4t3WrCvmq8B0Aq3L8hUxRESKVrsAd4140jXBjUm7Y43Fp4MJ70u3D",
	"LG0XByGdaRXJtziOCw82XxvleflLI1PljDIJbEAYQgF7rKRLLR3htoUqk8YeioA9VziZbENtjivB1C56",
	"3pHkE/Ap0EexK32FT7NB9ng2aw+Yf3oF1iSY2kUCk7AJX0qjJ1rcsfS3ZRRjKsEefp4cKgV+3SCJUpzZ",
	"WUwJdyV0GY0YzjiUR88Mpd89uMEV7wlzgul5D4+GXbdwOhWOp8Zt+oS+0fz2ejIb38gPi/lKVVHP6LNN",
	"3bb2OvxKd6I/xQmcAtewyLRlC4ZI/MVSadv1NXlLzRv20G8YTWREw91vkKmHMxLJ5Xh0t1yd2td9DWnN",
	"AWYsgHNvBk6ONzsSBhzoq78UH6nO5Dcl9BMEU5KI12PFej+DF+2oq8jT6cmIXMJmzxPyBJrLahe8GgfV",
	"9IG5zTdtdPLOUszhTf/jcrIeo/lseu+rmEvAwUdOhFYKavtYWuzsPzNSS0w4UMToX4U7wm9QpH0+8aOD",
	"qH+b9TmIm/GH4d10vULDmYy5s9Xa9yzU/Qi2eB8Kv76WAoAGYgqylaibffqnstFiS4iohGif3Qnkuyut",
	"r7YSjNldWwCjHd+po6EUkm8DTwHjz7/kZ6E6J9q6ueyXB+rFf4xOp18ocDeG1OzekhcIuudki7PVejmc",
	"zPzbLUqaTBoK7IHtaQCBq9HSoWARoSTaRwN0obenpIOXF/kwvGzCvXS0160QnLbdujDlsy6UUfZ+oCdN",
	"pazkq9EPpjhKOlltPYgIzW6rZsfOcfjqhx8KTlT9zEVj6Nn6Aer+42fc+9cv//d916S0YXfVqzYWnZrf",
	"KfltDw0pSBdn6DTH8jk7mRbj2bHxd7UYjyYfJiPvHPIQp7y+vdRsrFPaq220jzmbRmtj4oLDlqTHZCDW",
	"RBzny1o/dZRVCZyH80pNGbeL9T3qo+HsXmX2vocyjmJxSH93ZoB+/+P0yvBTMd3Vvi883GwgFgnC9IB+",
	"XM1naWZ8fEeOQ7IhwuxQ6pR2r/fsSostVTPCmq2G5YpzThViMR3/Hc3Gq/X4Bq3Wy7vR+m7pf4MaqVaN",
	"l5mWcTeMMa6vgJdk+tUNQSWPM5XPM9UPNPms3f1Z2mpa3olsrm6cFznu+ufc9mvu+3W/gSPwY1L1WzZu",
	"WVXKq/z2zOiWPNaWBj2rF1HhpuxRukh/cqrr2X35NXCAgydMN/nvipgV6QrlLlGdJkb6usHidrg4s4Hv",
	"FsdnNmcWeUgL5+fAbNmPmXrd85kwTrTuHDXO/xcAAP//5miNURBOAAA=",
}

// decodeOpenAPISpec decodes and decompresses the embedded spec.
func decodeOpenAPISpec() ([]byte, error) {
	joined := strings.Join(openAPISpecJSON, "")
	raw, err := base64.StdEncoding.DecodeString(joined)
	if err != nil {
		return nil, fmt.Errorf("decoding base64: %w", err)
	}
	r, err := gzip.NewReader(bytes.NewReader(raw))
	if err != nil {
		return nil, fmt.Errorf("creating gzip reader: %w", err)
	}
	defer r.Close()
	var out bytes.Buffer
	if _, err := out.ReadFrom(r); err != nil {
		return nil, fmt.Errorf("decompressing: %w", err)
	}
	return out.Bytes(), nil
}

// decodeOpenAPISpecCached returns a closure that caches the decoded spec.
func decodeOpenAPISpecCached() func() ([]byte, error) {
	var cached []byte
	var cachedErr error
	var once sync.Once
	return func() ([]byte, error) {
		once.Do(func() {
			cached, cachedErr = decodeOpenAPISpec()
		})
		return cached, cachedErr
	}
}

var openAPISpec = decodeOpenAPISpecCached()

// GetOpenAPISpecJSON returns the raw OpenAPI spec as JSON bytes.
func GetOpenAPISpecJSON() ([]byte, error) {
	return openAPISpec()
}
