// Code generated by oapi-codegen; DO NOT EDIT.

package output

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"strings"
	"sync"
)

// #/components/schemas/ArrayContainer
type ArrayContainer struct {
	Values               []string       `form:"values,omitempty" json:"values,omitempty"`
	AdditionalProperties map[string]any `json:"-"`
}

// Get returns the specified additional property value and whether it was found.
func (a ArrayContainer) Get(fieldName string) (value any, found bool) {
	if a.AdditionalProperties != nil {
		value, found = a.AdditionalProperties[fieldName]
	}
	return
}

// Set sets an additional property value.
func (a *ArrayContainer) Set(fieldName string, value any) {
	if a.AdditionalProperties == nil {
		a.AdditionalProperties = make(map[string]any)
	}
	a.AdditionalProperties[fieldName] = value
}

func (a *ArrayContainer) UnmarshalJSON(b []byte) error {
	object := make(map[string]json.RawMessage)
	err := json.Unmarshal(b, &object)
	if err != nil {
		return err
	}

	if raw, found := object["values"]; found {
		if err := json.Unmarshal(raw, &a.Values); err != nil {
			return fmt.Errorf("error reading 'values': %w", err)
		}
		delete(object, "values")
	}

	if len(object) != 0 {
		a.AdditionalProperties = make(map[string]any)
		for fieldName, fieldBuf := range object {
			var fieldVal any
			err := json.Unmarshal(fieldBuf, &fieldVal)
			if err != nil {
				return fmt.Errorf("error unmarshaling field %s: %w", fieldName, err)
			}
			a.AdditionalProperties[fieldName] = fieldVal
		}
	}
	return nil
}

func (a ArrayContainer) MarshalJSON() ([]byte, error) {
	var err error
	object := make(map[string]json.RawMessage)

	object["values"], err = json.Marshal(a.Values)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'values': %w", err)
	}

	for fieldName, field := range a.AdditionalProperties {
		object[fieldName], err = json.Marshal(field)
		if err != nil {
			return nil, fmt.Errorf("error marshaling '%s': %w", fieldName, err)
		}
	}
	return json.Marshal(object)
}

// ApplyDefaults sets default values for fields that are nil.
func (s *ArrayContainer) ApplyDefaults() {
}

// Base64-encoded, gzip-compressed OpenAPI spec.
var openAPISpecJSON = []string{
	"H4sIAAAAAAAC/2ySQXObQAyF7/yKN7hXAklu3DKdHnpJesgfWIOMlWJpuxKe+N93FnCwO72Jx6enJ4FG",
	"khC5Rfn80Dw0ZcFy0LYAzpSMVVo8Zr0AnH2kFj/NJsJT8/xYxOBHy2ztZJ4LYKC1ABJZVDGyqwCUT01T",
	"bo9AT9Yljj5PesHI5tADzBPLYDdgp+IkftsLhBhH7kLurj9M5f4tYN2RTuFfFfiW6NCi3NWdnqIKiVu9",
	"sFa/pBQu31U8sFAqiw3JPiu1WN6j1zF+idRC9x/U+SrtQBL2I8uA0Pec84bxV9JIyZkMbEj0Z+JEPVxB",
	"n1GNoEI4h8RB5pv4kbCfhtXyfz4tPE20AnGTv/bf4fXt/Uc7W4Uc/kpdcoTXt/ctRpB+FmQax7Af6cvj",
	"HMbp1hP4rAat8taV/eZYaVxyVVFZnNJdqu1A8/wblZ1Odv+pFnD5F4q/AQAA//9Bsr97qQIAAA==",
}

// decodeOpenAPISpec decodes and decompresses the embedded spec.
func decodeOpenAPISpec() ([]byte, error) {
	joined := strings.Join(openAPISpecJSON, "")
	raw, err := base64.StdEncoding.DecodeString(joined)
	if err != nil {
		return nil, fmt.Errorf("decoding base64: %w", err)
	}
	r, err := gzip.NewReader(bytes.NewReader(raw))
	if err != nil {
		return nil, fmt.Errorf("creating gzip reader: %w", err)
	}
	defer r.Close()
	var out bytes.Buffer
	if _, err := out.ReadFrom(r); err != nil {
		return nil, fmt.Errorf("decompressing: %w", err)
	}
	return out.Bytes(), nil
}

// decodeOpenAPISpecCached returns a closure that caches the decoded spec.
func decodeOpenAPISpecCached() func() ([]byte, error) {
	var cached []byte
	var cachedErr error
	var once sync.Once
	return func() ([]byte, error) {
		once.Do(func() {
			cached, cachedErr = decodeOpenAPISpec()
		})
		return cached, cachedErr
	}
}

var openAPISpec = decodeOpenAPISpecCached()

// GetOpenAPISpecJSON returns the raw OpenAPI spec as JSON bytes.
func GetOpenAPISpecJSON() ([]byte, error) {
	return openAPISpec()
}
