// Code generated by oapi-codegen; DO NOT EDIT.

package output

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"strings"
	"sync"
)

// #/components/schemas/SimpleDefaults
type SimpleDefaults struct {
	StringField *string  `form:"stringField,omitempty" json:"stringField,omitempty"`
	IntField    *int     `form:"intField,omitempty" json:"intField,omitempty"`
	BoolField   *bool    `form:"boolField,omitempty" json:"boolField,omitempty"`
	FloatField  *float32 `form:"floatField,omitempty" json:"floatField,omitempty"`
	Int64Field  *int64   `form:"int64Field,omitempty" json:"int64Field,omitempty"`
}

// ApplyDefaults sets default values for fields that are nil.
func (s *SimpleDefaults) ApplyDefaults() {
	if s.StringField == nil {
		v := "hello"
		s.StringField = &v
	}
	if s.IntField == nil {
		v := 42
		s.IntField = &v
	}
	if s.BoolField == nil {
		v := true
		s.BoolField = &v
	}
	if s.FloatField == nil {
		v := float32(3.14)
		s.FloatField = &v
	}
	if s.Int64Field == nil {
		v := int64(9223372036854775807)
		s.Int64Field = &v
	}
}

// #/components/schemas/NestedDefaults
type NestedDefaults struct {
	Name        *string                    `form:"name,omitempty" json:"name,omitempty"`
	Child       *SimpleDefaults            `form:"child,omitempty" json:"child,omitempty"`
	InlineChild *NestedDefaultsInlineChild `form:"inlineChild,omitempty" json:"inlineChild,omitempty"`
}

// ApplyDefaults sets default values for fields that are nil.
func (s *NestedDefaults) ApplyDefaults() {
	if s.Name == nil {
		v := "parent"
		s.Name = &v
	}
	if s.Child != nil {
		s.Child.ApplyDefaults()
	}
	if s.InlineChild != nil {
		s.InlineChild.ApplyDefaults()
	}
}

// #/components/schemas/NestedDefaults/properties/inlineChild
type NestedDefaultsInlineChild struct {
	Label *string `form:"label,omitempty" json:"label,omitempty"`
	Value *int    `form:"value,omitempty" json:"value,omitempty"`
}

// ApplyDefaults sets default values for fields that are nil.
func (s *NestedDefaultsInlineChild) ApplyDefaults() {
	if s.Label == nil {
		v := "inline-default"
		s.Label = &v
	}
	if s.Value == nil {
		v := 100
		s.Value = &v
	}
}

// #/components/schemas/MapWithDefaults
type MapWithDefaults struct {
	Prefix               *string           `form:"prefix,omitempty" json:"prefix,omitempty"`
	AdditionalProperties map[string]string `json:"-"`
}

func (s MapWithDefaults) MarshalJSON() ([]byte, error) {
	result := make(map[string]any)

	if s.Prefix != nil {
		result["prefix"] = s.Prefix
	}

	// Add additional properties
	for k, v := range s.AdditionalProperties {
		result[k] = v
	}

	return json.Marshal(result)
}

func (s *MapWithDefaults) UnmarshalJSON(data []byte) error {
	// Known fields
	knownFields := map[string]bool{
		"prefix": true,
	}

	var raw map[string]json.RawMessage
	if err := json.Unmarshal(data, &raw); err != nil {
		return err
	}

	if v, ok := raw["prefix"]; ok {
		var val string
		if err := json.Unmarshal(v, &val); err != nil {
			return err
		}
		s.Prefix = &val
	}

	// Collect additional properties
	s.AdditionalProperties = make(map[string]string)
	for k, v := range raw {
		if !knownFields[k] {
			var val string
			if err := json.Unmarshal(v, &val); err != nil {
				return err
			}
			s.AdditionalProperties[k] = val
		}
	}

	return nil
}

// ApplyDefaults sets default values for fields that are nil.
func (s *MapWithDefaults) ApplyDefaults() {
	if s.Prefix == nil {
		v := "map-"
		s.Prefix = &v
	}
}

// #/components/schemas/ArrayDefaults
type ArrayDefaults struct {
	Items []string `form:"items,omitempty" json:"items,omitempty"`
	Count *int     `form:"count,omitempty" json:"count,omitempty"`
}

// ApplyDefaults sets default values for fields that are nil.
func (s *ArrayDefaults) ApplyDefaults() {
	if s.Count == nil {
		v := 0
		s.Count = &v
	}
}

// #/components/schemas/AnyOfWithDefaults
type AnyOfWithDefaults struct {
	Value *AnyOfWithDefaultsValue `form:"value,omitempty" json:"value,omitempty"`
}

// ApplyDefaults sets default values for fields that are nil.
func (s *AnyOfWithDefaults) ApplyDefaults() {
}

// #/components/schemas/AnyOfWithDefaults/properties/value

type AnyOfWithDefaultsValue struct {
	union json.RawMessage
}

// AsAnyOfWithDefaultsValueAnyOf0 returns the union data inside the AnyOfWithDefaultsValue as a AnyOfWithDefaultsValueAnyOf0.
func (t AnyOfWithDefaultsValue) AsAnyOfWithDefaultsValueAnyOf0() (AnyOfWithDefaultsValueAnyOf0, error) {
	var body AnyOfWithDefaultsValueAnyOf0
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromAnyOfWithDefaultsValueAnyOf0 overwrites any union data inside the AnyOfWithDefaultsValue as the provided AnyOfWithDefaultsValueAnyOf0.
func (t *AnyOfWithDefaultsValue) FromAnyOfWithDefaultsValueAnyOf0(v AnyOfWithDefaultsValueAnyOf0) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeAnyOfWithDefaultsValueAnyOf0 performs a merge with any union data inside the AnyOfWithDefaultsValue, using the provided AnyOfWithDefaultsValueAnyOf0.
func (t *AnyOfWithDefaultsValue) MergeAnyOfWithDefaultsValueAnyOf0(v AnyOfWithDefaultsValueAnyOf0) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}
	merged, err := JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsAnyOfWithDefaultsValueAnyOf1 returns the union data inside the AnyOfWithDefaultsValue as a AnyOfWithDefaultsValueAnyOf1.
func (t AnyOfWithDefaultsValue) AsAnyOfWithDefaultsValueAnyOf1() (AnyOfWithDefaultsValueAnyOf1, error) {
	var body AnyOfWithDefaultsValueAnyOf1
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromAnyOfWithDefaultsValueAnyOf1 overwrites any union data inside the AnyOfWithDefaultsValue as the provided AnyOfWithDefaultsValueAnyOf1.
func (t *AnyOfWithDefaultsValue) FromAnyOfWithDefaultsValueAnyOf1(v AnyOfWithDefaultsValueAnyOf1) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeAnyOfWithDefaultsValueAnyOf1 performs a merge with any union data inside the AnyOfWithDefaultsValue, using the provided AnyOfWithDefaultsValueAnyOf1.
func (t *AnyOfWithDefaultsValue) MergeAnyOfWithDefaultsValueAnyOf1(v AnyOfWithDefaultsValueAnyOf1) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}
	merged, err := JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t AnyOfWithDefaultsValue) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *AnyOfWithDefaultsValue) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}

// ApplyDefaults sets default values for fields that are nil.
func (t *AnyOfWithDefaultsValue) ApplyDefaults() {
}

// #/components/schemas/AnyOfWithDefaults/properties/value/anyOf/0
type AnyOfWithDefaultsValueAnyOf0 struct {
	StringVal *string `form:"stringVal,omitempty" json:"stringVal,omitempty"`
}

// ApplyDefaults sets default values for fields that are nil.
func (s *AnyOfWithDefaultsValueAnyOf0) ApplyDefaults() {
	if s.StringVal == nil {
		v := "default-string"
		s.StringVal = &v
	}
}

// #/components/schemas/AnyOfWithDefaults/properties/value/anyOf/1
type AnyOfWithDefaultsValueAnyOf1 struct {
	IntVal *int `form:"intVal,omitempty" json:"intVal,omitempty"`
}

// ApplyDefaults sets default values for fields that are nil.
func (s *AnyOfWithDefaultsValueAnyOf1) ApplyDefaults() {
	if s.IntVal == nil {
		v := 999
		s.IntVal = &v
	}
}

// #/components/schemas/OneOfWithDefaults
type OneOfWithDefaults struct {
	Variant *OneOfWithDefaultsVariant `form:"variant,omitempty" json:"variant,omitempty"`
}

// ApplyDefaults sets default values for fields that are nil.
func (s *OneOfWithDefaults) ApplyDefaults() {
}

// #/components/schemas/OneOfWithDefaults/properties/variant

type OneOfWithDefaultsVariant struct {
	union json.RawMessage
}

// AsOneOfWithDefaultsVariantOneOf0 returns the union data inside the OneOfWithDefaultsVariant as a OneOfWithDefaultsVariantOneOf0.
func (t OneOfWithDefaultsVariant) AsOneOfWithDefaultsVariantOneOf0() (OneOfWithDefaultsVariantOneOf0, error) {
	var body OneOfWithDefaultsVariantOneOf0
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromOneOfWithDefaultsVariantOneOf0 overwrites any union data inside the OneOfWithDefaultsVariant as the provided OneOfWithDefaultsVariantOneOf0.
func (t *OneOfWithDefaultsVariant) FromOneOfWithDefaultsVariantOneOf0(v OneOfWithDefaultsVariantOneOf0) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeOneOfWithDefaultsVariantOneOf0 performs a merge with any union data inside the OneOfWithDefaultsVariant, using the provided OneOfWithDefaultsVariantOneOf0.
func (t *OneOfWithDefaultsVariant) MergeOneOfWithDefaultsVariantOneOf0(v OneOfWithDefaultsVariantOneOf0) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}
	merged, err := JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsOneOfWithDefaultsVariantOneOf1 returns the union data inside the OneOfWithDefaultsVariant as a OneOfWithDefaultsVariantOneOf1.
func (t OneOfWithDefaultsVariant) AsOneOfWithDefaultsVariantOneOf1() (OneOfWithDefaultsVariantOneOf1, error) {
	var body OneOfWithDefaultsVariantOneOf1
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromOneOfWithDefaultsVariantOneOf1 overwrites any union data inside the OneOfWithDefaultsVariant as the provided OneOfWithDefaultsVariantOneOf1.
func (t *OneOfWithDefaultsVariant) FromOneOfWithDefaultsVariantOneOf1(v OneOfWithDefaultsVariantOneOf1) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeOneOfWithDefaultsVariantOneOf1 performs a merge with any union data inside the OneOfWithDefaultsVariant, using the provided OneOfWithDefaultsVariantOneOf1.
func (t *OneOfWithDefaultsVariant) MergeOneOfWithDefaultsVariantOneOf1(v OneOfWithDefaultsVariantOneOf1) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}
	merged, err := JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t OneOfWithDefaultsVariant) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *OneOfWithDefaultsVariant) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}

// ApplyDefaults sets default values for fields that are nil.
func (t *OneOfWithDefaultsVariant) ApplyDefaults() {
}

// #/components/schemas/OneOfWithDefaults/properties/variant/oneOf/0
type OneOfWithDefaultsVariantOneOf0 struct {
	OptionA *string `form:"optionA,omitempty" json:"optionA,omitempty"`
}

// ApplyDefaults sets default values for fields that are nil.
func (s *OneOfWithDefaultsVariantOneOf0) ApplyDefaults() {
	if s.OptionA == nil {
		v := "option-a-default"
		s.OptionA = &v
	}
}

// #/components/schemas/OneOfWithDefaults/properties/variant/oneOf/1
type OneOfWithDefaultsVariantOneOf1 struct {
	OptionB *int `form:"optionB,omitempty" json:"optionB,omitempty"`
}

// ApplyDefaults sets default values for fields that are nil.
func (s *OneOfWithDefaultsVariantOneOf1) ApplyDefaults() {
	if s.OptionB == nil {
		v := 123
		s.OptionB = &v
	}
}

// #/components/schemas/AllOfWithDefaults
type AllOfWithDefaults struct {
	Base     *string `form:"base,omitempty" json:"base,omitempty"`
	Extended *int    `form:"extended,omitempty" json:"extended,omitempty"`
}

// ApplyDefaults sets default values for fields that are nil.
func (s *AllOfWithDefaults) ApplyDefaults() {
	if s.Base == nil {
		v := "base-value"
		s.Base = &v
	}
	if s.Extended == nil {
		v := 50
		s.Extended = &v
	}
}

// #/components/schemas/DeepNesting
type DeepNesting struct {
	Level1 *DeepNestingLevel1 `form:"level1,omitempty" json:"level1,omitempty"`
}

// ApplyDefaults sets default values for fields that are nil.
func (s *DeepNesting) ApplyDefaults() {
	if s.Level1 != nil {
		s.Level1.ApplyDefaults()
	}
}

// #/components/schemas/DeepNesting/properties/level1
type DeepNestingLevel1 struct {
	Name   *string                  `form:"name,omitempty" json:"name,omitempty"`
	Level2 *DeepNestingLevel1Level2 `form:"level2,omitempty" json:"level2,omitempty"`
}

// ApplyDefaults sets default values for fields that are nil.
func (s *DeepNestingLevel1) ApplyDefaults() {
	if s.Name == nil {
		v := "level1-name"
		s.Name = &v
	}
	if s.Level2 != nil {
		s.Level2.ApplyDefaults()
	}
}

// #/components/schemas/DeepNesting/properties/level1/properties/level2
type DeepNestingLevel1Level2 struct {
	Count  *int                           `form:"count,omitempty" json:"count,omitempty"`
	Level3 *DeepNestingLevel1Level2Level3 `form:"level3,omitempty" json:"level3,omitempty"`
}

// ApplyDefaults sets default values for fields that are nil.
func (s *DeepNestingLevel1Level2) ApplyDefaults() {
	if s.Count == nil {
		v := 2
		s.Count = &v
	}
	if s.Level3 != nil {
		s.Level3.ApplyDefaults()
	}
}

// #/components/schemas/DeepNesting/properties/level1/properties/level2/properties/level3
type DeepNestingLevel1Level2Level3 struct {
	Enabled *bool `form:"enabled,omitempty" json:"enabled,omitempty"`
}

// ApplyDefaults sets default values for fields that are nil.
func (s *DeepNestingLevel1Level2Level3) ApplyDefaults() {
	if s.Enabled == nil {
		v := false
		s.Enabled = &v
	}
}

// #/components/schemas/RequiredAndOptional
type RequiredAndOptional struct {
	RequiredWithDefault string  `form:"requiredWithDefault" json:"requiredWithDefault"`
	RequiredNoDefault   string  `form:"requiredNoDefault" json:"requiredNoDefault"`
	OptionalWithDefault *string `form:"optionalWithDefault,omitempty" json:"optionalWithDefault,omitempty"`
	OptionalNoDefault   *string `form:"optionalNoDefault,omitempty" json:"optionalNoDefault,omitempty"`
}

// ApplyDefaults sets default values for fields that are nil.
func (s *RequiredAndOptional) ApplyDefaults() {
	if s.OptionalWithDefault == nil {
		v := "optional-default"
		s.OptionalWithDefault = &v
	}
}

// Base64-encoded, gzip-compressed OpenAPI spec.
var openAPISpecJSON = []string{
	"H4sIAAAAAAAC/6xWS2/bOBC++1cMlAVyUuJX4kQ3Z4O9bbzYFumh6IG2RvEUFMmSlBuj6H8v9LQZ0XYk",
	"xydjHt/M8JuPlFQomKIIgsnV6GoYDEgkMhoAWLIcI3jEhGXcwjPjGRr4jMYOADaoDUkRQVDkKGbXJoJf",
	"vwcrmSopUFiTY5jVGlNW/AW4gAdmaAVKU0qWNmjgJ9k1xGUFUwR9olRxrIpWiQB2qzACufyOK1uZlJYK",
	"tSVsggCM1SRe/iHk8c5YZ5fOPXNVN4JgjZzLoHGRsAcwSFh8Qe0DmY4b61JKfgAgdyETPgCrM2zsCZfs",
	"UBMiS5f+HiZXo+n+FLfTd8+RSJ0yG5VZPuz78XgymY2Hk9u7m+lsdnM3nA0qWp/QWIwregyEYNYy4zFo",
	"XGXaIMyV4tvHfZbLjJ4sC5ZiJ3oV0yjsjt/VmtxD+UtjEsHlxfVue6+r1b12F/Jy73g5Cfz7LZRnhkNz",
	"5D/Olshd08GB3KHK+mFlCJy4Ta5VP2qbeQd2NBzWrC6KGUqJsjgmS1Iw/l8zCDARu9r9l6kvZNc9aVUa",
	"E3rtRGzKVFhP7mtxB+ZAVQPOtWZbSHKFeC6iwttzFLKYmvYkLIfcs7bCTo/89dtui2UmbKcrqqGWie0i",
	"cWcGEpBifrFU4+chZ7DZWsGipjtseEgtxxSzu+efGW+7jqrH3Z7qX1iGBh/TGgl7tC+//tyb9v6+JkoK",
	"PEXUIg85iyhNzF2kouoHUSVVLsr5WUSVGCHzX3ZntvZwFlej8aQRFedvuSqVlNt9BBUJu+ph17djyQz2",
	"ejryxLAQaNC/Or5aFDHGvZ6Zm+YqekRUINBYEi8QQppxS4ojcNwgLw8wD3kqIzrudgEyOuN5fvup8e4j",
	"LiuHeb67rYVj7MfsvMGtJ6Dz/o5bzqLByWFQb5OnGi0WRrAlb+/Lqe9jb9sJ4wbrFfoff2SkMYaNqTTN",
	"uEeHddhcxIsq6sg66Sp6X5+1bU/MHu+TdH2+c/EgdfrwqfPbN2Kri5O49ZH17aXOb/dSe0738icAAP//",
	"D156coUOAAA=",
}

// decodeOpenAPISpec decodes and decompresses the embedded spec.
func decodeOpenAPISpec() ([]byte, error) {
	joined := strings.Join(openAPISpecJSON, "")
	raw, err := base64.StdEncoding.DecodeString(joined)
	if err != nil {
		return nil, fmt.Errorf("decoding base64: %w", err)
	}
	r, err := gzip.NewReader(bytes.NewReader(raw))
	if err != nil {
		return nil, fmt.Errorf("creating gzip reader: %w", err)
	}
	defer r.Close()
	var out bytes.Buffer
	if _, err := out.ReadFrom(r); err != nil {
		return nil, fmt.Errorf("decompressing: %w", err)
	}
	return out.Bytes(), nil
}

// decodeOpenAPISpecCached returns a closure that caches the decoded spec.
func decodeOpenAPISpecCached() func() ([]byte, error) {
	var cached []byte
	var cachedErr error
	var once sync.Once
	return func() ([]byte, error) {
		once.Do(func() {
			cached, cachedErr = decodeOpenAPISpec()
		})
		return cached, cachedErr
	}
}

var openAPISpec = decodeOpenAPISpecCached()

// GetOpenAPISpecJSON returns the raw OpenAPI spec as JSON bytes.
func GetOpenAPISpecJSON() ([]byte, error) {
	return openAPISpec()
}

// JSONMerge merges two JSON-encoded objects. Fields from patch override
// fields in base. Both arguments must be valid JSON objects (or nil/null).
func JSONMerge(base, patch json.RawMessage) (json.RawMessage, error) {
	if len(base) == 0 || string(base) == "null" {
		return patch, nil
	}
	if len(patch) == 0 || string(patch) == "null" {
		return base, nil
	}

	var baseMap map[string]json.RawMessage
	if err := json.Unmarshal(base, &baseMap); err != nil {
		return nil, fmt.Errorf("JSONMerge: unmarshaling base: %w", err)
	}

	var patchMap map[string]json.RawMessage
	if err := json.Unmarshal(patch, &patchMap); err != nil {
		return nil, fmt.Errorf("JSONMerge: unmarshaling patch: %w", err)
	}

	for k, v := range patchMap {
		baseMap[k] = v
	}

	return json.Marshal(baseMap)
}
